### ISSUE TITLE
usb goto problems

### ISSUE THREAD

**Issue by voigtman** [rlf/uSkyBlock#444] opened 2015-08-07 02:20 UTC
usb v 2.3-HF7i
i'm hearing reports from players that new islands are spawning with nothing in the chests - I cannot test this at the moment. 
I've now had two players change names and have lost access to their islands
I updated to this version today from hf3 because I was having problems with biomes not changing and players were spontaneously losing islands without any sort of warning or cause. (I've had to re-register several.
Now with this version I have limited use of usb goto - it works only some of the time. when it doesn't I get this in console:
[21:08:12] [Server thread/INFO]: Voigtman issued server command: /usb goto StatusReport
[21:08:12] [Craft Scheduler Thread - 227/WARN]: Exception in thread "Craft Scheduler Thread - 227" 
[21:08:12] [Craft Scheduler Thread - 227/WARN]: org.apache.commons.lang.UnhandledException: Plugin uSkyBlock v2.3-HF7i generated an exception while executing task 132020
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.CraftOfflinePlayer cannot be cast to org.bukkit.entity.Player
	at us.talabrek.ultimateskyblock.command.admin.AbstractAsyncPlayerInfoCommand$1.run(AbstractAsyncPlayerInfoCommand.java:32)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by dutchy1001** [comment] 2015-08-07 08:40
The reason players loose access to their island is due to that the chunks wont load on command "/island home", this is also the cause "/usb goto" and probably a few other commands wont wont. As soon the holidays are over and/or our devs have time they will fix this.
When these are fixed we will release a new version for the public.

**Comment by voigtman** [comment] 2015-08-10 20:06
Well, I've reverted back a few. Just so you know - i'm not sure this has been reported but in that version the islands first chests are all empty.

**Comment by voigtman** [comment] 2015-08-10 20:06
Thank you, by the way.

**Comment by dutchy1001** [comment] 2015-09-09 19:47
fixed in the the latest pre-release (v2.3-HF8d)

**Closed by dutchy1001** 2015-09-09 19:47 UTC
