### ISSUE TITLE
Error with AsyncWorldEdit and Progress WatchDog

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#483] opened 2015-09-25 05:44 UTC
Versions: http://pastebin.com/raw.php?i=XHGdpKpL
Receiving the following error when performing world edit operations on a player's island, such as "/copy" or "/paste": http://pastebin.com/raw.php?i=Z8EREtCg

**Comment by rlf** [comment] 2015-09-25 07:21
Do you have a `messages.properties`, if so, could you share it?
The above traces give no clue to errors in the uSkyBlock code, so I need some more detective work to figure out what the root-cause is.

**Comment by BlackBeltPanda** [comment] 2015-09-25 08:00
No, I don't.
Tried enabling debug mode and received this error: http://pastebin.com/raw.php?i=Khz1bsi1
Tried World Edit operations again and only received this error: http://pastebin.com/raw.php?i=83tJnKCW

**Comment by rlf** [comment] 2015-09-25 08:43
Ye, that seems to be a bug, apparently, it currently requires you to set the level before enabling it.

I think the problem is, that you use AWE Premium, and apparently, that is not compatible with AWE 2.2.2 - which is the one we coded against (can't force all uSkyBlock users to use AWE premium).

I will try to have a look this afternoon, though, I don't have premium, and frankly do not intend to buy it, so I might be a bit at a loss here.

**Comment by rlf** [comment] 2015-09-25 08:45
Come to think of it, I guess that means you can post this as a bug for AWE - since they are obviously not playing nice with plugins trying to use the AWE 2.2.2 API, they really should be the ones to handle the above error (IMHO).

**Comment by csorrows** [comment] 2015-09-25 10:34
I agree. They should not require plugins to code against both the 'free' version and premium version separately. I would throw this back to the authors of AWE.

**Comment by BlackBeltPanda** [comment] 2015-10-03 17:12
Seems to be working now. =)

**Comment by dutchy1001** [comment] 2015-10-03 18:53
yeaa lot of stress with testing went into this, I havent seen this many alpha releases in a very long time

**Comment by dutchy1001** [comment] 2015-10-14 10:08
seems to be going well on the public test server too/
Think we can close this untill new issue's arise.

**Closed** 2016-01-10 19:55 UTC
Labels: A bug, T ready for test
