### ISSUE TITLE
usb goto problems again....

### ISSUE THREAD

**Issue by voigtman** [rlf/uSkyBlock#490] opened 2015-10-01 03:10 UTC
I just updated to the release from this morning to see if this will change, but any new island that has been made since my switch to 2.4 has failed to set a home in the island.yml file so /usb goto playername sends me to 0, 0, 0. This doesn't seem to have any affect on players being able to go to their islands however.  Also, (fingers crossed because I think this issue was already addressed) all of the new islands have had empty chests - leading to unhappy players :P 

I will keep you posted as I find out more in regards to the chests.

**Comment by dutchy1001** [comment] 2015-10-01 06:48
Do you use AsyncWorldEdit? If not that might be the issue. We have been working on this to get it working "nice" together but forgot to test it without this plugin. 
You can get it from [here](https://www.spigotmc.org/threads/asyncworldedit.11441/) for a temporally fix untill we have it working again without this plugin.

**Comment by voigtman** [comment] 2015-10-01 06:52
Yes I have been using it for a few months already. 

--
Jason Houge
http://jasonhougecom

**Comment by dutchy1001** [comment] 2015-10-01 06:56
what version?

**Comment by voigtman** [comment] 2015-10-01 07:06
The issue first came up with the first release of uSkyBlock 2.4 paired with 
AsynchWorldedit 2.2.2

**Comment by rlf** [comment] 2015-10-01 07:06
The empty chests was something that should be fixed in v2.4.5 - and was introduced by AsyncWorldEdit being used to paste the island (the plugin couldn't find a chest when looking for it, because AWE wasn't done yet).

Reg. the `/usb goto` is that the only command affected? And is it only when trying to go to newly created islands?

Please also note, that you cannot rely on the .yml files, until you have done `/usb cache flush` - since the data is not saved to file immediately (but rather periodically).

**Comment by voigtman** [comment] 2015-10-01 07:32
I must have missed reading about /USB cache flush. Is this a 1 time thing or should I set it up to automatically run every so often? I have island ymls with no homes I can usb goto and they're a week old. My server restarts every 12 hrs so if it's a something that should be cleared up on a restart, it's been missed.  I'll watch and see how things go over the next couple of days and see if anything has changed. I'll run that command when I wake up tomorrow. 

--
Jason Houge
http://jasonhougecom

**Comment by voigtman** [comment] 2015-10-01 07:38
As far as I can tell, it's the only command so far. Luckily we have back up methods of getting to islands if need be. 

Also... That reminds me... If this has never been brought up before The island kick should have some kind of admin bypass. And that obsidian to lava  bug eats a stack of buckets.... Sorry I'm tired and going to bed. I'll stop rambling now. 

--
Jason Houge
http://jasonhougecom

**Comment by rlf** [comment] 2015-10-01 12:02
The bucket is known - but apparently we just forget it all the time, and I think the kick has an admin bypass, depending on what you mean with that?

**Comment by dutchy1001** [comment] 2015-10-02 10:26
I've tried to reproduce this but every time I use the "/usb goto" command it works

**Comment by voigtman** [comment] 2015-10-02 15:03
USB goto works, but what ever the coords are that directs you to those islands (I believe the player's home in the island yml?) is remaining 0 0 0 for new islands 

--
Jason Houge
http://jasonhougecom

**Comment by voigtman** [comment] 2015-10-02 15:04
Older islands, usb goto takes me right to their island just as expected. 


--
Jason Houge
http://jasonhougecom

**Comment by voigtman** [comment] 2015-10-02 15:22
Ok, it's the player yml, not the island yml, that is the issue. And the issue for new islands has been resolved with the update I made... So the issue must only exist for the islands that were generated during the 2.4 release. Well, that settles that. As for chests being empty or full - I need to check in that yet.

--
Jason Houge
http://jasonhougecom

**Comment by dutchy1001** [comment] 2015-10-02 15:31
If a player joins for the first time and doesnt have an island it should give a "no island" message in red. The coordinates in the player.yml  are indeed still 0 0 0. When an island is deleted by an admin or the purge system the player file is reset to coordinates 0 0 0 again and the "no island" message should appear in the chat again.
Tried it just again with our latest release v2.4.5 but no problems

**Comment by voigtman** [comment] 2015-10-02 15:55
correct, latest version has no problems. I just upgraded a few days ago. 2.4 (original) has issues with it. but that's not important now.
Seems chests work just fine also. Case closed! Thanks for your support as always.

just one more question - maybe I need to make a new ticket for it, as it's a request. 
A way to set home for a player other than registering their island. I have had a couple of instances where players had set home, and didn't realize they built over that spot and every time they go home, they spawn in a wall and die on repeat.

**Comment by dutchy1001** [comment] 2015-10-14 10:09
closed as seems to be fixed in later version.

**Closed by dutchy1001** 2015-10-14 10:09 UTC
