### ISSUE TITLE
NameChange not always updating correctly

### ISSUE THREAD

**Issue by mcraftpete** [rlf/uSkyBlock#314] opened 2015-03-15 11:59 UTC
Sometimes when a player changes name it is not updating their data correctly.
I have a player example where they changed their name , they have been playing server for some time but it has not updated the WG region.
The original player name is Tom_Boy_Tilly and new name is TillyVictini , on joining the usb player data name has changed to the new name , the island data has the old name (not sure if that's suppose to change or simply uses the uuids from the file in usb folder ?) and the WG region seems to have the correct uuid stored but old name , player cannot do anything on island.
Here is the WG ..
-4840,5940island:
        min: {x: -4892.0, y: 0.0, z: 5888.0}
        max: {x: -4788.0, y: 255.0, z: 5992.0}
        members: {}
        flags: {entry: allow, greeting: Â§d** You are entering Â§bTom_Boy_Tilly's Â§disland.,
            pvp: deny, farewell: Â§d** You are leaving Â§bTom_Boy_Tilly's Â§disland.}
        owners:
            players: [herobine_199, fizzy2014, tom_boy_tilly]
            unique-ids: [498203b2-5e90-4999-8ee6-1486da329bce]
        type: cuboid
        priority: 100

That uuid is definitely correct for Tilly , but they cant do anything at all , most of time players update correctly but we get a few that do not for no reason.

Also if an older player that comes on server that hasn't been on for a while , when they first join their region does not create , a simply reolg fixes it but its like it doesn't recognize them the first time , not sure if this is 2 separate issues or same issue with onjoin update.

**Comment by rlf** [comment] 2015-03-15 13:38
v2.2-HF8 - We will await an upgrade to v2.3-HF1, and see if this problem persist.

**Comment by mcraftpete** [comment] 2015-03-23 21:26
This problem still is present , I have been on server today and at least 3 players in 40 minutes logged in and each did not create a region around their existing island , I made all 3 relog and 1 of them updated after a relog , the other one still has not updated even after reclogging a 2nd time , I checked it was their island etc and checked config files and all looked good , checked wg and region definitely did not create.
At times I have had server crashes which at minute after seeing 1 of them directly after 1 of the 3 players logged in I cant help but point at wg issues.

**Comment by rlf** [comment] 2015-03-26 11:53
Sounds weird.
Does the server-log say anything sensible?

**Comment by mcraftpete** [comment] 2015-03-26 12:00
Hi,
I havent seen anything sensible , i dont know the exact process but at times a player that had an island who hasnt been on server for a while comes on , it doesnt update their wg data so it does not create a region at their island , sometimes asking a player to relog , they come back and it does create it , sometimes even after a relog they still do not have a zone , problem is i cant really manually add one either as that would likely create problems so the player cannot play :(
I will try to keep tabs each time it happens so i can check logs of first visit etc , but its hard as some come on and go off without your knowledge so we lose the player.

**Comment by rlf** [comment] 2015-03-26 15:21
It sounds like an exception occurs for the player, and that is why the WG region isn't being updated - that is why I ask for the server-log.

**Comment by mcraftpete** [comment] 2015-03-28 18:18
Ok , so I can see an error log of something , I think this is an older player that returned to server , pretty sure its same error as when they change their name...
[12:09:03] [Craft Scheduler Thread - 1565/WARN]: [uSkyBlock] Error during rank generation
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:1.8.0_05]
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source) ~[?:1.8.0_05]
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source) ~[?:1.8.0_05]
	at org.bukkit.configuration.MemorySection.mapChildrenKeys(MemorySection.java:712) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.configuration.MemorySection.getKeys(MemorySection.java:83) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	at us.talabrek.ultimateskyblock.uuid.FilePlayerDB.getUUIDFromName(FilePlayerDB.java:32) ~[uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.uuid.FilePlayerDB.getDisplayName(FilePlayerDB.java:56) ~[uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.util.PlayerUtil.getPlayerDisplayName(PlayerUtil.java:18) ~[uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.island.IslandLogic.createIslandLevel(IslandLogic.java:213) ~[uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.island.IslandLogic.generateTopTen(IslandLogic.java:187) [uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.command.admin.GenTopTenCommand$1.run(GenTopTenCommand.java:26) [uSkyBlock.jar:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_05]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]

**Comment by rlf** [comment] 2015-03-30 16:47
Ah, that one should've been fixed a couple of releases ago.

**Comment by mcraftpete** [comment] 2015-03-31 22:09
oh , which version has the fix then ?

**Comment by rlf** [comment] 2015-04-01 23:36
https://github.com/rlf/uSkyBlock/commit/ce16d59b4f4b74157a64568bf8e77e431c3a5eac

**Comment by mcraftpete** [comment] 2015-04-06 20:06
ok so I have been running the new version as you said ..and today I got another blip which looks almost same error ...2.3-HF1c is my skyblocvk version now after updating and this is the error that just happened...
It kicked `most` of the players on the server but didn't completely force a restart...

[14:01:11] [Server thread/INFO]: badboywolf1 butter butter butter butter butter butter
[14:01:13] [User Authenticator #383/INFO]: UUID of player KID_brother is 77d3c2bf-d84e-4986-86cc-fcee0947f93e
[14:01:13] [Server thread/INFO]: [SpawnTP] Sent KID_brother to spawn
[14:01:13] [Craft Scheduler Thread - 260/WARN]: [uSkyBlock] Error during rank generation
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:1.8.0_05]
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source) ~[?:1.8.0_05]
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source) ~[?:1.8.0_05]
	at org.bukkit.configuration.MemorySection.mapChildrenKeys(MemorySection.java:712) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.configuration.MemorySection.getKeys(MemorySection.java:83) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	at us.talabrek.ultimateskyblock.uuid.FilePlayerDB.getUUIDFromName(FilePlayerDB.java:32) ~[uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.uuid.FilePlayerDB.getDisplayName(FilePlayerDB.java:56) ~[uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.util.PlayerUtil.getPlayerDisplayName(PlayerUtil.java:18) ~[uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.island.IslandLogic.createIslandLevel(IslandLogic.java:208) ~[uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.island.IslandLogic.generateTopTen(IslandLogic.java:187) [uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.island.IslandLogic$1.run(IslandLogic.java:157) [uSkyBlock.jar:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_05]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
[14:01:13] [Server thread/INFO]: KID_brother[/71.162.234.120:56604] logged in with entity id 351538 at ([SkyBlock] -97.5, 4.5, -893.5)
[14:01:14] [pool-10-thread-1/INFO]: Creating empty config: /home/multicraft/servers/server6/plugins/Essentials/userdata/77d3c2bf-d84e-4986-86cc-fcee0947f93e.yml

Hope this helps :)

**Comment by rlf** [comment] 2015-04-15 22:30
Should be fixed in v2.3-HF3

**Comment by dutchy1001** [comment] 2015-04-16 19:57
is this related also to #285 ? 

285 is tested to be working OK now.

**Comment by rlf** [comment] 2015-04-16 22:06
A bit, I think the root-cause of this, was caused by what @Brokkonaut posted in his pull-request - though - the code is obviously not thread-safe, but probably should be...

**Comment by dutchy1001** [comment] 2015-04-16 22:15
lets hope it's fixed it then, just need to wait and see for mcpete and the big server to see if it's doing the job then

**Comment by dutchy1001** [comment] 2015-04-17 15:53
As this has been tested in the previous release I'm gonna mark it as "tested awaiting reporter"

**Comment by mcraftpete** [comment] 2015-05-03 17:34
Hi,
I took a long time to come back with this as it has been better then before , I do still get player reports of not adding to island/region which could be old data , I have been trying to narrow it down without success.
I also have high timings for namechange . I took a timing when the server was only 45 players on..
http://timings.aikar.co/?url=10979863
So I feel something is still not right with name changing.

**Comment by dutchy1001** [comment] 2015-08-26 19:33
fixed in v2.3-HF7i

Closed

**Closed by dutchy1001** 2015-08-26 19:33 UTC
Labels: tested awaiting reporter
