### ISSUE TITLE
Challenges not rewarding and causing error

### ISSUE THREAD

**Issue by rocky143** [rlf/uSkyBlock#168] opened 2015-01-21 10:27 UTC
When completing a challenge, I would get this error: http://pastebin.com/KTifand7
It was working just fine before I updated to the latest version of the plugin from spigot to fix the party issue. The error is not the only thing that happens, it also wont give the rewards.
I have already re-generated my challenges.yml but that does not seem to fix the issue.

**Comment by dutchy1001** [comment] 2015-01-21 10:39
I get  a error on completing the "Cobblestone" challange, I do get the rewards but the challange is not "completed" in the GUI (http://pastebin.com/uff3v8Ua).

When then trying to complete the "applecollector" I get no reward no apple is showing in the GUI (http://pastebin.com/uSN6RpvR)

using RC1.62

**Comment by rlf** [comment] 2015-01-21 12:32
Aaah, regression. Hotfix on it's way.

**Comment by dutchy1001** [comment] 2015-01-21 12:34
thought it was getting warmer

**Comment by rlf** [comment] 2015-01-21 12:40
Pushed - ready when travis has build RC1.63.

**Comment by dutchy1001** [comment] 2015-01-21 13:16
Working with version v2.0.1RC1.63

**Comment by TwiiXoRino** [comment] 2015-01-21 16:02
I can't use the challenges. When i try /challenges or /c there comes an error.
Error: An Internal error occured while attemtping to perform this command
Server log: [17:02:39] [Server thread/INFO]: jensbenz98 issued server command: /challenges
[17:02:39] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'challenges' in plugin uSkyBlock v2.0.1-RC1.63
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.milkbowl.vault.item.Items
	at us.talabrek.ultimateskyblock.handler.VaultHandler.getItemName(VaultHandler.java:74) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.Challenge.getRequiredItems(Challenge.java:102) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.Challenge.getDisplayItem(Challenge.java:151) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.getItemStack(ChallengeLogic.java:368) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.populateChallengeRank(ChallengeLogic.java:456) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.populateChallengeRank(ChallengeLogic.java:427) ~[?:?]
	at us.talabrek.ultimateskyblock.SkyBlockMenu.displayChallengeGUI(SkyBlockMenu.java:651) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.ChallengesCommand.onCommand(ChallengesCommand.java:38) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	... 13 more

**Comment by dutchy1001** [comment] 2015-01-21 16:07
@TwiiXoRino 
we need more info, tell us what versions you use (version numbers, not "the latest") of the plugin, dependencies and server.

**Comment by dutchy1001** [comment] 2015-01-21 16:10
Just looking again you use Spigot-1.7.9-R0.2 and it seems that Vault is out dated. These updates are for craftbukkit/Spigot 1.8 and up only.

Update first and see if the challenges wotk then. Craftbukkit/Spigot 1.8 is a must or no support can be given.

**Comment by rlf** [comment] 2015-01-21 16:32
Wrong version of Vault - it seems. Use 1.5 or above.

**Comment by dutchy1001** [comment] 2015-01-21 20:11
closing this issue as the main issue has been resolved

**Closed by dutchy1001** 2015-01-21 20:11 UTC
Labels: ready for test
