### ISSUE TITLE
Islands Dissappear/2x Name Change

### ISSUE THREAD

**Issue by DogsPaw** [rlf/uSkyBlock#310] opened 2015-03-14 05:08 UTC
I know I'm posting this with almost nothing to go on. It's all I have.
uSkyBlock: 2.3-HF1a
WorldGuard: #1586
Vault: 1.5.3

After some mishaps with the Purge command on an older version without the knowledge it was partially broken, then 100% broke with the next update, now somewhat fixed with the current update. I blamed some island mishaps on me running the purge command during those times. 
Issue: #298

Now I'm having quite a small issue, which is growing quite fast. Players who have islands, will log out for a bit (couple hours to a couple days) no commands will be run that would modify anything in that time (ex. Purge) come back on to a few things so far, their island gone with a new player on it, but /USB goto (Old Player) will take me to that new players island, or it will say it's their island according to the region, but /USB island info says something different. There is not a single error in the console. Just says they joined and their player data was loaded. No error upon them logging off either. This started with 2 players a few days ago and has now progressed to 6 players.

Also, a player changed their name and it converted successfully but apparently changed it again but the island remained the same. Didn't convert again. That was a quick fix of just going to the island and running the register command.

**Comment by rlf** [comment] 2015-03-14 11:13
Sounds like you might have lost the World-Guard regions of some of the islands.

Take a look, in the `regions.yml` file under World-Guard, and if this is the case, try to fix it with `/usb island protectall` - note this might take a while, and consume quite a lot of server-resources.

**Comment by rlf** [comment] 2015-03-14 11:15
Note: The problem is (most likely) a combination of missing world-guard regions, and a wrong value of the lastIslandConfig.yml - Another workaround (to stop this from happening), is manually modifying the `lastIslandConfig.yml` to correctly reflect the "last-island", and then retstart the server.

**Comment by DogsPaw** [comment] 2015-03-14 17:37
"Completed protect all in 2s, 154 new regions were created"

For the lastIslandConfig.yml, it says:
    lastIslandX: 1650
    lastIslandZ: -2530

In the Islands file, in order, the last island appears as 2530, -2530 and then it's followed by 7 players that are labeled as names, not Coords, but opening their .yml file it just says version: 1

Would I modify the lastIslandConfig with the 2530, -2530?

**Comment by rlf** [comment] 2015-03-15 10:57
Yes

**Comment by DogsPaw** [comment] 2015-03-18 00:03
So I stopped the server, made the changes, the issue persisted, went back to the lastIslandConfig and it now reads 2640,440 when it was a matched 2530,-2530. The last island in the numerical list is 2640,2640.

**Comment by DogsPaw** [comment] 2015-03-19 02:53
Issue still persists with said changes implemented.

**Comment by DogsPaw** [comment] 2015-03-19 03:08
So I ran the ProtectAll command again, and it generated another 30+ regions, but a lot of them looked like this: 
New protected region created for 's Island by CONSOLE

While others looked like this:
New protected region created for ManyBigBears's Island by CONSOLE

**Comment by DogsPaw** [comment] 2015-03-21 04:45
New Islands are being created within abandoned islands, don't know if this is still being looked at or if there are other ways to possibly approach this problem.

**Comment by DogsPaw** [comment] 2015-03-22 17:48
Apart of this ticket included name changes, if a player changes their name again the island won't update it.
If it changes once, it's good, the island will convert the name, but if it's changed again, the island simply ignores it.

**Comment by DogsPaw** [comment] 2015-03-25 08:03
Is there any other possible fixes? Or should I give up with this post?

**Comment by dutchy1001** [comment] 2015-03-25 09:34
As much I love to help you out here, I cant code or see were the issue is what breaks this. Our dev's are atm busy with work and school so you have to bare with me.

**Comment by dutchy1001** [comment] 2015-04-12 10:59
As this is now answered in issue #344 i will close this one.

**Closed by dutchy1001** 2015-04-12 10:59 UTC
