### ISSUE TITLE
/is warp <tab> will show offline players

### ISSUE THREAD

**Issue by rocky143** [rlf/uSkyBlock#166] opened 2015-01-21 02:10 UTC
Seem to me like some players are reporting that when they do "/is warp name"(in half) and tries to auto complete it by pressing Tab, it show random player names that are not even online on the server.
Would be great if this issue can be fixed.

**Comment by rlf** [comment] 2015-01-21 07:46
You can warp to offline players islands as well.
So this is not a bug, it's a feature.
It should (how-ever) only show players that are registered in uSkyBlock.

**Comment by rlf** [comment] 2015-01-21 07:47
And... by "random players" I assume they all match the rules of tab-completion?

**Comment by rocky143** [comment] 2015-01-21 08:24
Yes that is correct but it would be great to have an option in the config so we can only allow tab completion for online player since many are used the online players on my server, they have been asking again and again.

**Comment by rlf** [comment] 2015-01-21 08:48
@dutchy1001 and others - do we prefer to limit commands that makes sense on "islands" or "offline-players" to online-players only?

It seems the wrong approach to me, compared to showing the end-user what is actually the right "set of data".

**Comment by rocky143** [comment] 2015-01-21 08:59
@rlf I had another question not relating to this topic and I didn't feed the need of creating another report about it. Is uSkyblock in anyway preventing non-hostile mobs from dying if they are in lava?
I am trying to figure this out and I don't seem to have any plugin that does that and in uSkyblock config.yml, I did not see a setting so I wanted to ask and make sure.

**Comment by rlf** [comment] 2015-01-21 09:14
Yes, it might. We have some inbuild grief-prevention - see the bottom of the config.yml.
It's intented to only protect "visitors" - from being lured into lava by rogue islanders - but there might be a bug reg. non-hostile creatures as well - though, that might be intentional - avoiding "griefers" pushing livestock into lava.

**Comment by rlf** [comment] 2015-01-21 09:16
Just checked the code - it shouldn't cancel mobs dying in lava, only players that are visiting.

**Comment by rocky143** [comment] 2015-01-21 09:18
Emm, if I wanted to disable the option for visitors, which one would it be that wont protect them from dying in lava so I can test this?

**Comment by rocky143** [comment] 2015-01-21 09:30
I just checked, this is happening to items as well and I am testing all in on my own island as op.

**Comment by dutchy1001** [comment] 2015-01-21 09:35
As far as I can remember /is warp has always been for online and offline players. Some servers allow to have "player" shops and they could be accessed then even when the shop owner isn't online. If players dont want others on their island they should turn /is warp off at their GUI, this why that option is there. With the current protection options I think that if the /is warp is left on the griefing is kept to a minimum.

**Comment by rlf** [comment] 2015-01-21 09:44
`/usb reload` should work, yes, but I usually keep `/plugman reload uSkyBlock` close, just to be sure.

And *blush* there isn't a specific option for the lava-damage, that is grouped by the enabling of pvp.

So, if you want to enable lava damage, enable pvp (https://github.com/rlf/uSkyBlock/blob/master/src/main/resources/config.yml#L62)

**Comment by rocky143** [comment] 2015-01-21 11:42
Enabling pvp is gonna make it so players will be pvping in the island(add the allow flag to worldguard)?
How is lava relating to pvp, non-hostile mobs not dying in lava and entities are not burning in it?

**Comment by rlf** [comment] 2015-01-21 12:30
It isn't - but since you wanted to "disable the lava-protection of visitors", I told you the only (current) way to do that.
And that is by setting allowPvP to allow in the config.yml.
I recognize, this should be added as a separate config-parameter, but currently it's not.
But - that said - I doubt that protection is the cause of the missing burning of entities/mobs.

**Comment by rlf** [comment] 2015-01-21 19:53
The original issue detailed here, is about whether to include or not include offline players in tab completion of warps.

Any comments?

**Comment by dutchy1001** [comment] 2015-01-21 21:33
As my previous comment sums it all I'm against not including offline players in tab completion of warps as it's upto the player him/herself to turn on or off the warp function.

**Comment by rlf** [comment] 2015-01-21 22:31
Closing this issue then

**Closed by rlf** 2015-01-21 22:31 UTC
Labels: invalid, wontfix
