### ISSUE TITLE
Problem with challenge rewards. 

### ISSUE THREAD

**Issue by archmohaa** [rlf/uSkyBlock#364] opened 2015-05-06 10:50 UTC
Heya, we are having problems a lot of the time with reward quantities being given from challenges to the players. If they are supposed to get 4 sand for eg it will sometimes change and give everyone 1.

Basically the problem is here:

https://github.com/rlf/uSkyBlock/blob/master/src/main/java/us/talabrek/ultimateskyblock/challenge/ChallengeLogic.java#L354

In the array returned by getItemReward being given to the player each item stack needs to be cloned first before it is given out and it should fix the problem.

**Comment by dutchy1001** [comment] 2015-05-06 12:45
Duplicate of issue #362 which is with a fix. 
As this version is not official released (due to some other issue's we like to be fixed first) to bukkit or spigot you can still get this from the github downloads

**Closed by dutchy1001** 2015-05-06 12:45 UTC
Labels: duplicate
