### ISSUE TITLE
Island level not updating

### ISSUE THREAD

**Issue by c0wg0d** [rlf/uSkyBlock#349] opened 2015-04-13 06:05 UTC
My players are reporting that their island levels are not increasing, despite adding stacks upon stacks of building materials.  Could this be an issue with an old levelConfig.yml file?  It is linked below:

http://pastebin.com/wWRJSFqr

**Comment by rlf** [comment] 2015-04-13 06:35
The island level is not updated until the owner of the island executes `/is info` (or perhaps `/is level`).

Unless you have setup the auto-refresh of top-ten.

**Comment by c0wg0d** [comment] 2015-04-13 06:36
We don't have the auto-refresh enabled, but they are typing /is level to see the island level and it never changes.

**Comment by dutchy1001** [comment] 2015-04-13 06:49
but if they type /info first they will see what blocks are on the island which then register the level. then when they do /is level it should show the right level.

This is fixed in an update we're working on.

**Comment by rlf** [comment] 2015-04-14 18:12
It's a regression-bug introduced by a "split" in info and level commands earlier (for permission support).

Should be fixed.

**Comment by rlf** [comment] 2015-04-14 23:22
This works for me.
Could you please clarify how it doesn't work?
And preferably the versions in use (hint: use `/usb version`)

**Comment by c0wg0d** [comment] 2015-04-14 23:30
As dutchy said, if players do /is info first, then /is level will show the correct level.  It would be nice if /is level would do the calculation for the island level without needing to do /is info first, or just combining the output from both of these into one command would be better in my opinion.

**Comment by rlf** [comment] 2015-04-15 09:37
Well, we just split them, that is why we had a bug in there :) So "putting them into one command" is not going to happen.

But, that said, the `/is level` command SHOULD update the level (when done by a member of the island, and not too often).

**Comment by c0wg0d** [comment] 2015-04-15 17:28
If /is level does recalculate the level, then we're good.

**Comment by dutchy1001** [comment] 2015-04-15 17:31
I will test this later tonight again, but first a family movie lol

**Comment by dutchy1001** [comment] 2015-04-15 23:14
The command /is level updates the level when executed.
Tested in v2.3-HF2f

**Closed by dutchy1001** 2015-04-15 23:14 UTC
Labels: misconfiguration/old version
