### ISSUE TITLE
Losing Islands on Name Change

### ISSUE THREAD

**Issue by Callatic** [rlf/uSkyBlock#699] opened 2016-03-21 21:42 UTC
I have recently noticed, I have the latest WorldEdit and WorldGuard, Multiverse-NetherPortals. I also have the latest of uSkyblock. But when players seem to be changing there name, they are losing there islands. They keep everything else except there islands. I am wanting this bug to be fixed very quickly.

**Comment by rlf** [comment] 2016-03-22 09:47
Please provide the output from `/usb version`

Related to #314 #344 #540 #231 and most recently (possibly) #689

**Comment by Callatic** [comment] 2016-03-22 11:22
[https://i.gyazo.com/d1de0e13afa23446991191e1c8319f42.png](url)

This is the output.

**Comment by rlf** [comment] 2016-03-22 11:51
![](https://i.gyazo.com/d1de0e13afa23446991191e1c8319f42.png)

**Comment by Callatic** [comment] 2016-03-22 14:25
Yes. That is what it was.

**Comment by BlackBeltPanda** [comment] 2016-03-22 23:49
This happens with me, as well. I've been manually re-registering players to their islands after they change their names.

Version info: http://pastebin.com/raw/WWiXQQBj

**Comment by i9hdkill** [comment] 2016-03-23 02:54
Yep, for me aswell.
`[03:56:10 INFO]: Name: uSkyBlock
[03:56:10 INFO]: Version: 2.6.4
[03:56:10 INFO]: Description: Ultimate SkyBlock v2.6.4-bc02bd-403
[03:56:10 INFO]: Language: de (de)
[03:56:10 INFO]: ------------------------------
[03:56:10 INFO]: Server: CraftBukkit git-Spigot-db6de12-3f3c65f (MC: 1.8.8)
[03:56:10 INFO]: ------------------------------
[03:56:10 INFO]: Vault 1.5.6-b49 (ENABLED)
[03:56:10 INFO]: WorldEdit 6.1.1-SNAPSHOT;3399-b19cd9be (ENABLED)
[03:56:10 INFO]: WorldGuard 6.1.1-SNAPSHOT.1628-e28b236 (ENABLED)
[03:56:10 INFO]: AsyncWorldEdit 3.3.0 (ENABLED)
[03:56:10 INFO]: Multiverse-Core 2.5-b711 (ENABLED)
[03:56:10 INFO]: ------------------------------
`

**Comment by Callatic** [comment] 2016-03-23 11:55
Same i9.

**Comment by i9hdkill** [comment] 2016-03-23 13:38
What was the downside of naming the playerfiles after the uuid and keep the name in the file?
Player joins--> usky player uuid file is loaded--> If playername differs, playername will be updated in the file and in the wgregion that is linked with this file.
To test this simply change the displayname in the uuid file and rejoin, name should be now updating. 
But this sounds too easy for me right now

**Comment by rlf** [comment] 2016-03-24 18:26
The problem has been around for a while - and we will need to change to a UUID based datamodel.
The previous attempts has had some serious issues - but there is no doubt we still need to make the move.

The problem is not the player-files, it's the relations within the island files.
Currently the datamodel uses the playername, both for members, bans, trustees, kicks etc.
Even for the WG-regions.

But there is no doubt we will move to a purely UUID based datamodel - we were just hoping to "make do" with the name-changing-logic until we introduced support for MySQL/SQLite based data-store instead of yml files.

**Comment by Callatic** [comment] 2016-03-24 20:28
When is it going to get fixed?

**Comment by Callatic** [comment] 2016-04-03 12:35
When will this be fixed?

**Comment by rlf** [comment] 2016-04-03 13:13
No one knows for sure, but I guarantee you, it won't be fixed until someone fixes it.

**Comment by Callatic** [comment] 2016-04-03 13:17
Who codes the plugin? Whoever codes the plugin will fix it?

**Comment by rlf** [comment] 2016-04-04 09:14
I do, when I find the time. And I encourage others to fix stuff as well, and post a pull-request.

I currently have very limited time, so the last many weeks has been inactive with reg. to development for me.

**Comment by rlf** [comment] 2016-04-04 09:15
And... fixing the UUID issues we have, has been high on the priority list for a while. So, if you're lucky, it will happen in 2016! :D

**Comment by aycgit** [comment] 2016-07-20 12:39
To keep it clean i think this one can we closed because it was fixed in 2.7.1

**Comment by dutchy1001** [comment] 2016-07-20 13:30
This is still ongoing, as the release is just a few days old we have to give sever owners the chance to report if there errors occur.

**Comment by i9hdkill** [comment] 2016-07-20 14:10
Getting errors on /is top if old cracked players are in the players/errors folder
http://pastebin.com/zBg6F4f5

A question:
The name Astracoupe does not exist as a premium user, but an island exist under his name.
If the old player decides to play again after 3 years(100% unlikely, but I am curious) and registers the name Astracoupe, does he get his island back, even when his player.yml is in the players/errors folder?
If not, I would delete them to stop usky spamming these errors.

**Comment by dutchy1001** [comment] 2016-07-20 14:51
Errors should go into the `error` folder and are mostly caused by very old names that do not exist anymore or files that were create when players misspelled while doing a /is command (E.G `/is warp dutchy0110` instead of `dutchy1001`). These names causing the errors because they are not registered with a proper UUID's.

The chance player X gets the same UUID from his/her "offline" account is 110% not possible and therefore not be able to get his/her old island back (only possible to re-register the new name with commands).

**Comment by dutchy1001** [comment] 2016-12-16 21:43
This should now be in the past after adding a new UUID system.
Any more issue's reopen or create a new issue post.

**Closed by dutchy1001** 2016-12-16 21:43 UTC
Labels: A bug, C UUID, T ready for test
