### ISSUE TITLE
 can't load on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by xkxksk1234** [rlf/uSkyBlock#839] opened 2016-07-27 06:43 UTC
`(I'am not good english...sorry)`

_Please paste the output from `/usb version` below_
```
§7Name: §buSkyBlock
§7Version: §b2.7.2
§7Description: §bUltimate SkyBlock v2.7.2-45f756-430
§7Language: §bkorean (korean)
§9  State: d=200, r=75, i=551, p=724, n=false, awe=false
§7Server: §eCraftBukkit git-Spigot-e000104-4cb3258 (MC: 1.9.2)
§9  State: online=true, bungee=false
§7------------------------------
§7§dVault §f1.5.6-b49 §7(N/A§7)
§7§dWorldEdit §f6.1.3;7a097ca §7(N/A§7)
§7§dWorldGuard §f6.1.2;e38d98d §7(N/A§7)
§7§dMultiverse-Core §f2.5-b716 §7(N/A§7)
§7------------------------------

(on windows 10 status)
(can't check on Ubuntu uSkyblock status but, same plugin)

```

_What steps will reproduce the problem?_
i can't understand this.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: http://pastebin.com/XrjPXqTz

_Server Status:_
```
OS: Ubuntu 14.04 LTS
Ram: 2GB
uSkyblock Version: v2.7.2 (http://dev.bukkit.org/bukkit-plugins/uskyblock/files/38-uskyblock-v2-7-2/)
Minecraft Version: CraftBukkit version git-Spigot-e000104-4cb3258 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)
```
I'm using 2.7.1 but this version is an error(https://github.com/rlf/uSkyBlock/issues/836).
I really like this plugin. :D

**Video**
```
https://youtu.be/sv1CwZvlZyI
```

**Comment by dutchy1001** [comment] 2016-07-27 08:22
I don't understand why your having this issue, I run my server on Ubuntu 14.04 LTS too.

Can you try a very basic server setup:
- Spigot (prefarable v1.10)
- [Pex](http://dev.bukkit.org/bukkit-plugins/permissionsex/files/48-permissions-ex-v1-23-4/)
- [Essentials](http://ci.drtshock.net/job/essentialsx/)
- [EssentialsSpawn](http://ci.drtshock.net/job/essentialsx/)
- [uSkyblock](http://dev.bukkit.org/bukkit-plugins/uskyblock/files/38-uskyblock-v2-7-2/)
- [Vault](http://dev.bukkit.org/bukkit-plugins/vault/files/52-vault-1-5-6/)
- [WorldEdit](http://builds.enginehub.org/job/worldedit?branch=master)
- [WorldGuard](http://builds.enginehub.org/job/worldguard?branch=master)
- [Multiverse-Core](https://ci.onarandombox.com/view/Multiverse/)
- [Multiverse-Portals](https://ci.onarandombox.com/view/Multiverse/) 
- [Multiverse-NetherPortals](https://ci.onarandombox.com/view/Multiverse/)

These are the minimal plugins needed to run uSkyblock (which I run myself too).

When posting the errors in the log plz post the FULL log next time, not just the error.

With the settings you have changed in the config you will not be able to make use of the Nether feature as `distance` and `protectionRange` both needs to be able to be devided by 32, but this is not the cause of your issue

**Comment by xkxksk1234** [comment] 2016-07-29 04:36
It work!
http://imgur.com/a/XST9X
Thank you **dutchy**

**Comment by dutchy1001** [comment] 2016-07-29 08:33
glad it works, closing this issue now.

**Closed by dutchy1001** 2016-07-29 08:33 UTC
