### ISSUE TITLE
Issue with Custom Schematics.

### ISSUE THREAD

**Issue by trulywitty** [rlf/uSkyBlock#198] opened 2015-01-28 04:14 UTC
Well the main issue I have is that I created a schematic ingame right. Selected it from corner to corner.
I then copied it from one block above and saved it with world edit.

The problem lies here. When my island is created with ./is create it will spawn the player in the void. and then when you true to /is restart it generates a error. I'll link it here. I am running Spigot 1.8 version 27 and have all the required files for the uskyblock. http://pastebin.com/4mt4d5wN Any reason my?
Or do I need bedrock near my chest? I currently have it at the bottom of my island. Image showed here
http://gyazo.com/ce2908cce862d2e1f93cc5e4c75fb9b0 and same with my other three Schematics.

Im going to try to add bedrock to them now.

**Comment by dutchy1001** [comment] 2015-01-28 10:16
Have you followed the guide on bukkit-pages? (http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/extras/) or the wiki here (little book on the rightside)

**Comment by rlf** [comment] 2015-01-28 11:13
The chest needs to be within 15 blocks of the bedroc - that is the "scanning radius" used by the plugin.

**Comment by rlf** [comment] 2015-01-29 11:40
Please report back on this issue @trulywitty so, we can close it (or fix it).

**Comment by trulywitty** [comment] 2015-01-29 19:40
Ok so I got the schematics to Work besid're schematic per group. I am using groupmanaget and I have. My group SkyHero inherit from default and have my schematic Tirga and the perm I gave it was usb.schematic.Tirga also the default group have a custom schematic called Jungle.

So Here is my delema. When SkyHero creates a island it creates the Jungle island but it is all messed up. It has the island itself and fills chunks with random parts of the Jungle island. Any idea why this is? Skyhero Inheritiby Jungle Schematic?

**Comment by dutchy1001** [comment] 2015-01-29 19:55
The default group you give them the permission "- usb.schematic.jungle"
The group SkyHero you give 2 permissions
1) - -usb.schematic.jungle (to cancel this for the group)
2) - usb.schematic.tirga

with special attention to the "- -" in the first permission to cancel it.

Also make sure you followed the guideline (as mentioned above) for making a schematic refering to the bedrock and chest distance.

Pls let us know asap if this fixed your problem.

**Comment by trulywitty** [comment] 2015-01-29 22:35
Ok thanks Dutchy But My islands end up looking the same even with cancelling out the perms 
What Happens:
Picture: http://gyazo.com/c5a2336f38779db2251872cdcdd6ba93

Pastebin of Groups: http://pastebin.com/MXc9CxJH
Uskyblock Config: http://pastebin.com/X9p7SH7E
And picture of schematics: http://gyazo.com/ee4d9ff2b7545306e3126a0c6f832374
Anything that is needed please let me know.

**Comment by rlf** [comment] 2015-01-29 22:46
Most likely, the screendump is caused by you not haven been ported away (known client-refresh bug in Spigot).

**Comment by trulywitty** [comment] 2015-01-29 23:06
Are you able to explain this in more depth?

**Comment by rlf** [comment] 2015-01-29 23:11
If you stay in an area, while a plugin (like uSkyBlock) changes blocks, you will get mirrored blocks, and all kinds of crazy shit. This is due to the fact, that in Spigot 1.8, the refreshChunks command is broken (it wasn't in 1.7.10). So, you can either teleport away, and then back (forcing a refresh of your client), or disconnect and reconnect.

If you don't, stuff like your screendump happens.

**Comment by trulywitty** [comment] 2015-01-30 22:45
Ok thanks rlf, Now that I understand It now is not happening to me anymore.

**Comment by dutchy1001** [comment] 2015-01-31 20:45
think this has been explained and sorted.

closing issue.

**Closed by dutchy1001** 2015-01-31 20:45 UTC
Labels: input needed, misconfiguration/old version
