### ISSUE TITLE
Whilst Purging

### ISSUE THREAD

**Issue by DogsPaw** [rlf/uSkyBlock#298] opened 2015-03-03 04:24 UTC
So, I've been having very very very heavy lag spikes to the point of it bringing my Server down. So I went in and changed a few things, updated some plugins and for the finale, did my first purge since my reset. I purge Islands that are 30 days old. While purging, this happened: http://pastebin.com/SjUBsDLr  about 90 minutes AFTER I initiated the purge.

**Comment by wesley27** [comment] 2015-03-03 05:09
It appears as though you're using an older version of Spigot, a couple months old in fact. Try updating to the latest Spigot build, and also try updating to the latest WorldGuard build.

**Comment by DogsPaw** [comment] 2015-03-03 06:48
Ran Build tools and got another Spigot.jar, will run the same command and see what happens.

**Comment by DogsPaw** [comment] 2015-03-03 07:03
So, put in the newer Spigot Jar, Ran the Purge, found 899 candidates, kicked me and another player off, then spat out the same thing: http://pastebin.com/fMSu40K9

Updating WorldGuard as well.

**Comment by DogsPaw** [comment] 2015-03-03 07:13
Alright, I'm running everything up to date as far as I can see,
Vault: 1.5.3
WorldGuard: 1586
uSkyBlock:  v2.3 b3ca9e9

Still got: http://pastebin.com/3G8pWa1y

**Comment by rlf** [comment] 2015-03-03 10:19
Purge has not yet been fixed. So that is "expected" (for now)

**Comment by rlf** [comment] 2015-03-03 10:41
Duplicate of #291 and #243

**Closed** 2015-03-03 10:42 UTC
Labels: duplicate, input needed

**Comment by DogsPaw** [comment] 2015-03-03 22:48
So, this went through the first time in the first Pastebin link, before updating to the latest build, it seems to have messed up some Islands, one player got on, played for a few minutes, got off, got on a few minutes later and most of his island was gone. No errors or anything in the Console, then another player created an Island and it put his Island on top of anothers. Could this be due to the first Purge doing something before crashing? The last 2 'found' all the islands, but crashed before it made changes, the first Purge looked like it marked, and then started deleting.
