### ISSUE TITLE
Challenges Broken

### ISSUE THREAD

**Issue by RickyDeCoite** [rlf/uSkyBlock#727] opened 2016-04-22 03:52 UTC
Name: uSkyBlock
Version: 2.6.7
Description: Ultimate SkyBlock v2.6.7-6cffd6-407
Language: en (en)

Server: CraftBukkit git-Spigot-944aa20-8d16fc0 (MC: 1.9.2)

Vault 1.5.6-b49 (N/A)
WorldEdit 6.1.1-SNAPSHOT;3463-219d2da (N/A)
WorldGuard 6.1.2-SNAPSHOT;1653-65e48d1 (N/A)
Multiverse-Core 2.5-b719 (N/A)
Multiverse-NetherPortals 2.5-b710 (N/A)

Challenges are not in any proper order to be usable. The top row are all Island Level up to SkyLord, but the next tier of challenges require that all of those Challenges be completed.

https://gyazo.com/29128da70b9bc9b1e58b932c294037d6
https://gyazo.com/cb8a0a2e5ef961528467dac8a787deec

All the glowing challenges were completed on an empty stock island.

Not using OP, no permissions other than the default permissions that all users have.

Was a completely clean install with nothing other than the config.yml modified, everything else was untouched.

**Comment by dutchy1001** [comment] 2016-04-22 06:50
Not sure why this is happening but something is wrong with the challenges file.
Delete the challenges.yml and re-download it from [here](http://pastebin.com/V61vAZq3), save it as challenges.yml.

This should fix it.

**Comment by RickyDeCoite** [comment] 2016-04-22 06:53
Since I've deleted the file a few times, should I just redownload the entire plugin? If I do, how do I remove the uSkyBlock version of SkyBlock. Everything I did would not work. To the point of editing the .jar file and removing them from the schematics file. Don't know how to explain it properly.

**Comment by dutchy1001** [comment] 2016-04-22 10:08
First off all don't mess with the .jar file as this will void the support and it isn't needed to do.

I've seen some errors in the "Pastebin" link were the indentation gets messed up. I've edited this 3 times now and re-uploaded it with the right indentation but as soon I save it, it comes back with the error on the page (guess saving as YALM isn't working properly).
I now saved it as ```text``` and the indentation seems to stay as it is. Copy the page (use the download button on top) open it in Notepad++ (most recommended to use) and rename to challenges.yml (you can choose YALM in the dropdown menu on the ```save as type``).
Download the file from [here](http://pastebin.com/qjgqSS3k)

**Comment by RickyDeCoite** [comment] 2016-04-22 10:34
Alright, and for the schematics issue, should I make a new issue post for that? Or is it the same saving issue that challenges are experiencing?

**Comment by dutchy1001** [comment] 2016-04-22 10:50
To disable the islands you need to change the node ```enable: true``` to false in the island section in the config. Adding this node to the next skySMP will do then the same. For any other island you add you can then set ```enable: true``` and ```index: [number]``` , "index" is then the location in the GUI (only dont use 0 zero).

**Comment by rlf** [comment] 2016-04-22 11:46
Sounds like it is broken due to tampering. Closing this one.

**Comment by RickyDeCoite** [comment] 2016-04-22 11:51
Challenges were broken before plugin was touched.

**Comment by dutchy1001** [comment] 2016-04-22 11:59
I have found the same issue with a clean new server, were looking into this

**Comment by rlf** [comment] 2016-04-22 12:57
We've managed to reproduce it, and it seems to only occur on very first installs.
A server-restart or `/usb reload` fixes the issue.

Most likely due to some file-copying being done too late in the process.

**Comment by RickyDeCoite** [comment] 2016-04-22 12:59
I will try again on a non modified plugin using Dutchys way to stopping the uSkyBlock version of SkyBlock from generating.

**Comment by dutchy1001** [comment] 2016-04-22 13:02
What you mean with "NON modified"?? Use an original jar only and use the explanation to disable islands as above.

**Comment by RickyDeCoite** [comment] 2016-04-22 13:03
Thats what I meant.

**Comment by dutchy1001** [comment] 2016-04-22 13:04
Altering the config to your servers needs is not a problem ofcourse.

**Comment by RickyDeCoite** [comment] 2016-04-22 13:10
Yeah, I was unaware of how to disable all schematics other than SkySMP. Setting the default one to false still had me using default layout, didn't realize I had to add a new enable line and set it to true. Only thing I changed in the plugin was the schematics folder to change the default around and not have it files to generate. Won't do that if I can get the original skyblock to load properly. Don't know if you guys want this to remain open until it's fixed for initial start ups. (The original issue)

**Comment by rlf** [comment] 2016-04-22 13:49
Should be fixed in next release (v2.6.8)

**Comment by TheMattVid** [comment] 2016-06-09 06:22
I just did a clean install of uSkyblock with version 2.6.10 and I got this problem. By default, all island level challenges were in the first row. It does not seem to be fixed.

**Comment by SgtLegoTown** [comment] 2016-06-09 06:40
can you provide us first the needed information with usb version please

**Comment by TheMattVid** [comment] 2016-06-09 06:41
USB version 2.6.10-ea06f4-411

**Comment by SgtLegoTown** [comment] 2016-06-09 06:45
the command /usb version please full output

also dependesies

**Comment by SgtLegoTown** [comment] 2016-06-09 06:46
isn't it handier to make new topic of this ?

**Comment by dutchy1001** [comment] 2016-06-09 06:46
Challenges are working fine with v2.6.10. You might miss a depended plugin. post the output of **/usb version** plz

**Comment by TheMattVid** [comment] 2016-06-09 06:48
Name: uSkyblock
Version: 2.6.10
Description: Ultimate SkyBlock v2.6.10-ea06f4-411
Language: en (en)

Server: CraftBukkit git-Spigot-798f32d-0cd0397 (MC: 1.9.4)

Vault 1.5.3-b37 (ENABLED)
WorldEdit 6.1.3-SNAPSHOT;3552-edb4c0b (ENABLED)
WorldGuard 6.1.2-SNAPSHOT;1664-5bd2125 (ENABLED)
Multiverse-Core 2.5.0-SNAPSHOT-b722 (ENABLED)
Multiverse-NetherPortals 2.5.0-SNAPSHOT-b712 (ENABLED)

**Comment by TheMattVid** [comment] 2016-06-09 06:50
I don't see why this has anything to do with dependencies. Challenges work, yes, but the top row is all of the level challenges. That's how it generated. The way the challenges file loads on a fresh install does not make logical sense. It works, but it's out of order.

**Comment by dutchy1001** [comment] 2016-06-09 07:04
I dont know from what version you updated but the challenges have been re-written. This is why all the level challenges are at the top now. There are a new challenges added and some others removed. Each "level" challenge will still open an other row of challenges, that hasn't changed. 

As you already said in the other post "_I haven't updated skyblock for awhile_" things are changing sometimes.

Vault is not up-to-date , v1.5.6 is current (for a long time already)

This topic is solved and I will close this now

**Closed by dutchy1001** 2016-06-09 07:04 UTC
Labels: A bug, T ready for test

**Comment by TheMattVid** [comment] 2016-06-09 07:10
I never at any point said that I had a problem with this being different. I just said that this doesn't make logical sense. It completely breaks the way that unlocking the next row of challenges works.

The "default" rank leeway is 1, meaning that players have to complete all but 1 of the "default" challenges in order to unlock the next row. But since all of the "default" challenges are island level challenges, that means that players must achieve an island level of 500 before they are able to unlock any of the other challenges! Why should players need a level 500 island to do the rest of the challenges? It's broken!

**Comment by TheMattVid** [comment] 2016-06-09 07:14
Ok, I just double-checked and players only need to complete one of the default challenges to unlock farmer challenges. That's my bad.

**Comment by dutchy1001** [comment] 2016-06-09 08:37
A clear fact of shouting before trying I guess.
The way I have set this up is exactly the same as it was, only difference is that the "level" challenges are on the top instead of the end of a challenge row.
I know it forces player to now make their cobble-generator first, but that is the main building requirement an island needs to progress/expand.

Nothing is stopping you to redo the challenges the way you like. If you do, just uncomment the "_merge-ignore:_" in the challenges.yml so it wont be overwritten when updating in the future.

**Comment by TheMattVid** [comment] 2016-06-09 18:42
As I said in my last message, I misread the config file for the challenges and thought that it would require for players to have a level 500 island before they could unlock the next row of challenges. I'm sure you could understand why that would be a cause for concern. But like I said, that was a misreading on my part and now I see that players only need to have a level 10 island before unlocking the next row. My initial complaint had nothing to do with me being "against change" or something like that. I genuinely thought that the default challenges file was setup in a logically bad way. Surely if the default challenges did require having a level 500 island before advancing, you would want me to let you know, right? Nonetheless, this was all my misunderstanding and I am fine with how the default challenges are set up.

**Comment by dutchy1001** [comment] 2016-06-09 19:05
I understood in your last message that it was a mistake of understanding the file on your side, but then deleting the "shout out" message of it being broken did made my message look like I was in the wrong. 

If it was a case that the challenges.yml was wrong/broken, ppl would have complained already as the file is a few months old, but if it was new then yes we would like to be informed of course.

At least it's not broken as you found out, so were all still happy :+1:

**Comment by TheMattVid** [comment] 2016-06-09 19:16
My fault for deleting. I deleted before you sent your response, so I didn't know that you were even making a response at the time. No harm intended.
