### ISSUE TITLE
Could not pass event PlayerQuitEvent to uSkyBlock

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#141] opened 2015-01-10 05:32 UTC
Server version: git-Spigot-081dfa5-ba8f630
uSkyBlock version: 2.0.1-SNAPSHOT-ceade5

Getting a lot of these errors in my logs:
http://pastebin.com/raw.php?i=VvSFaDp4

**Comment by rlf** [comment] 2015-01-18 22:18
Duplicate of #140 - closing this for now

**Closed by rlf** 2015-01-18 22:18 UTC
