### ISSUE TITLE
Could not pass PlayerTeleportEvent

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#692] opened 2016-03-15 05:39 UTC
After a player logged in, the console was spammed with about 28,000 lines of this error: http://pastebin.com/raw/ANNRrKF4

**Comment by dutchy1001** [comment] 2016-03-15 07:47
You only got MV-Core and  MV-NetherPortals, you might need to add MV-portals and see if that helps

**Comment by rlf** [comment] 2016-03-15 13:26
Hmm, we have seen this before.

It seems to be caused by a concurrency bug when loading player-data of someone that needs their inventory cleared.

**Comment by rlf** [comment] 2016-03-23 09:06
The above spamming should be fixed, but...
There might still be issues when clearing inventory for players that were offline (or off-world) when their island was cleared.

**Comment by BlackBeltPanda** [comment] 2016-04-04 09:12
Haven't had any issues with it since the commit. =)

**Comment by rlf** [comment] 2016-04-04 09:13
Thanks, closing for now then.

**Closed by rlf** 2016-04-04 09:13 UTC
Labels: A bug, C performance/concurrency, T ready for test
