### ISSUE TITLE
Lack of Challenge Rewards when Inventory is Full

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#275] opened 2015-02-18 23:08 UTC
As the title states, challenge rewards are missing if there are more reward slots required than slots freed by required items. The fix to this is disallowing challenge completion if one's inventory is too full.

**Comment by dutchy1001** [comment] 2015-02-19 01:39
duplicate of #263 closing this

**Comment by TheMattVid** [comment] 2015-02-19 06:19
My apologies.

**Comment by TheMattVid** [comment] 2015-02-19 06:22
Wait, I just checked #263. The topic there is the handling of more than 8 challenges in a certain difficulty level. My suggestion had to do with receiving rewards from challenges when one's inventories are full. I don't see how the two are related.

**Comment by dutchy1001** [comment] 2015-02-19 10:39
So your saying that when your inventory is full and you complete a challange you wont get all the rewards?

It was late last night and misread the issue

**Comment by TheMattVid** [comment] 2015-02-19 15:49
Yes, that is what I'm saying.

**Comment by dutchy1001** [comment] 2015-02-19 15:52
rlf has added the "feature request" so we now wait till we can test when he implements it.

**Comment by rlf** [comment] 2015-02-20 14:55
Hmm, since the proposed "solution" wouldn't be exactly easy to implement (we need to guess, what the state of the inventory will be, when removing the items). A "half-way-there" solution might be, to simply drop the items at the player location, if the inventory is full?

**Comment by dutchy1001** [comment] 2015-02-20 15:26
The "half-way" solution sound fine to me.
I stick with my first answer, "if a player has it's inventory full he/she should better pay attention then".

**Comment by rlf** [comment] 2015-02-21 12:43
Fixed in v2.2-HF12 (not tested yet)

**Comment by dutchy1001** [comment] 2015-02-24 07:45
when inventory is full items will drop onthe floor now and a message telling you this.

Working in HF12

**Closed by dutchy1001** 2015-02-24 07:45 UTC
Labels: feature request, ready for test
