### ISSUE TITLE
Nether

### ISSUE THREAD

**Issue by Alibabaand40voleur** [rlf/uSkyBlock#793] opened 2016-06-26 22:48 UTC
_Please paste the output from `/usb version` below_
![capture](https://cloud.githubusercontent.com/assets/18491206/16365432/71530cb0-3c00-11e6-81d5-e09617171c6f.PNG)

_What steps will reproduce the problem?_

When u go in the nether portal, we go in nether of the sky, with the lava etc, but we spawn on the top.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

**Comment by rlf** [comment] 2016-06-27 09:09
Duplicate of #86 #452 #560 #389. Closed.

**Closed by rlf** 2016-06-27 09:09 UTC
Labels: S duplicate
