### ISSUE TITLE
Wrong calculation of level when using skulls

### ISSUE THREAD

**Issue by ghacproductions** [rlf/uSkyBlock#841] opened 2016-07-30 14:39 UTC
_Please paste the output from `/usb version` below_
Version: 2.7.1
Description: Ultimate SkyBlock v2.7.1-47aaa9-425
Language: de (de)
State: d=110, r=50, i=18.374, p=34.679, n=false, awe=false
Server: CraftBukkit git-Spigot-078e2f8-f5d891f (MC: 1.10.2)
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.3-SNAPSHOT;3558-5a42a8d (ENABLED)
WorldGuard 6.1.3-SNAPSHOT;1670-4ab38e5 (ENABLED)
Multiverse-Core 2.5-b719 (ENABLED)

_What steps will reproduce the problem?_
1. Set skulls on your island, set them in different directions (up, north, east, south, west)
2. Set different values for the different SubTypes (0-4)
3. See how different your island level changes based on the direction the skull is facing.

_What I expected to see:_
Different SubTypes for different skull-types (creeper, skeleton, etc.)

[Screenshot 1](http://puu.sh/qjL3a/8d78992b81.png)
[Screenshot 2](http://puu.sh/qjL8w/4d814287e3.png)

**Comment by dutchy1001** [comment] 2016-07-30 14:54
Can you try this with v2.7.2 again and see if it still happens?

**Comment by dutchy1001** [comment] 2016-07-30 15:10
can you also post (through pastebin) the **levelConfig.yml**.
Whenever I place a skull it only adds 1000 point (=1 level) to my island, no matter what orientation I put it.

**Comment by i9hdkill** [comment] 2016-07-31 01:10
levelConfig:
http://pastebin.com/fdPczD6n

**Comment by ghacproductions** [comment] 2016-07-31 01:47
I guess something is messed up between the blockdata and the block-damage-value, therefor some weird things happen.

**Comment by dutchy1001** [comment] 2016-07-31 09:40
@i9hdkill 
In your levelconfig you don't have the default value's for skulls.
```
  '144/1': 1000  = wither skull = 1 island level
  '144/2': 10000 = zombie skull = 10 island levels
  '144/3': 100000 =steve skull = 100 island levels
```
All other skulls will have a default value of 10

default setting for skulls are:
```
  '144/0': 1000
  '144/1-4': -1
```
Meaning all 5 skulls get the same 1000 points (1 island level point)
(dragon head (144:5) isn't added as we don't have TheEnd world)

**Comment by i9hdkill** [comment] 2016-07-31 12:27
Thanks for the answer. However you missed the point. 2 MIGHT be the zombie skull, but it is also the direction the skull is facing.
Our level config is for testing purposes. Just test our config and place 5 steve heads with different directions and look for the island level.

**Comment by dutchy1001** [comment] 2016-07-31 12:48
The way the levelconfig works is not by direction, but as it's datavalue, so 144/2 will revere to the zombie skull not the direction it's placed.
![2016-07-31_13 43 44](https://cloud.githubusercontent.com/assets/5569980/17276556/0a020184-5725-11e6-8eb9-c1f1c101340a.png)
After each skull placed I did **/is level** and I go up by 1 level (1000 points) each time (19.8 is my default starting level)

**Comment by dutchy1001** [comment] 2016-07-31 13:59
After using your levelConfig it is odd that the points are depending on the direction the skull is placed, this shouldn't happen.
When rlf is back we have to look into this and see what can be done.

**Comment by rlf** [comment] 2016-08-01 08:39
Skulls have changed, and the way we handle block-data-values is not sufficient to handle different types of skulls (since they will all have the same data-values when placed as blocks).

See http://minecraft.gamepedia.com/Mob_head

The data-values of the `ItemStack` doesn't match the data-values of the `Block`.

**Comment by rlf** [comment] 2016-08-01 08:44
In other words, we support giving a score for a skull (facing in any direction), but not the ability to score different skull-types differently.

This should be fixed by setting appropriate values for `blockLimits`.

Any other fix, would require yet another refactoring of the `levelConfig.yml` - which might be in order, but not highly prioritized atm.

**Comment by rlf** [comment] 2016-08-01 10:22
This issue is caused by the above mentioned difference between data-values for blocks (what we use) and itemstacks. The data-values on the blocks (and thus in the levelConfig) is ONLY concerning the block-orientation, not the type.

This will be closed as invalid, since it's not a bug - If you are very keen on getting this feature, create a feature request for additionaly block-states for scoring, i.e. applying some extra scoring mechanism depending on block-state.

**Closed by rlf** 2016-08-01 10:22 UTC
Labels: A bug, S invalid / wontfix

**Comment by i9hdkill** [comment] 2016-08-01 13:04
Alright, thanks for the explanation.
