### ISSUE TITLE
lag spike on placing blocks above the void

### ISSUE THREAD

**Issue by ridalarry** [rlf/uSkyBlock#822] opened 2016-07-11 12:05 UTC
```
11.07 08:00:38 [Server] INFO Name: uSkyBlock 
11.07 08:00:38 [Server] INFO Version: 2.7.2-alpha2 
11.07 08:00:38 [Server] INFO Description: Ultimate SkyBlock v2.7.2-alpha2-dbadfe-428 
11.07 08:00:38 [Server] INFO Language: en (en) 
11.07 08:00:38 [Server] INFO State: d=128, r=64, i=100, p=178, n=true, awe=true 
11.07 08:00:38 [Server] INFO ------------------------------ 
11.07 08:00:38 [Server] INFO Server: Paper git-Paper-813 (MC: 1.10.2)
11.07 08:00:38 [Server] INFO ------------------------------ 
11.07 08:00:38 [Server] INFO Vault 1.5.6-b49 (ENABLED) 
11.07 08:00:38 [Server] INFO WorldEdit 6.1.3-SNAPSHOT;3557-ac1b4f7 (ENABLED) 
11.07 08:00:38 [Server] INFO WorldGuard 6.1.2-SNAPSHOT;1664-5bd2125 (ENABLED) 
11.07 08:00:38 [Server] INFO AsyncWorldEdit 3.3.12 (ENABLED) 
11.07 08:00:38 [Server] INFO Multiverse-Core 2.5.0-SNAPSHOT-b722 (ENABLED) 
11.07 08:00:38 [Server] INFO Multiverse-Portals 2.5.0-SNAPSHOT-b746 (ENABLED) 
11.07 08:00:38 [Server] INFO Multiverse-NetherPortals 2.5.0-SNAPSHOT-b712 (ENABLED)
```

plugins
```
plugins (36): AsyncWorldEditInjector, Skript, PlaceholderAPI, ChatControl, PlugMan, SkQuery, Votifier, ProtocolLib, Multiverse-Core, Reflex, AAC, AsyncWorldEdit, IPWhitelist, PermissionsEx, FeatherBoard, Tab, Multiverse-Portals, Vault, ChatColor, ProtocolSupport, WorldEdit, Essentials, AnimatedNames, HolographicDisplays, CrateReloaded, WorldGuard, AuctionHouse, React, Multiverse-NetherPortals, GAListener, PvPManager, EssentialsSpawn, EnjinMinecraftPlugin, ChestShop, uSkyBlock, CombatActionBar
```

_What steps will reproduce the problem?_
1. placing a block above the void (if there is no block underneath it) it will cause tps and fps drop at random islands in certain areas (not the entire island)

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin 
there is nothing in the logs

**Comment by rlf** [comment] 2016-07-11 13:31
This has been noted elsewhere, and wasn't (last time around), uSkyBlock, but more a client-issue.

Try disabling uSkyBlock, and TP to the problem area, and place blocks to your hearts content, and see if that doesn't cause lag-spikes as well.

There has been some reports, that using Optifine as client will make the lag-spikes less severe.

It might also be caused by chunk-corruption, but that hasn't been confirmed.

**Comment by dutchy1001** [comment] 2016-07-11 14:56
This might be caused by AAC, try disable that and see if the problem still exists.

**Comment by ridalarry** [comment] 2016-07-11 18:55
I have tried to disable AAC, and the issue still exist. I tried SIngle player on the void and the issue doesn't happen. Here is my timings for more detailed issue https://timings.aikar.co/v2/?id=9755cc32583f4fda83f4bff3484b48e4

**Comment by ridalarry** [comment] 2016-07-11 20:13
Is it possible to make flat land in purpose underneath the islands? as thats not supposed to happen, but it seems like the only way to fix it. https://www.spigotmc.org/threads/lag-when-placing-blocks.32960/

**Comment by BlackBeltPanda** [comment] 2016-07-11 21:53
This happens on servers (not sure about single player) due to the lighting update system. When you place/break a block far enough above the void, it lags trying to calculate the lighting updates for every block beneath it that would normally need to be updated.

I don't think flatland would solve the issue since there's still many blocks that need to be updated. You'd rather need a ceiling above the island to prevent the lighting updates but that's obviously not ideal.

**Comment by BlackBeltPanda** [comment] 2016-07-11 22:02
Just did some testing.

- Using Optifine had little or no effect on preventing the lag.
- Flatland had no effect on preventing the lag.
- A ceiling above the island was able to prevent the lag.

Not sure what you could do to prevent it short of a ceiling, which would just block the light.

**Comment by ridalarry** [comment] 2016-07-11 22:32
@BlackBeltPanda if its the light then I think spigot might have an option to fix it I will test it and inform you.

**Comment by ridalarry** [comment] 2016-07-12 02:36
Maybe a fix will be sending packets to the player that there is a ceiling to make it less laggy. Could be with a configurable option and it might have another plugin to depend on if you want this feature.

**Comment by rlf** [comment] 2016-07-12 06:50
I think it has been confirmed, that this is not caused by uSkyBlock, but is rather an issue with Spigot and light-updates.

Closing it here, but feel free to keep the discussion going.

**Closed by rlf** 2016-07-12 06:50 UTC
