### ISSUE TITLE
New Skyblock Generation Issue

### ISSUE THREAD

**Issue by Sterio** [rlf/uSkyBlock#496] opened 2015-10-02 09:14 UTC
So me and my friend are trying to create an island but when ever it says we created an island it sends us to the same island even tho we both made different islands. It claims it by who ever created it last but the other person can still build and break blocks and all of that. We have restarted the plugin configs and the server several times but it still doesn't work. We are using the latest plugin release and the latest Spigot.

**Comment by dutchy1001** [comment] 2015-10-02 09:41
plz do the command "/usb version" and post those details including a full server log through pastebin

**Comment by VizionStudios** [comment] 2015-10-02 19:44
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Version: 2.2.2
02.10 12:42:45 [Server] INFO Name: AsyncWorldEdit (ENABLED)
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Version: 6.1
02.10 12:42:45 [Server] INFO Name: WorldGuard (ENABLED)
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Version: 6.1;no_git_id
02.10 12:42:45 [Server] INFO Name: WorldEdit (ENABLED)
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Version: 1.5.6-b49
02.10 12:42:45 [Server] INFO Name: Vault (ENABLED)
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Server: CraftBukkit git-Spigot-76236cb-c373061 (MC: 1.8.8)
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Language: en (en)
02.10 12:42:45 [Server] INFO Description: Ultimate SkyBlock v2.4.6-31e0d8-dev
02.10 12:42:45 [Server] INFO Version: 2.4.6

**Comment by VizionStudios** [comment] 2015-10-02 19:58
http://pastebin.com/bnwfVWBL

**Comment by rlf** [comment] 2015-10-02 21:43
```
[12:57:36] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
```
Might be the cause.
Could you "pastebin" the relevant island.yml and player.yml files?

**Comment by VizionStudios** [comment] 2015-10-02 22:08
Player YML:
http://pastebin.com/hhTK7TVt
Island YML:
http://pastebin.com/2QpLydQ0

**Comment by rlf** [comment] 2015-10-02 22:21
Ok, not sure how you got to that place, but clearly the data has been fubared.

Please use `/usb island remove <name>` for the one you want to assign to a new island, and then let them do `/is create` again - that way, they should get a new one.

**Comment by VizionStudios** [comment] 2015-10-03 08:03
It's Fix.

**Comment by dutchy1001** [comment] 2015-10-03 08:15
thx for letting us know

**Closed by dutchy1001** 2015-10-03 08:15 UTC
