### ISSUE TITLE
Neighbouring island restart/generation causing islands to be chopped off

### ISSUE THREAD

**Issue by Wugthefk** [rlf/uSkyBlock#126] opened 2015-01-03 09:06 UTC
**Version**: V2.0.1-RC1.47

**Related config**
general:
    spawnSize: 150
island:
    distance: 110
    height: 150
    protectionRange: 105

I know this plugin shouldn't be used on live servers, but I felt this plugin was pretty solid overall except for a few bugs here and there from time, so I did... 
(Well it also helps to discover bugs so why not :sweat_smile: )

1. Lets just say I have an island that has lots of cobblestone, built to its edges.
2. Then, my neighbour who was just starting out... failed by losing his items and decided to reset his own island.
3. My island which had cobblestone flooring built to the limits of the skyblock that contained animals and crops on top of it suddenly dissapeared within my protection region of 105 blocks (around 5 blocks inside my protected area)
4. So my island got sliced away slightly due to the resetting of my neighbour.

Is this due to a configuration problem, or a plugin bug?
Any help would be greatly appreciated :v:

**Comment by Wugthefk** [comment] 2015-01-03 09:13
I'm not sure whether this issue is caused by island restart or newly generation (or both).

A player who had his island chopped off told me it happened today.

The log of the neighbouring island shows me this:
[1/3/15] The island has been created. (today)

So I concluded that this was caused by his neighbour resetting or generating a new island.

I might be wrong, though...

**Comment by rlf** [comment] 2015-01-03 11:42
It happens - and actually, it's a blunder on my part, since I sort of knew this would happen.
We use chunk-regeneration now as reset, but that poses problems, when the distance vs. protectionrange is too small to guarantee each island complete chunks.

**Comment by rlf** [comment] 2015-01-03 12:24
Should be fixed in https://github.com/rlf/uSkyBlock/releases/tag/v2.0.1-RC1.48
Please verify.

**Comment by dutchy1001** [comment] 2015-01-06 10:39
I cant reproduce this anymore. Fixed on my tests

**Comment by rlf** [comment] 2015-01-11 10:51
Seems to have introduced server-crashes when resetting large islands.

**Comment by dutchy1001** [comment] 2015-01-29 12:53
This hasnt happen to me in the last releases and I have done many island restarts or creations

**Closed** 2015-01-29 12:56 UTC
Labels: ready for test
