### ISSUE TITLE
Challenges Bugged Out

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#304] opened 2015-03-05 23:18 UTC
I had completely customized my challenges. I updated my skyblock jar without regenerating the challenges.yml (which is probably what I shouldn't be doing.) It had been successful in the past, but this time, it seems like things have fallen through the cracks. Every time I try to fix the challenges back to how I had them, it will readd the default challenges IN ADDITION to the customized ones I have added. The display image for all of the Ranks is also a dirt block even though the config says otherwise. When the default challenges reappeared, I deleted them and restarted the server. After the restart, there were only default challenges. Not sure what went wrong here, but I am working on redoing the config to see what happens afterward.

**Comment by TheMattVid** [comment] 2015-03-06 02:56
A manual transfer seems to have it fixed, but I will keep this open in case this problem had some sort of underlying bug.

**Comment by woolwind** [comment] 2015-03-06 03:06
In my case it is losing my custom challenges and only putting in the default.   /usb reload isn't loading challenges again so I have t kill the server to fix it.

**Comment by TheMattVid** [comment] 2015-03-06 03:16
Okay, after the manual transfer, players progress in the challenges returned, but it was still a bit off for some players. One player listed challenges that they had never done as being completed. For example, he never even unlocked master challenges, but three were listed as completed, including "skylord" which is one of the original challenges that I kept in the manual ones. Additional information for that particular challenge is that his island level has never at any point reached the level required to complete that challenge.

**Comment by wesley27** [comment] 2015-03-06 03:36
What version of the plugin were you using before? And I'm assuming you updated to the latest?

**Comment by TheMattVid** [comment] 2015-03-06 03:51
Not 100% sure what I had before, but I think it might have been HF 2.2. From there, I upgraded straight to the latest version.

**Comment by dutchy1001** [comment] 2015-03-06 07:47
when the challenges are been overwritten a copy of the old file can be found in the "backup" folder. Copy the custom challenges (and just the challanges) from there and wih a reload it should all go fine.

**Comment by woolwind** [comment] 2015-03-06 10:08
Nope.  It keeps redoing the merge. 
/usb reload either isn't loading or it is merging again.

**Comment by dutchy1001** [comment] 2015-03-06 10:26
When you say it keeps doing the merge, do you copy the whole "old" challenges.yml back?

The reason it keep merging, what I think is the problem, is that you copy the "version" (on the botum of the .yml) to which let the plugin think you still have an old version. The new version should be "version: 7".

Your right about the amount of challenges displayed and we are aware of this, see issue #263

**Comment by rlf** [comment] 2015-03-06 15:22
We've always said that you need to "manually MERGE" your own changes into the config-files.

If you OVERWRITE - you will get the behaviour you seems to be experiencing.

**Comment by rlf** [comment] 2015-03-06 15:23
And btw. yes - a merge means anything you remove from the "default" will be re-merged into the new challenges. Perhaps we should include a "enabled" flag so, you can keep the challenges, but just disable them?

**Comment by rlf** [comment] 2015-03-06 16:12
Sort of duplicate of #305 though, more like an essay than a bug-report.

**Comment by rlf** [comment] 2015-03-06 16:13
In commit 16d9b94 I introduce the ability to mark existing challenges as `disabled` - instead of deleting them, they will just not be read - this way, the merge of config files (including challenges.yml) should work moving forward.

**Comment by rlf** [comment] 2015-03-06 16:24
https://github.com/rlf/uSkyBlock/releases/tag/v2.3-HF1a

**Comment by rlf** [comment] 2015-04-18 06:27
Closing

**Closed by rlf** 2015-04-18 06:27 UTC
Labels: bug, ready for test
