### ISSUE TITLE
RABBITS AND HORSES WONT SPAWN PLEASE HELP!!!!!!!

### ISSUE THREAD

**Issue by yo-mama-ugly-1** [rlf/uSkyBlock#717] opened 2016-04-10 07:06 UTC
Rabbits wont Spawn, horses Wont Spawn.

Can i make it to where admins can build wherever without giving them op?

**Comment by yo-mama-ugly-1** [comment] 2016-04-10 07:11
I figured out how to fix armor stands with sspawn limits.

**Comment by yo-mama-ugly-1** [comment] 2016-04-10 07:14
I also realized that when someone breaks a block in the middle of a large platform it makes their chunk lag hard? Was wondering if it is my server hosting or the plugin?

Because my server doesnt lag on the regular.

**Comment by yo-mama-ugly-1** [comment] 2016-04-10 07:26
http://prntscr.com/aqe5pe

**Comment by yo-mama-ugly-1** [comment] 2016-04-10 07:26
http://prntscr.com/aqe5pe

**Comment by rlf** [comment] 2016-04-10 08:30
Closing this issue, until:
a) The reporter isn't calling my mama ugly
b) The issue isn't posted in all caps (I can't stand yelling)

**Closed by rlf** 2016-04-10 08:30 UTC
