### ISSUE TITLE
Server crash on is restart

### ISSUE THREAD

**Issue by stelioshah** [rlf/uSkyBlock#403] opened 2015-06-21 17:18 UTC
Each time someone restarts his island my server crashes and it creates this crash report '---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/21/15 7:11 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
	at com.google.common.collect.Lists.newArrayList(Lists.java:127)
	at net.minecraft.server.v1_8_R2.Chunk.removeEntities(Chunk.java:806)
	at net.minecraft.server.v1_8_R2.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:357)
	at net.minecraft.server.v1_8_R2.WorldServer.doTick(WorldServer.java:230)
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:716)
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:336)
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:626)
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:534)
	at java.lang.Thread.run(Thread.java:744)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
	at com.google.common.collect.Lists.newArrayList(Lists.java:127)
	at net.minecraft.server.v1_8_R2.Chunk.removeEntities(Chunk.java:806)
	at net.minecraft.server.v1_8_R2.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:357)
	at net.minecraft.server.v1_8_R2.WorldServer.doTick(WorldServer.java:230)

-- Affected level --
Details:
	Level name: skyworld
	All players: 1 total; [EntityPlayer['_1jingo1_'/256, l='skyworld', x=220.50, y=155.10, z=112.50](_1jingo1_ at 220.5,155.1,112.5)]
	Chunk stats: ServerChunkCache: 472 Drop: 30
	Level seed: -6725330579759841081
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: 0.00,127.00,0.00 - World: (0,127,0), Chunk: (at 0,7,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 10988 game time, 10988 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 57414 (now: false), thunder time: 40118 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:716)
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:336)
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:626)
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:534)
	at java.lang.Thread.run(Thread.java:744)

-- System Details --
Details:
	Minecraft Version: 1.8.3
	Operating System: Linux (amd64) version 3.4.36-mc-verygames
	CPU: 24x Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz
	Java Version: 1.7.0_55, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 466854512 bytes (445 MB) / 915353600 bytes (872 MB) up to 5688000512 bytes (5424 MB)
	JVM Flags: 19 total; -Xms256M -Xmx5710M -XX:UseSSE=2 -XX:MaxPermSize=512M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:NewRatio=3 -XX:SurvivorRatio=3 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=8 -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:MaxGCMinorPauseMillis=7 -XX:+ExplicitGCInvokesConcurrent -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60 -XX:+BindGCTaskThreadsToCPUs -Xnoclassgc
	IntCache: cache: 0, tcache: 62, allocated: 0, tallocated: 0
	CraftBukkit Information: 
   Running: CraftBukkit version git-Bukkit-30d751b (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT) false
   Plugins: { TuxTwoLib v1.8.4-b5 Tux2.TuxTwoLib.TuxTwoLib [], GroupManager v2.1.31 (Phoenix) org.anjocaido.groupmanager.GroupManager [AnjoCaido, Gabriel Couto, ElgarL], IronElevators v1.02 [mc1.7.4] me.ScarleTomato.IronElevators.IronElevators [], AsyncWorldEditInjector v2.2.0 org.primesoft.asyncworldedit.injector.InjectorBukkit [SBPrime], NoNameTags v1.0 me.kazzababe.bukkit.NoNameTags [], mcjobs v3.1.8 com.dmgkz.mcjobs.McJobs [RathelmMC], MassiveCore v2.7.5 com.massivecraft.massivecore.MassiveCore [Cayorion], Carz v5.0 me.A5H73Y.Carz.Carz [], Vault v1.5.2-b33 net.milkbowl.vault.Vault [cereal, Sleaker, mung3r], Multiverse-Core v2.4-b527 com.onarandombox.MultiverseCore.MultiverseCore [Rigby, fernferret, lithium3141, main--], RandomTeleport vmaven-version-number com.atomic.rtp.RandomTeleport [], PearlXP v1.4 PearlXP.PearlXP [], PerWorldPlugins v1.2.4 us.Myles.PWP.Plugin [_MylesC, Incomprehendable], RidingConfig v1.2 tk.bukkit.tutorial.Horseprotection [GamerArlindo01], MoreThanFish v1.5 me.mig4ng.MoreThanFish.MoreThanFish [], WhatIsIt v1.3.9 com.flobi.WhatIsIt.WhatIsIt [flobi], DrugMeUp v0.9.4.1 me.giinger.dmu.DrugMeUp [Giinger, hammale], EggCatcher v1.13 me.shansen.EggCatcher.EggCatcher [shansen], ProtocolLib v3.6.3-SNAPSHOT com.comphenix.protocol.ProtocolLibrary [dmulloy2, comphenix], PlayerVaults v3.5.2 com.drtshock.playervaults.PlayerVaults [drtshock, Koalaaaa], LoginSecurity v2.0.10 com.lenis0012.bukkit.ls.LoginSecurity [lenis0012], HolographicDisplays v2.1.10 com.gmail.filoghost.holographicdisplays.HolographicDisplays [], MobArena v0.96.9 com.garbagemule.MobArena.MobArena [garbagemule], mcMMO v1.5.00-b3547 com.gmail.nossr50.mcMMO [nossr50, GJ, NuclearW, bm01, Glitchfinder, TfT_02, t00thpick1, Riking], TimTheEnchanter v3.0 org.kitteh.enchant.Tim [mbaxter], Citizens v2.0.14-SNAPSHOT (build 1195) net.citizensnpcs.Citizens [aPunch, fullwall], MultiInv v3.2.3 uk.co.tggl.pluckerpluck.multiinv.MultiInv [Pluckerpluck, Tux2], GenerousMobs v1.3 com.fuzzoland.GenerousMobs.GenerousMobs [YoFuzzy3], WorldEdit v6.1;no_git_id com.sk89q.worldedit.bukkit.WorldEditPlugin [], NoCheatPlus v3.11.1-RC-sMD5NET-b743 fr.neatmonster.nocheatplus.NoCheatPlus [NeatMonster, asofold, Evenprime], Teleman v1.3.0 de.tgamer1.teleman.Teleman [], MythicDrops v3.1.0-SNAPSHOT-b385-STABLE net.nunnerycode.bukkit.mythicdrops.MythicDropsPlugin [ToppleTheNun, pur3pow3r], SafeFrames v1.04 me.japu_d_cret.sf.main [Japu_D_Cret], Builder v0.9.1 net.jrbudda.builder.Builder [jrbudda], TheWalls v2.0.1 net.cubecraftgames.walls.Walls [rubik_cube_man], WorldGuard v6.0.0-beta-05.1569- com.sk89q.worldguard.bukkit.WorldGuardPlugin [], HeadDrops v1 com.Chipmunk9998.HeadDrops.HeadDrops [], Hats v1.0 tfw.hats.Main [TiffanyValenti], Pixelator v1.2.1 com.darkblade12.pixelator.Pixelator [DarkBlade12], TouchscreenHolograms v1.3 com.gmail.filoghost.touchscreen.TouchscreenHolograms [], ChestRestock v2.3-b70 com.dumptruckman.chestrestock.ChestRestockPlugin [dumptruckman], Parkour v3.4 me.A5H73Y.Parkour.Parkour [], CraftArrows vRC2.0 net.creepcraft.iPencil.CraftArrows.CraftArrows [iPencil], Cannons v2.2.6 at.pavlov.cannons.Cannons [DerPavlov], Lockette v1.8.17 org.yi.acru.bukkit.Lockette.Lockette [Acru, ElgarL, vk2gpz], ClearLag v2.7.7 me.minebuilders.clearlag.Clearlag [bob7l], GriefPrevention v11.7 me.ryanhamshire.GriefPrevention.GriefPrevention [], InfiniteChests v0.3-PR me.TMAC_Kratos.InfiniteChests.InfiniteChests [TMAC_Kratos], NametagEdit v2.4 ca.wacos.nametagedit.NametagEdit [wacossusca34, sgtcaze, sanjay900], ButtonWarp v2.2.2 com.codisimus.plugins.buttonwarp.ButtonWarp [Codisimus], Essentials vTeamCity com.earth2me.essentials.Essentials [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally], floAuction v3.1.0 com.flobi.floAuction.floAuction [flobi], CommandSigns v1.9.3.2 org.zonedabone.commandsigns.CommandSigns [zonedabone, CJxD, HansAnderson], InSigns v2.1 de.blablubbabc.insigns.InSigns [blabubbabc], uSkyBlock v2.3-HF3 us.talabrek.ultimateskyblock.uSkyBlock [Talabrek, R4zorax and others], SilkSpawners v3.6.6 de.dustplanet.silkspawners.SilkSpawners [xGhOsTkiLLeRx, mushroomhostage], Shopkeepers v1.60 com.nisovin.shopkeepers.ShopkeepersPlugin [nisovin, blablubbabc], SurvivalGames vBeta dev1.9.4b me.maker56.survivalgames.SurvivalGames [maker56, JefroyTJF], MythicMobs v2.0.3 net.elseland.xikage.MythicMobs.MythicMobs [Xikage AKA Ashijin], Movecraft v3.1.X80 net.countercraft.movecraft.Movecraft [BaccaYarro], ChestShop v3.8.7 com.Acrobot.ChestShop.ChestShop [Acrobot], EssentialsChat vTeamCity com.earth2me.essentials.chat.EssentialsChat [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally], Quake v2.4.1 com.Geekpower14.Quake.Quake [Geekpower14], AsyncWorldEdit v2.2.0 org.primesoft.asyncworldedit.AsyncWorldEditMain [SBPrime], EssentialsProtect vTeamCity com.earth2me.essentials.protect.EssentialsProtect [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], EssentialsSpawn vTeamCity com.earth2me.essentials.spawn.EssentialsSpawn [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], Paintball v1.3.3 de.blablubbabc.paintball.Paintball [blablubbabc], EssentialsAntiBuild vTeamCity com.earth2me.essentials.antibuild.EssentialsAntiBuild [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, Iaccidentally], Factions v2.7.5 com.massivecraft.factions.Factions [Cayorion, Brettflan], Sentry v1.8.2 net.aufdemrand.sentry.Sentry [aufdemrand, jrbudda],}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { TIMED_WAITING pool-3-thread-32: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615), java.lang.Thread.run(Thread.java:744)], TIMED_WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], WAITING ProtocolLib-StructureCompiler 0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615), java.lang.Thread.run(Thread.java:744)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)], RUNNABLE Server console handler: [java.io.FileInputStream.readBytes(Native Method), java.io.FileInputStream.read(FileInputStream.java:272), java.io.BufferedInputStream.fill(BufferedInputStream.java:235), java.io.BufferedInputStream.read(BufferedInputStream.java:254), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:248), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:261), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:198), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2145), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLineSimple(ConsoleReader.java:3183), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2333), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2269), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2257), net.minecraft.server.v1_8_R2.DedicatedServer$2.run(DedicatedServer.java:80)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_8_R2.DedicatedServer$1.run(DedicatedServer.java:53)], WAITING Chunk I/O Executor Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615), java.lang.Thread.run(Thread.java:744)], RUNNABLE Netty Epoll Server IO #0: [io.netty.channel.epoll.Native.epollWait(Native Method), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219), io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116), java.lang.Thread.run(Thread.java:744)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151), java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:189)], TIMED_WAITING Timer-0: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], TIMED_WAITING Server Watchdog: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_8_R2.ThreadWatchdog.run(SourceFile:73), java.lang.Thread.run(Thread.java:744)], TIMED_WAITING pool-38-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082), java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:519), java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:682), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615), java.lang.Thread.run(Thread.java:744)], RUNNABLE Signal Dispatcher: [], RUNNABLE Netty Epoll Server IO #2: [io.netty.channel.epoll.Native.epollWait(Native Method), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219), io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116), java.lang.Thread.run(Thread.java:744)], RUNNABLE Thread-4: [java.io.FileOutputStream.writeBytes(Native Method), java.io.FileOutputStream.write(FileOutputStream.java:345), java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82), java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140), java.io.PrintStream.write(PrintStream.java:451), org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:82), java.io.FilterOutputStream.write(FilterOutputStream.java:125), java.io.PrintStream.write(PrintStream.java:480), java.io.FilterOutputStream.write(FilterOutputStream.java:97), org.bukkit.craftbukkit.v1_8_R2.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:44), java.lang.Thread.run(Thread.java:744)], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_8_R2.FileIOThread.c(SourceFile:51), net.minecraft.server.v1_8_R2.FileIOThread.run(SourceFile:30), java.lang.Thread.run(Thread.java:744)], RUNNABLE Netty Epoll Server IO #1: [io.netty.channel.epoll.Native.epollWait(Native Method), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219), io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116), java.lang.Thread.run(Thread.java:744)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Thread.java:1639), org.bukkit.craftbukkit.v1_8_R2.CraftCrashReport.call(CraftCrashReport.java:29), net.minecraft.server.v1_8_R2.CrashReportSystemDetails.a(SourceFile:78), net.minecraft.server.v1_8_R2.CrashReport.h(CrashReport.java:136), net.minecraft.server.v1_8_R2.CrashReport.<init>(CrashReport.java:34), net.minecraft.server.v1_8_R2.CrashReport.a(CrashReport.java:321), net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718), net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:336), net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:626), net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:534), java.lang.Thread.run(Thread.java:744)], TIMED_WAITING EbeanBackgroundThread: [java.lang.Thread.sleep(Native Method), com.avaje.ebeaninternal.server.lib.BackgroundThread$Runner.run(BackgroundThread.java:168), java.lang.Thread.run(Thread.java:744)], WAITING Ebean-jdbcsqlitepluginsCannonsCannonsdb.0: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), com.avaje.ebeaninternal.server.lib.thread.PooledThread.run(PooledThread.java:75), java.lang.Thread.run(Thread.java:744)], TIMED_WAITING MStore ExamineThread: [java.lang.Thread.sleep(Native Method), com.massivecraft.massivecore.store.ExamineThread.run(ExamineThread.java:55)], WAITING Thread-30: [java.lang.Object.wait(Native Method), java.lang.Thread.join(Thread.java:1280), java.lang.Thread.join(Thread.java:1354), com.Acrobot.ChestShop.Updater.Updater.waitForThread(Updater.java:289), com.Acrobot.ChestShop.Updater.Updater.getLatestType(Updater.java:241), com.Acrobot.ChestShop.Updater.Updater.shouldUpdate(Updater.java:508), com.Acrobot.ChestShop.Updater.Updater.versionCheck(Updater.java:466), com.Acrobot.ChestShop.Updater.Updater.access$400(Updater.java:41), com.Acrobot.ChestShop.Updater.Updater$UpdateRunnable.run(Updater.java:586), java.lang.Thread.run(Thread.java:744)], TIMED_WAITING pool-6-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1090), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:807), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615), java.lang.Thread.run(Thread.java:744)], WAITING Java2D Disposer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151), sun.java2d.Disposer.run(Disposer.java:145), java.lang.Thread.run(Thread.java:744)], RUNNABLE DestroyJavaVM: [], TIMED_WAITING Thread-29: [java.lang.Thread.sleep(Native Method), me.maker56.survivalgames.database.sql.DatabaseThread.run(DatabaseThread.java:66)], WAITING pool-34-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615), java.lang.Thread.run(Thread.java:744)], TIMED_WAITING Timer-1: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], RUNNABLE Netty Epoll Server IO #3: [io.netty.channel.epoll.Native.epollWait(Native Method), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219), io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116), java.lang.Thread.run(Thread.java:744)],}
   Recent tasks from 10959-10989{MassiveCore:com.massivecraft.massivecore.util.IdUtil@10829,}
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayer['_1jingo1_'/256, l='skyworld', x=220.50, y=155.10, z=112.50](_1jingo1_ at 220.5,155.1,112.5)]
	Is Modded: Definitely; Server brand changed to 'CraftBukkit'
	Type: Dedicated Server (map_server.txt)'

**Comment by dutchy1001** [comment] 2015-06-21 18:42
Multiverse-Core v2.4-b527 and WG v6.0.0 beta-5 can both be updated to newer versions. I suggest a [dev build](http://builds.enginehub.org/job/worldguard?branch=master) for WG and normal build for [MV-Core](http://dev.bukkit.org/bukkit-plugins/multiverse-core/files/27-2-5-b691-beta/)

Let us know what it does after the update.

**Comment by rlf** [comment] 2015-06-29 09:10
Duplicate of many other errors reg. server crash on is restart.

Should be addressed in the HF6 releases.

**Comment by dutchy1001** [comment] 2015-08-26 19:30
no further input, solved I presume then.

Closed

**Closed by dutchy1001** 2015-08-26 19:31 UTC
Labels: bug, duplicate
