### ISSUE TITLE
When two people make an island at the same time they both get assigned to the same island

### ISSUE THREAD

**Issue by ItsShadowFang** [rlf/uSkyBlock#756] opened 2016-05-28 02:21 UTC
When two people make an island at the same time they both get assigned to the same island, however only one of them owns the island and the other person cannot do anything on it.

Is there any way this can be fixed?

**Comment by SgtLegoTown** [comment] 2016-05-28 05:52
#689 is about the same issue can you paste your /usb v please

**Comment by ItsShadowFang** [comment] 2016-05-28 07:47
Yes that is exactly what is happening
![c579f0e4-2394-11e6-8d7f-d544f93c605b](https://cloud.githubusercontent.com/assets/12955896/15625962/7f564104-24b0-11e6-8a2f-f50368f6b98d.png)

**Comment by SgtLegoTown** [comment] 2016-05-28 09:15
can you update to latest decencies 
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.3-SNAPSHOT;3547-fd0e400 (ENABLED)
WorldGuard 6.1.2-SNAPSHOT;1660-15a9c50 (ENABLED)
Multiverse-Core 2.5.0-SNAPSHOT-b722 (ENABLED)
Multiverse-Portals 2.5.0-SNAPSHOT-b746 (ENABLED)
Multiverse-NetherPortals 2.5.0-SNAPSHOT-b712 (ENABLED)

ill tested with 2.6.9 and above  decencies don't have the problem recreated yet

**Comment by ItsShadowFang** [comment] 2016-05-28 13:38
I upgraded everything to the same as you and now no islands are being created, it's been 5 minutes now and still nothing has been created

**Comment by SgtLegoTown** [comment] 2016-05-28 13:44
are there any errors ? if you use AWE watchdog has a timer that should give a error 

in config 👍 
 watchDog:

    # The maximum time to wait for AWE paste to complete (2m, 3m20s, etc.)
    timeout: 2m

    # The number of ms between each heartbeat
    heartBeatMs: 2000

**Comment by SgtLegoTown** [comment] 2016-05-28 13:57
can you also try with out Awe u are  using 3.3.8 that is not latest version and can give issue's 

and pls test with a server  stop and start because a server reload can give other issue's

**Comment by ItsShadowFang** [comment] 2016-05-28 13:59
I installed the version of world edit you provided and now I get this

```
[08:56:44] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1.3-SNAPSHOT;3547-fd0e400
[08:56:44] [Server thread/ERROR]: Error occurred while enabling WorldEdit v6.1.3-SNAPSHOT;3547-fd0e400 (Is it up to date?)
java.lang.ExceptionInInitializerError
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:100) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-0359393-9cd1111]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot.jar:git-Spigot-0359393-9cd1111]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.IllegalArgumentException: Replacing commands is currently undefined behavior
	at com.sk89q.worldedit.util.command.SimpleDispatcher.registerCommand(SimpleDispatcher.java:64) ~[?:?]
	at com.sk89q.worldedit.util.command.fluent.DispatcherNode.register(DispatcherNode.java:71) ~[?:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.<init>(CommandManager.java:153) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformManager.<init>(PlatformManager.java:86) ~[?:?]
	at com.sk89q.worldedit.WorldEdit.<init>(WorldEdit.java:95) ~[?:?]
	at com.sk89q.worldedit.WorldEdit.<clinit>(WorldEdit.java:91) ~[?:?]
	... 13 more
```

**Comment by SgtLegoTown** [comment] 2016-05-28 14:03
can you give a current usb v please

**Comment by ItsShadowFang** [comment] 2016-05-28 14:04
2.6.9

**Comment by SgtLegoTown** [comment] 2016-05-28 14:05
type in game or in console /usb v and paste it  or screen shot to see if you have to right versions together ..

**Comment by ItsShadowFang** [comment] 2016-05-28 14:09
sorry I realised that after I posted it before, one second. okay got world edit working again, however the problem with the islands going together still persists
![minecraft 1 8 2016-05-28 15 08 21](https://cloud.githubusercontent.com/assets/12955896/15627758/0c7c776c-24e6-11e6-9047-60e885d728f1.png)

**Comment by SgtLegoTown** [comment] 2016-05-28 14:13
I will set up a test with this information and will get back on it I have to make a 1.8.8 server to test

the problem isn't going away when you disable asyncworldedit ?

if you can give that a try I will test some here .. and get back on it  ..

**Comment by ItsShadowFang** [comment] 2016-05-28 14:38
works fine without awe but with awe seems to cause the issue

**Comment by SgtLegoTown** [comment] 2016-05-28 14:57
ty I experience the same result ..

**Comment by rlf** [comment] 2016-05-28 16:15
From `config.yml`:
```
asyncworldedit:
  # Supports disabling the detection of AWE
  enabled: true
```
If set to false, we should use WE directly (without trying to use AWE).

**Comment by ItsShadowFang** [comment] 2016-05-28 22:49
I had set that to false but still the problem was happening

**Comment by dutchy1001** [comment] 2016-05-29 14:49
After reading all back and talking to SgtLegoLand I think AWE is the cause of duplicate players on an island. Due to the delay AWE is causing to avoid server lag the location isn't fully claimed and used twice or more (depending on the amount of players simultaneously create an island) to add players. 

As I was never a fan of AWE I can only suggest to bin this plugin for the USB server, the amount this plugin is needed for uSkyblock is minimal with normal game play and normal islands. 
If WorldEdit is given to players on any other server in the bungeecoord setup then by all means use AWE.

**Comment by rlf** [comment] 2016-06-07 19:39
Seems to be duplicate of #689

**Closed by rlf** 2016-06-07 19:39 UTC
Labels: A bug, S duplicate
