### ISSUE TITLE
Island Owners cannot pick up items/shear sheep etc.

### ISSUE THREAD

**Issue by i9hdkill** [rlf/uSkyBlock#265] opened 2015-02-16 15:57 UTC
Hi,
I converted my 1.0.8 uskyblock files with v2.2-HF9b.
That worked fine for me. Everyone can access their islands and can build.
The island size is also correct. The world Guard 6 regions coordinates are matching the islands.yml files.
So it should be setup correctly.
Anyways, island Owner and Member( member and owner in the islands.yml file) cannot shear sheeps.
That's quite weird. (Even the option visitor can shear sheeps option is active (true). 
World Guard 6 Beta 5 (the version with the old 5.9 use flag)
World edit 6.0.1
Spigot 1.8 build on 10.02.15
Any thoughts on that?

**Comment by rlf** [comment] 2015-02-17 07:53
The `true` meaning of the visitor flag is opposite your assumption.
`true` means yes, protect against visitors doing this - i.e. try to set it to false, and see if that is still an issue.

Our plugin will assume, that WG 6 beta 5 has WG6-compatible flags - meaning, it will make wrong assumptions about the use flag.

My bet would be, that this is caused by WG flags - does it say anything when they try to shear? (screenshot please). If the text starts with some red, and then changes to ... I think it's blue - then it's a WG restriction.

**Comment by i9hdkill** [comment] 2015-02-17 22:45
No World Guard Message.
set it to false did the trick but this can't be the solution, because I don't want that visitors can shear etc.

But with true even members cannot shear sheeps.

**Comment by dutchy1001** [comment] 2015-02-17 22:55
>World Guard 6 Beta 5 (the version with the old 5.9 use flag)

What you mean with this? You either use v6 or v5 and the according flags (which are set automatic in USB). If you got that version from a 3rd party then I suggest to get an official release [here](http://dev.bukkit.org/bukkit-plugins/worldguard/files/45-world-guard-6-0-beta-5/)

**Comment by i9hdkill** [comment] 2015-02-17 23:03
In the initial Release of WG6, sk89 changed the use flag to cover almost everythink (not just doors and levers)
In WG6 Beta 2 he changed the behaviour of the use flag back to the 5.9 version, where the Use flag just covers levers, pressureplates and doors.
So I am using WG 6 Beta 5.
But back to topic, since it's seems not to be a WG issue (No WG Message when shearing sheeps etc.) the use flag doesn't matter.

**Comment by i9hdkill** [comment] 2015-02-17 23:17
World Guard Region:
http://pastebin.com/4WZ5ekU6
Island.yml:
http://pastebin.com/Q7uSfjyd
player.yml:
http://pastebin.com/bKrZj0b4

With shearing set to true, the player Jonnilow can not shear sheeps

**Comment by dutchy1001** [comment] 2015-02-17 23:23
I just tested this again on my server, a vistor cant shear a sheep with the setting to true or false (this needs a fix then). The owner and the player in the party group can still shear a sheep.
Check if there is not an other plugin that can block this.

**Comment by i9hdkill** [comment] 2015-02-17 23:30
Setting fire-damage to true also protects islands members from fire-damage.
And some Island Member have trouble with picking up items when the option is set true.

Seems like a problem with loading the right player configuration on join?

**Comment by rlf** [comment] 2015-02-18 08:04
It sounds like what you are experiencing, is a general malconfiguration or corrupt data.
All those "functions" you list as "not working" - all relies on the ability to deduce whether a player "is on his own island". This is heavily dependent on the WorldGuard region, and the island.yml files.

In other words, take a look at your WG regions, WG version etc.
Perhaps even post the output of `/usb version` here?

**Comment by i9hdkill** [comment] 2015-02-18 15:53
Name: uSkyBlock
[16:51:53 INFO]: Version: 2.2-HF9b
[16:51:53 INFO]: Description: Ultimate SkyBlock v2.2-HF9b-8e30a8-dev
[16:51:53 INFO]: ------------------------------
[16:51:53 INFO]: Server: CraftBukkit git-Spigot-8a983f9-e81edfc (MC: 1.8)
[16:51:53 INFO]: ------------------------------
[16:51:53 INFO]: Name: Vault
[16:51:53 INFO]: Version: 1.5.2-b33
[16:51:53 INFO]: ------------------------------
[16:51:53 INFO]: Name: WorldEdit
[16:51:53 INFO]: Version: 6.0.1;3346-0c4e6e2f
[16:51:53 INFO]: ------------------------------
[16:51:53 INFO]: Name: WorldGuard
[16:51:53 INFO]: Version: 6.0.0-SNAPSHOT.1567-
[16:51:53 INFO]: ------------------------------

island file name (see some posts above) are matching the world guard regions name.
The size of the regions also matching the max islans size.
the island files have the same file names like the world guard regions.

**Comment by dutchy1001** [comment] 2015-03-02 18:02
Is this still an issue or has it been fixed with newer releases??

**Comment by dutchy1001** [comment] 2015-03-04 09:21
closing as no new input has been made.

**Closed by dutchy1001** 2015-03-04 09:21 UTC
Labels: misconfiguration/old version
