### ISSUE TITLE
tps low

### ISSUE THREAD

**Issue by EJupJup** [rlf/uSkyBlock#628] opened 2016-01-20 06:40 UTC
I THINK THIS PLUGIN HAVE PERFORMENCE ISSUE

BECAUSE MY SERVER USED MEMORY 20G ,BUT TPS IS VERY LOW

**Comment by SgtLegoTown** [comment] 2016-01-20 07:24
Caps lock is broke ? I also have 20 GB ram and not a tps drop even have 100+ plugins running on my skyblock. TPS drop is mostly caused by memory or processor time that is taken when it shouldn't or maybe there are 400 players doing a IS restart ? at the same time .. so support this great supporters with more information maybe a timings report. and the plugins U use and some information when the drop take place. they helped me wonderful . so maybe with some information they can do something with they help you 2  .. and very imported try /usb v it magic !!!

**Comment by rlf** [comment] 2016-01-21 16:52
Not a serious bug report.
Closing.

**Closed by rlf** 2016-01-21 16:52 UTC
