### ISSUE TITLE
topten ignoring an island

### ISSUE THREAD

**Issue by woolwind** [rlf/uSkyBlock#129] opened 2015-01-03 23:33 UTC
this island's score should put it at #5, but it isn't on the list.   The topten list is updating because I see islands on the list changing score during the day.

http://pastebin.com/gTPrsq9u

**Comment by woolwind** [comment] 2015-01-04 02:13
so it seems this players rank is not being calculated correctly. he took off some blocks so his 
island level is 294 and it says his rank is 12, but according to current scores on topten list, he should be #7

**Comment by rlf** [comment] 2015-01-04 09:57
Interesting, I will try to see what can be the cause of this.

**Comment by rlf** [comment] 2015-01-04 10:10
Hmm, the code seems sane, and the unit-tests seems fine.
I did, however, find a peculiarity, that might influence the top-ten.
When RC1.52 is ready, please re-test using it.

**Comment by rlf** [comment] 2015-01-19 08:47
Have you seen this issue lately @woolwind ?

**Comment by woolwind** [comment] 2015-01-20 17:09
yes, it still occurs.  Poor yesyes is island level 802 and should be in second place now, but it still ranks him as #12

**Comment by rlf** [comment] 2015-01-20 19:02
Could you please share his island.yml as well as one of those "above" him?

**Comment by rlf** [comment] 2015-01-20 20:26
Should be fixed (please re-test) with RC1.61

**Comment by woolwind** [comment] 2015-01-21 16:31
fixed :)

**Closed** 2015-01-21 16:32 UTC
Labels: awaiting reporter, ready for test
