### ISSUE TITLE
New players island spawned ontop of another?

### ISSUE THREAD

**Issue by Disorbs** [rlf/uSkyBlock#183] opened 2015-01-24 21:22 UTC
So basically we had a new member and he did /is create and it spawned right in the middle
of another island and apparently took over leader of her island as well, he had to transfer
ownership of the island and did /is leave but what if this happens again and this other person
isnt so nice and griefs there island? :o 

example of what i mean, made in paint lol http://i.gyazo.com/dd6208315da2afae9dd68c469a7f7170.png

version 2.0.1 R63

**Comment by rlf** [comment] 2015-01-24 21:28
It sounds like something is truly wrong with your setup Disorbs.

But, I'd like to get to the bottom of these.
Next time something remotely like this happens, please save the following data (before fixing it):
a) Both player-yml files
b) Island (both if available) -yml files
c) Config files from `/plugins/uSkyBlock`
e) WorldGuard regions (`/plugins/WorldGuard/worlds/skyworld/regions.yml`)
f) The server-log-file (or at least an extract).

We cannot reproduce these things here, and with what you describe - it doesn't seem to be caused by two players creating islands at the same time (i.e. no concurrency issue).

**Comment by Disorbs** [comment] 2015-01-24 21:32
honestly i uploaded the files and only changed like oldsialnd: true and that was the only thing
i change besides uploading the worlgguard and edit nothing else and it doesn't seem to do it anymore
i think its only after a cycle around at a point because i made a new account and it worked fine it was just
this one time and all the problems ive had so far wasn't actually uSkyblock till this one

**Comment by rlf** [comment] 2015-01-24 21:38
Hmm, that you use oldIsland: true might be a quite important info.

I will try to reproduce it here.
What about the WG-regions?

**Comment by Disorbs** [comment] 2015-01-24 21:41
didnt change a thing either - http://pastebin.com/UUXRiwvs

**Comment by Disorbs** [comment] 2015-01-24 21:44
as u can see golden is the player that took over the island and now it appears he took over Catkitty
and the one he took over was owlBplayin and now its fine but i guess owl and epic are leaders of their
own island which im guessing is a error

**Comment by rlf** [comment] 2015-01-24 23:03
Ok, can you share the relevant files from islands and players?

**Comment by TheMattVid** [comment] 2015-01-25 00:48
The problem described here is the same as the one I had in my own issue report earlier this week. Although I have not had the problem with the newest version yet, my experience with this plugin over the years has shown that weeks of successful performance of the plugin can go by before the bug happens. Perhaps there is a bug in which an orphaned island will cause an unintentional change in the lastisland file. Another possibility is that perhaps if someone makes their own island, joins another island, leaves, and creates their own island again, it messes with the lastisland file. The only thing I know is that this problem seems to be changing the lastisland file in a way that it shouldn't be changed. The reason why I'm fairly confident that the lastisland file is a cause/result of the problem is because as soon as the problem starts, a bunch of islands in a row will consecutively be overwritten by new players creating islands. If we all keep a close eye on this, we can put a stop to this once and for all.

**Comment by rlf** [comment] 2015-01-25 11:18
Ye, I can put in some additional validation of the last-island-location as well, and, make the "is an island here" detection better.

**Comment by rlf** [comment] 2015-01-26 00:23
Dutchy managed to reproduce this, but ONLY when the island in question (the one being overwritten), didn't have a valid WG-region.

We have decided - based on these findings - to re-introduce the `/usb island protectall` command - it should be working in v2.1.14 - but use it with care (test it, before going guns blazing on live servers).

**Comment by woolwind** [comment] 2015-01-27 20:34
I started getting this - I think it might be the result of running purge but can't swear to it.

I just looked at my last island:
  general:
    lastIslandX: 111
    lastIslandZ: -660

why is it 111 instead of 110?

**Comment by rlf** [comment] 2015-01-27 23:40
Huh, dunno. What happens if you manually edit the lastIslandConfig.yml and restarts the server?

**Comment by rlf** [comment] 2015-01-27 23:41
`/usb island protectall` has been released in v2.2.
Are you still seeing this issue @Disorbs ?

**Comment by rlf** [comment] 2015-01-29 11:41
@Disorbs or @TheMattVid - is this still an issue?

**Comment by TheMattVid** [comment] 2015-01-29 15:58
I have not yet experienced the issue, but 7 days of success does not necessarily correlate with a fixed problem. As I have stated before, in previous versions of the plugin, the problem can happen suddenly after weeks of successful island use. I will continue to monitor this indefinitely and let's all hope this has already been fixed in one of your previous updates.

**Comment by rlf** [comment] 2015-01-29 16:32
In my book, that was a "seems fixed for now" - closing the issue.

**Closed by rlf** 2015-01-29 16:32 UTC
Labels: bug, input needed

**Comment by woolwind** [comment] 2015-01-30 01:24
I have this too - and still have, and think I've finally figured it out.   So for starters, I ran purge  - which I realize was a totally boneheaded move at this stage, but people were getting lonely. I think what happened is after the last orphan island was used, the 'last island' config was set to that address, and it proceeded to loop around the existing islands.  Now this would be fine if it detected island in use correctly and skipped them, but ... not so much. It would paste the schematic on top of whatever was there, issue the island to the new player, set the region - and just to be annoying, add the former owner as a member to the island.   I have reset the last island location to the actual last island, and expect it to behave now.

**Comment by TheMattVid** [comment] 2015-01-30 01:42
I think you are on to something woolwind. You are close on the trail. Your problem was caused with the island purge and mine was not. I do think we have narrowed down the source of the problem due to the lastisland.yml file occasionally changing when orphan islands are unoccupied. Orphan islands are created in two obvious ways: purges, and people with islands joining other islands, leaving theirs unoccupied. Obviously, this doesn't happen every time, because most of the time, orphan island occupation is successful and the problem doesn't happen. If we can pin down what's causing the lastisland.yml to sort of glitch when orphan islands are occupied, perhaps we can finally kill off this bug. My idea is that perhaps it's an issue with handling multiple orphan islands at once.

**Comment by woolwind** [comment] 2015-01-30 02:16
I also had a glitch where last island was off by one in the X - so was getting locations 111, 221, 331, etc
which in addittion to the re-use bug caused 2 island files for the same location since the originals were at 110, 220, as usual. No effing clue how that one happened, but once it did, it behaved consistently.

**Comment by TheMattVid** [comment] 2015-01-30 02:32
That could possibly be due to the fact that the default island size is an even number. As a result, the center point of an island is technically a pair of coordinates involving .5 and .5. Perhaps this is causing confusion in the plugin's processing.

**Comment by rlf** [comment] 2015-01-30 07:28
I think that makes sence Matt.
Either that, or the plugin uses different algorithms spread out in the code, to determine island location (shudder).
The check for "existing island-location" has been improved - so no more overlapping islands should occur  (we use WG to check for overlapping regions) - but the lastIsland cordinate bug needs to be looked into.

**Comment by woolwind** [comment] 2015-03-03 16:48
I had this issue recur. For reasons as yet unknown, my last island configuration got reset to somewhere near the middle and a couple days worth of new islands got messed up before it got reported to me.

The 'does an island exist here' algorithm doesn't know from unprotected islands. I wrote a fix for my server which both checks  worldguard and also scouts around for bedrock in the vicinity. It does the right thing in my test world.  I'll submit a pull request shortly.
