### ISSUE TITLE
Change island-age calculation of purge

### ISSUE THREAD

**Issue by rocky143** [rlf/uSkyBlock#243] opened 2015-02-09 05:54 UTC
How do I preform a purge for lets say Islands that have been inactive for more than 60 days? At the moment, when I used the command "/usb purge 60" in game it says An internal error occurred and on console, I get this error http://pastebin.com/Yd1zTLY9

**Comment by rlf** [comment] 2015-02-09 06:21
What you do is correct - apparently there is a bug in the purge.

**Comment by rlf** [comment] 2015-02-09 06:34
v2.2-HF8

**Comment by rocky143** [comment] 2015-02-09 08:48
Error did seem to go away and it says in game "Marking all islands inactive for more than 60 days" but on the console, these errors appear http://pastebin.com/cpiGijK5 and at the end it would say:
[uSkyBlock] Done scanning - found 0 candidates for purging.
[uSkyBlock] Finished purging marked inactive islands.

**Comment by dutchy1001** [comment] 2015-02-09 10:42
I can confirm that the error in the chat is gone but as rocky143 said the console gives still an error. As rocky143 uses spigot 1.7.XX (as far i can see) I have the error in spigot 1.8.
http://pastebin.com/vYbbWq7V I've done 30 days and 130 days purge both wih no result of "old" islands. 
I also post the whole log as you can see all the other plugin and their version numbers.

**Comment by rlf** [comment] 2015-02-09 12:01
Acknowledged fixed in 7e81688

**Comment by rlf** [comment] 2015-02-09 22:31
Should be fixed in v2.2-HF9 - ready for test

**Comment by rocky143** [comment] 2015-02-10 02:21
Seems to be working now. 
One request from your precious time when you have some to spare.
It would be great to have a command to check the process of the purge or maybe a way to inform the person who runs the purge in a message that when an island is removed.
In the future, an admin command to check the total amount of islands on the server.

**Comment by rlf** [comment] 2015-02-10 06:48
See `/usb async list` and #193 and #192 .
The v2.2-HF9 didn't have a working purge - we found issues during testing - but v2.2-HF9b should have a functioning purge - use with care.

**Comment by Talabrek** [comment] 2015-02-11 01:00
I am currently testing out v2.2-HF9b and tried /usb purge.

I tested it three times. Each time the server lags, eventually times out (crashes), and the purge list is never completely built (so no islands are actually removed). Here is what's going on in the server thread when it finally times out: http://pastebin.com/i4MqqnbR

Looking at these lines:

com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest	com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames
net.minecraft.server.v1_8_R1.UserCache.a		
net.minecraft.server.v1_8_R1.UserCache.getProfile
org.bukkit.craftbukkit.v1_8_R1.CraftServer.getOfflinePlayer(CraftServer.java:1290)
org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:741)	us.talabrek.ultimateskyblock.command.admin.task.PurgeScanTask.offlineSince(PurgeScanTask.java:59)

It appears the problem is with Bukkit's offline player lookup. Perhaps there is a better way to check a player's last played time?

**Comment by rocky143** [comment] 2015-02-11 06:08
I have a great suggestion to fix the lag issue when purging.
Use AsyncWorldEdit(http://www.spigotmc.org/resources/asyncworldedit.327/) support to remove islands! I am sure, that will smooth down the process by a lot!

I am really looking in a way to purge and get rid of lots of in-active users/islands out. I have been facing some really bad system crashes(1-3 times in 24 hours) due to having a great amount of islands I believe or maybe it is because of island calculation, not exactly sure.. I wish I had solid proof of it.
I have been going crazy yelling at the people at the data-center, asking for machine replacement thinking it was Hardware failure but after getting a brand new box in hand, same thing happens. I have somewhere around 55k player data files and over 25k island data files.

**Comment by rlf** [comment] 2015-02-11 08:09
@Talabrek yes, I hope there is, because I've seen the same - and falls short of being able to do anything about the Bukkit performance. We discussed, at one time, to simply check the modification stamp on the island-files.
That might actually be enough.

@rocky143 We already "do what AWE does", that is why everything is "chunked into smaller tasks". Unfortunately, it seems, WE is quite CPU intensive when it comes to clearing regions, so we have even "tweaked" the island-clearing a bit, so it only uses WE on the "borders of the island", and uses normal world-regeneration (with the empty-world-generator) for all the "inner-chunks".

**Comment by rlf** [comment] 2015-02-11 08:19
Actually - when the player was last online might not be the best indication, more like when was any members last on the island...
Which means, we could, enhance the uSkyBlock to keep a timestamp in the island.yml file of "member-activity" - so a purge would be in effect even if the player has been online, but just not played uSkyBlock for the specified period (in effect has abandoned the island).

**Comment by Talabrek** [comment] 2015-02-11 09:28
@rlf Yes, I think storing the last time that any member was active on an island in the island.yml is the way to go.

**Comment by dutchy1001** [comment] 2015-02-11 09:34
it's fine atm for small server as my test with 43 islands worked ok, took few minutes to complete but no crashes or errors in console.
Removing the test tag and wait for new implentions of timestamp added to island.yml

**Comment by rlf** [comment] 2015-02-11 14:23
Ok, I will look into "stamping" the island files on:
* `/is h`
* Player Login while in skyworld

That way, we should have an easier way to obtain the "last-activity" time for an island.

**Comment by woolwind** [comment] 2015-02-11 17:56
I like that using the file modification date lets you manually prevent a specific island from being purged if you feel like it.  Or conversely schedule one for demolition :D

**Comment by woolwind** [comment] 2015-02-12 01:08
what permission does /is purge need now? because apparently usb.* isn't sufficient

**Comment by dutchy1001** [comment] 2015-02-12 07:52
The permission should be for purge "usb.admin.purge" or having OP status

**Comment by rlf** [comment] 2015-03-06 16:25
Using file-time-stamp https://github.com/rlf/uSkyBlock/releases/tag/v2.3-HF1a

**Closed** 2015-10-05 17:06 UTC
Labels: bug, ready for test
