### ISSUE TITLE
obsidian to lava bucket glitch

### ISSUE THREAD

**Issue by wesley27** [rlf/uSkyBlock#858] opened 2016-08-20 19:56 UTC
_Please paste the output from `/usb version` below_

```
Console : [15:52:44 INFO]: Name: uSkyBlock
Console : [15:52:44 INFO]: Version: 2.7.2
Console : [15:52:44 INFO]: Description: Ultimate SkyBlock v2.7.2-45f756-430
Console : [15:52:44 INFO]: Language: en (en)
Console : [15:52:44 INFO]:   State: d=149, r=62, i=18, p=21, n=false, awe=true
Console : [15:52:44 INFO]: Server: CraftBukkit git-Spigot-90f61bc-5e5cf84 (MC: 1.10.2)
Console : [15:52:44 INFO]:   State: online=false, bungee=true
Console : [15:52:44 INFO]: ------------------------------
Console : [15:52:44 INFO]: Vault 1.5.6-b49 (ENABLED)
Console : [15:52:44 INFO]: WorldEdit 6.1.3;7a097ca (ENABLED)
Console : [15:52:44 INFO]: WorldGuard 6.1.2;e38d98d (ENABLED)
Console : [15:52:44 INFO]: AsyncWorldEdit 3.4.1 (ENABLED)
Console : [15:52:44 INFO]: Multiverse-Core 2.5-b717 (ENABLED)
Console : [15:52:44 INFO]: Multiverse-NetherPortals 2.5.0-SNAPSHOT-b712 (ENABLED)
Console : [15:52:44 INFO]: ------------------------------
```

_What steps will reproduce the problem?_ - First glitch
1. have more than one empty bucket in your inventory in different inventory slots
2. right click obsidian to turn it into a lava bucket
3. all empty buckets in your inventory that are in different slots disappear, and you get one lava bucket

_What steps will reproduce the problem?_ - Second glitch
1. have a stack of at least two buckets in your inventory
2. right click obsidian to turn it into a lava bucket
3. your stack of buckets stays the same, and you are given a lava bucket

Both of these are obviously problems as the first is deleting your buckets, and the first one is spawning you a free bucket.

Thanks :)

**Comment by dutchy1001** [comment] 2016-08-20 20:56
Reproduced both **first** glitches

**Comment by wesley27** [comment] 2016-08-20 21:04
Oops, didn't realize I typed first twice, I changed it to second :P

**Comment by dutchy1001** [comment] 2016-08-20 21:12
lol

**Comment by GrimmKitty** [comment] 2016-09-01 04:38
I can take a look at this since I fixed it the first time.

**Comment by BlackBeltPanda** [comment] 2016-12-12 23:10
Any news on this? My players just discovered it and are now duplicating buckets, lol.

**Comment by BlackBeltPanda** [comment] 2017-05-01 19:54
I can't get uSkyBlock to import properly into Eclipse, but a fix for this should be to replace line 107 in PlayerEvents:
` inventory.remove(new ItemStack(Material.BUCKET, 1));`
With this:
```
if (player.getItemInHand().getAmount() > 1) {
	player.getItemInHand().setAmount(player.getItemInHand().getAmount() - 1);
} else {
	player.setItemInHand(null);
}
```

**Comment by BlackBeltPanda** [comment] 2018-07-15 12:35
Tested both glitches; this issue has been fixed. =)

**Closed by BlackBeltPanda** 2018-07-15 12:35 UTC
Labels: A bug, T ready for test
