### ISSUE TITLE
Is Level changed drastically in v2.4

### ISSUE THREAD

**Issue by voigtman** [rlf/uSkyBlock#477] opened 2015-09-22 01:17 UTC
Not sure how this changed with the update - maybe it's just that my understanding is off.
after the update, the island level scores changed pretty drastically - however I have one island that seems to have been unaffected. It's a coop of 5 players and their score is way above anyone else's. upon inspecting their island - there doesn't seem to be anything special about it that would warrant such a high score in comparison to everyone else - unless the score is calculated for each player on the coop. This is where I think the bug might be. Otherwise there seems to be a bias towards coops.

**Comment by i9hdkill** [comment] 2015-09-22 02:15
One big island moved from 5000 points to 29.000! with the update from 2.3 to 2.4.
Some smaller island lost some island levels. 
Think it's because you changed how much some blocks are worth, but why? 29.000 is quite high. The second island has 5000 only^^

**Comment by rlf** [comment] 2015-09-22 05:53
Could you please post the `/is info <leadername>` for those islands?

We tried to normalize the values you get from stone-bricks, but perhaps some error sneaked into the levelConfig.yml.

The is info should tell us what blocks are to blame.

**Comment by voigtman** [comment] 2015-09-22 06:29
hum..... Well,
it's been two days now since  I've installed it and just now that island level seems to have dropped!
https://gyazo.com/6e9c5d701a5e224e3dc8f2437dd93fa9
It was well over 4k just earlier today and yesterday as well.

**Comment by rlf** [comment] 2015-09-22 08:02
Well, the mechanic in uSkyBlock is so, that the island level is only calculated when:
a) The leader executes `/is level`
b) The leader (or a member) executes `/is info`
c) Another person executes `/is info <leadername>`
d) At least one member is online, and the `autoRefreshScore` is active.

In all other cases, the level you see (including on top 10) is simply read from the island-yml file, not recalculated.

**Comment by rlf** [comment] 2015-09-22 08:03
@i9hdkill I'd like to see both your `levelConfig.yml` and the `/is info` from the high-scoring island.
It really sounds like something might have bugged.

**Comment by i9hdkill** [comment] 2015-09-22 10:52
Level Config:
http://pastebin.com/CCc1b8tb
is Info from the "big" island:
http://prntscr.com/8j5i0b

**Comment by rlf** [comment] 2015-09-22 11:39
Yup.
I think the problem is, that GoldBlocks don't have a hard-limit, or a diminishing return.
They probably should.
But that hasn't changed lately? has it?

**Comment by rlf** [comment] 2015-09-22 12:01
A quick-fix for you (though you might get some angry islanders) would be to change your levelConfig.yml

Add this line in the `diminishingReturns` section:
```
  '44/0-7': 10000
  '41': 100
  '49': 50
```
To get gold blocks give diminishing score when 100 blocks has been placed.

**Comment by rlf** [comment] 2015-09-22 12:13
We'll nerf gold-blocks in the next release, to the above values.
Do you have any other blocks that needs nerfing?

**Comment by i9hdkill** [comment] 2015-09-22 13:28
Hm okay, but the island levels changed since the update drastically. espacially the 28k island.

But, i think with 2.3 we used the veeeeery old levelConfig from uskyblock 1.X and since 2.4 there was an auto-config merge or somethink like that...Not sure. However, thx for your solution.

**Comment by dutchy1001** [comment] 2015-09-22 13:36
That would explain a lot.
If that was the case your old levelConfig.yml file should be in the backup folder of uSkyblock. can you post that if you can.

**Comment by i9hdkill** [comment] 2015-09-22 13:43
Oh. yep, you are right. The old gold block was just worth 200 and no disminishing return.(Found the old levelConfig and copared it with the ones in the old Backups from some weeks age)
I think that's the way how we do it again our server. (So we don't get angry skyblockers:D

**Comment by rlf** [comment] 2015-09-22 17:59
But, please note, that you'll need to merge again when-ever you update the plugin. Our levelcinfig always wins :) cause we just simply knows best! ;)

**Comment by voigtman** [comment] 2015-09-22 21:00
Too funny! I think I may compare and adjust as well. Thank you for the tip earlier as well. Hey one thing I noticed and wanted to mention. I logged onto Dutchy's test server and my island had reset - but the /is menu didn't reflect that. It thought I still had an island. FYI. Could just be a version thing. 

--
Jason Houge
http://jasonhougecom

**Comment by rlf** [comment] 2015-09-22 22:07
Dutchys test server is being grossly mis-used, so often player files and island-files get out of sync.

That is sort of the whole purpose with the test server.

**Comment by dutchy1001** [comment] 2015-09-22 22:21
I have to hold me hand up there as a few days ago i made the mistake. (deleted the wrong world instead of updating it). It should be easy fixed with the /is restart command. Would be nice to see if that is fixing this for you. (I even trow in a few dia tools for ya) lol

**Closed** 2015-09-26 19:47 UTC
