### ISSUE TITLE
Islands got reset

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [rlf/uSkyBlock#164] opened 2015-01-20 07:18 UTC
I got this report from a staff member:
"okay, so the owner of the island (mhd4), had his friend part of the island (chrisbuild124). his friend (chris) left the island so he could reset his challenges, and he did this by creating a new island. after he did this, his friend (mhd4) invited him back to his island, and it said to chris you need to type /is create, which he did, and then it reset both their islands. If you look at his island now (chrisbuild124), you'll see it didn't even reset properly, meaning the person who invited him lost his island and somehow the invites got mixed up the wrong way around"

**Comment by rlf** [comment] 2015-01-20 07:57
Sorry, but I need more info/data.
I.e. the story is really good, but could you provide me with the island and player-files affected by the bug?

**Comment by TheOnlyRealTGS** [comment] 2015-01-20 08:28
Okay, I can't find mhd4 in the WG region file, but here's the one for chris:
```    -3080,-1210island:
        min: {x: -3132.0, y: 0.0, z: -1262.0}
        flags: {pvp: deny, greeting: §d** You are entering a protected island area. (chrisbuild124),
            farewell: §d** You are leaving a protected island area. (chrisbuild124),
            entry: allow, entity-item-frame-destroy: deny, entity-painting-destroy: deny}
        max: {x: -3028.0, y: 255.0, z: -1158.0}
        priority: 100
        type: cuboid
        owners:
            players: [chrisbuild124]
        members: {}```

Here's the island file for that island:
http://pastebin.com/tccBDx4S

Here's the player file
http://pastebin.com/AjMy6syQ

And the player file for mhd4
http://pastebin.com/xA6Pcr8F

**Comment by rlf** [comment] 2015-01-20 10:56
So, just to get this straight:
a) mhd4 and chrisbuild124 is on the same island - all is good.
b) chrisbuild124 executes `/is leave`
c) chrisbuild124 executes `/is create`
d) mhd4 executes `/is invite chrisbuild124`
What happens here?
e) chrisbuild124 should have executed `/is accept`, but instead he did `/is create`?
f) Somehow, mhd4s island got reset? and chrisbuild124s got reset in a buggy way?

I'll try to reproduce the error - and get back to you ( @dutchy1001 - if you can reproduce it, please comment on it).

**Comment by TheOnlyRealTGS** [comment] 2015-01-20 12:04
d) I guess it removed chrisbuild124's island (for real) and (technically) removed mhd4's island.
It should reset mhd4's island, because he's accepting an invite I guess.

**Comment by rlf** [comment] 2015-01-20 13:01
Wait, now I got confused, which side is leaving an island, and which side is inviting, and which side is accepting?

**Comment by dutchy1001** [comment] 2015-01-20 13:21
I can reproduce this almost as stated above. 
what I did:
I created an island, put some blocks down and invited "PinkGirly1001". She accepted the invite but did got the message that she accepted but also rejected the invite. (see pic) She was able to open chest and made the cobble gen. 
http://i.imgur.com/hdlSkTa

She then left with the command /is leave and was teleported back to the server spawn. (I presume not using "/island" but "/is" made the help message "usage: /island leave" appear, which is not needed)
http://imgur.com/8WNo4eB

After then she created her own island and got invited to mine again. 
http://imgur.com/bPHTfba
She typed "/is create" (as stated to reproduce this error) and got the right messages what should be happening, see pic
http://imgur.com/RUqs3LV

She then typed the right command, /is accept and got back to my island.
Now comes the problem.

PinkGirly left the island to go back to spawn. She typed /is h to go back to the island and got the message "No Island. Use /is create to get one See pic
http://imgur.com/1esRka4

She created a island with /is create but ended up at my island while "her" island is on a different location. Region is created  by WorldGuard but the actual island isnt there. Her home location is still on my island and I'm no longer "owner" and cant kick Pinky of the island and Pinky cant kick me either.
http://pastebin.com/603nTF7B <--Worldguard region file
http://pastebin.com/FP8EMSBk <-- dutchy island.yml (110,110.yml)
http://pastebin.com/KXBsauC9 <--Pinky island.yml (110,-110.yml)
http://pastebin.com/3cwWJ7Ci <--dutchy player.yml
http://pastebin.com/RtmEs1Yp <--Pinky player.yml

**Comment by TheOnlyRealTGS** [comment] 2015-01-20 13:25
@dutchy1001 @rlf I think the kicking issue could be the one I had in https://github.com/rlf/uSkyBlock/issues/134

**Comment by dutchy1001** [comment] 2015-01-20 13:29
not being able to kick is probably because the "owner" of the island isnt correct

**Comment by rlf** [comment] 2015-01-20 13:49
Sounds like the data-model get's confused - I will look into this issue tonight (I suspect this is also what was causing the issues #140, #141 and #142.

**Comment by dutchy1001** [comment] 2015-01-20 14:03
We wait till tonight the to see if you can sort some

**Comment by rlf** [comment] 2015-01-20 15:42
Actually:

>She typed "/is create" (as stated to reproduce this error) and got the right messages what should be  happening, see pic
> http://imgur.com/RUqs3LV

Shouldn't be happening - I suspect the `/is leave` doesn't correctly "cleanup" the notion of an island, and since it was deleted on `/is accept`, she shouldn't have an island at that time.

**Comment by dutchy1001** [comment] 2015-01-20 16:46
>She typed "/is create" (as stated to reproduce this error) and got the right messages what should be happening, see pic
>http://imgur.com/RUqs3LV
This is correct as far I understand what "should" happen. She's on her own island and I invited her. By mistake she typed /is create, she then got the message "Island found. You already have an island....." which is correct(not sure if this made a change in the configs from either usb or wg). When she typed "/is accept" her island is deleted and she joins my island.

**Comment by rlf** [comment] 2015-01-21 16:35
This should've been fixed with RC1.62, please test it on RC1.63

**Comment by dutchy1001** [comment] 2015-01-21 16:49
tried in many different ways with typing the wrong commands but all is going the way it should.

Fixed for me

**Closed** 2015-01-21 20:10 UTC
Labels: ready for test

**Comment by TheOnlyRealTGS** [comment] 2015-01-21 21:52
Glad that you fixed this, is there any way to reclaim the island?
