### ISSUE TITLE
Random NullPointerException in ChunkSnapShotTask

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#652] opened 2016-01-31 20:37 UTC
Seeing this pop up in my console randomly in v2.6.1: http://pastebin.com/raw/frtAwHz3

**Comment by swan201** [comment] 2016-01-31 20:41
same this issue https://github.com/rlf/uSkyBlock/issues/647

**Comment by BlackBeltPanda** [comment] 2016-01-31 20:43
Ah, I didn't see that report. Since rlf was asking on that one, I have the uSkyBlock nether disabled in my config.

**Comment by rlf** [comment] 2016-02-01 13:33
Ok, marking as duplicate of #647

**Closed by rlf** 2016-02-01 13:33 UTC
