### ISSUE TITLE
Add More Biomes

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#213] opened 2015-01-30 21:32 UTC
If the biomes listed on debocraft are the only ones available, it would be nice to have more. Perhaps add plains if we want players to be able to get horses or extreme hills if we want lower ranks to only be able to gain access to the standard animals.

**Comment by rlf** [comment] 2015-02-09 12:53
Do you want more than PLAINS and EXTREME HILLS?
What biomes exactly will provide different animals?

I'm asking, because we only want to support those that add something to the game.

**Comment by TheMattVid** [comment] 2015-02-09 19:05
Currently, normal animal biomes you have are:
Jungle- Standard animals and ocelots
Forest- Standard animals and wolves
Swampland- Standard animals and slimes
Taiga Standard animals and wolves

Plains would add the option for standard animals and horses.
Extreme Hills would add the option for only standard animals.

In short, yes, plains and extreme hills are the only two that I would like added.

**Comment by rlf** [comment] 2015-02-09 22:05
What about cold biomes? for snow generation?

**Comment by dutchy1001** [comment] 2015-02-09 22:26
I like the idea of the snow biomes, depending on how much work it is to add ofcourse.

**Comment by rlf** [comment] 2015-02-09 22:34
Should be fixed in v2.2-HF9 - ready for test

**Comment by Deathinflames** [comment] 2015-02-11 21:49
I just noticed changing biome to Extreme Hills results in Biome: Ocean in F3. Plains appears to be working correctly though.

**Comment by dutchy1001** [comment] 2015-02-11 22:16
I can confirm that Plains is working, ExtremeHills isn't.

**Comment by c0wg0d** [comment] 2015-02-11 22:54
Flower Forest would be nice so we could get the new flowers with bonemeal on grass.  Not sure if that's possible though, since they grow in predetermined patterns.

**Comment by dutchy1001** [comment] 2015-02-11 23:36
@c0wg0d 

Due to the way these flowers spawn it would be a waste to add this biome as it will not add anything to the gameplay.
The Flower biome will only spawn near forest and birch forest biomes, as we are all on islands we will not have these biomes spawn next to us.

**Comment by rlf** [comment] 2015-02-17 17:56
@dutchy1001 What happens with extremehills? nothing?

**Comment by rlf** [comment] 2015-02-17 18:42
Ready for test in v2.2-HF10

**Comment by dutchy1001** [comment] 2015-02-17 22:41
Tested and working on HF10a

**Closed** 2015-02-17 23:09 UTC
Labels: feature request

**Comment by c0wg0d** [comment] 2015-03-13 19:33
Sorry to bring this up again, but will guardians spawn in the ocean biome, or is there a special "ocean monument" biome?  If so, can we get that one added?
