### ISSUE TITLE
Strange issues with islands folder and regions

### ISSUE THREAD

**Issue by hunter688** [rlf/uSkyBlock#557] opened 2015-11-08 19:18 UTC
After period of time plugin starts to delete information about islands. in the folder /islands/ yml files. The period of time isnt the same every time, it is usually something between 10 - 50 mins.
Only thing which remains in the file of an island is "version:1" rest of the data is removed by the plugin.
This deletion proceeds from file to file, the plugin does not delete all at once.

This problem leads to another. Player names are beeing deleted from world guard regions. Only player names, regions themselfs remain untouched. When the plugin deletes player names it simultaneously changes flags of the region. flags: {greeting: §d*\* You are entering §bMike2051's §disland., farewell: §d*\* You are leaving §bMike2051's §disland.} Flags are reseted to default form with a difference that the name of the player is missing (mike2051).

I used usb debug and I have noticed that the plugin is trying to periodically create configurations for nonexisting player called CONSOLE. Could this have some connection to above descibed problems?

I will add more information if you need. Please leave me some advices how can I help you with finding source of this problem.

uSkyblock 2.4.5, spigot 1.8.8

**Comment by rlf** [comment] 2015-11-08 21:02
First off, please provide the full output of `/usb version` - as it contains a lot of useful information for us.

Since you are seing the CONSOLE, I would bet you are using some other plugin to show some data from uSkyBlock? For instance Holographic-Scoreboard?

The plugin should not delete data, but it is only saving files periodically.

**Comment by hunter688** [comment] 2015-11-09 06:52
<pre>
[07:46:00 INFO]: Name: uSkyBlock
[07:46:00 INFO]: Version: 2.4.5
[07:46:00 INFO]: Description: Ultimate SkyBlock v2.4.5-8f47f4-dev
[07:46:00 INFO]: Language: 2 (en)
[07:46:00 INFO]: ------------------------------
[07:46:00 INFO]: Server: CraftBukkit git-Spigot-0359393-9a17f01 (MC: 1.8.8)
[07:46:00 INFO]: ------------------------------
[07:46:00 INFO]: Name: Vault (ENABLED)
[07:46:00 INFO]: Version: 1.5.6-b49
[07:46:00 INFO]: ------------------------------
[07:46:00 INFO]: Name: WorldEdit (ENABLED)
[07:46:00 INFO]: Version: 6.1;no_git_id
[07:46:00 INFO]: ------------------------------
[07:46:00 INFO]: Name: WorldGuard (ENABLED)
[07:46:00 INFO]: Version: 6.1
[07:46:00 INFO]: ------------------------------
[07:46:00 INFO]: Name: AsyncWorldEdit (ENABLED)
[07:46:00 INFO]: Version: 2.2.2
[07:46:00 INFO]: ------------------------------
</pre>
Yes Holographic Scoreboard Im using.

I made bash script to monitor ls -la output of island directory:

sample output (see 130,-260.yml):
(lis mean november)
<pre>
drwxrwxr-x 2 bukkit bukkit   4096  7. lis 22.32 .
drwxrwxr-x 7 bukkit bukkit   4096  6. lis 19.30 ..
-rw-rw-r-- 1 bukkit bukkit 346521  8. lis 00.13 ls.log
-rw-rw-r-- 1 bukkit bukkit    365  8. lis 00.16 0,260.yml
-rw-r--r-- 1 bukkit bukkit    363  8. lis 00.16 0,-260.yml
-rw-rw-r-- 1 bukkit bukkit   1261  8. lis 00.16 130,260.yml
-rw-r--r-- 1 bukkit bukkit    387  8. lis 00.16 130,-260.yml
-rw-rw-r-- 1 bukkit bukkit    412  8. lis 00.16 -130,260.yml
-rw-r--r-- 1 bukkit bukkit    361  8. lis 00.16 -130,-260.yml
-rw-r--r-- 1 bukkit bukkit    367  8. lis 00.16 260,0.yml
-rw-rw-r-- 1 bukkit bukkit    514  8. lis 00.16 -260,0.yml
-rw-r--r-- 1 bukkit bukkit    367  8. lis 00.16 260,130.yml
-rw-r--r-- 1 bukkit bukkit    361  8. lis 00.16 260,-130.yml
-rw-rw-r-- 1 bukkit bukkit    512  8. lis 00.16 -260,130.yml
-rw-rw-r-- 1 bukkit bukkit    514  8. lis 00.16 -260,-130.yml
-rw-r--r-- 1 bukkit bukkit   1097  8. lis 00.16 260,260.yml
-rw-r--r-- 1 bukkit bukkit    383  8. lis 00.15 260,-260.yml
-rw-r--r-- 1 bukkit bukkit    369  8. lis 00.16 -260,-260.yml
celkem 412
drwxrwxr-x 2 bukkit bukkit   4096  7. lis 22.32 .
drwxrwxr-x 7 bukkit bukkit   4096  6. lis 19.30 ..
-rw-rw-r-- 1 bukkit bukkit 347611  8. lis 00.23 ls.log
-rw-rw-r-- 1 bukkit bukkit    365  8. lis 00.26 0,260.yml
-rw-r--r-- 1 bukkit bukkit    363  8. lis 00.26 0,-260.yml
-rw-rw-r-- 1 bukkit bukkit   1261  8. lis 00.26 130,260.yml
-rw-r--r-- 1 bukkit bukkit     11  8. lis 00.26 130,-260.yml
-rw-rw-r-- 1 bukkit bukkit    412  8. lis 00.26 -130,260.yml
-rw-r--r-- 1 bukkit bukkit    361  8. lis 00.26 -130,-260.yml
-rw-r--r-- 1 bukkit bukkit    367  8. lis 00.26 260,0.yml
-rw-rw-r-- 1 bukkit bukkit    514  8. lis 00.26 -260,0.yml
-rw-r--r-- 1 bukkit bukkit    367  8. lis 00.26 260,130.yml
-rw-r--r-- 1 bukkit bukkit    361  8. lis 00.26 260,-130.yml
-rw-rw-r-- 1 bukkit bukkit    512  8. lis 00.26 -260,130.yml
-rw-rw-r-- 1 bukkit bukkit    514  8. lis 00.26 -260,-130.yml
-rw-r--r-- 1 bukkit bukkit   1097  8. lis 00.26 260,260.yml
-rw-r--r-- 1 bukkit bukkit    383  8. lis 00.30 260,-260.yml
-rw-r--r-- 1 bukkit bukkit    369  8. lis 00.26 -260,-260.yml
celkem 416
</pre>

**Comment by csorrows** [comment] 2015-11-09 07:26
Maybe as the file/folder is being accessed from outside of the server, the file is being locked and not able to be updated?

**Comment by hunter688** [comment] 2015-11-09 07:29
File/folder inst accessed outside. Alle files are writable for plugin.

**Comment by rlf** [comment] 2015-11-09 08:31
I've seen some issue with the topten list on my server as well.

This might be the root-cause.

The files aren't "deleted", as much as they are "overwritten" with empty data.

This issue is most likely the same that is causing the issues where members are "taking over" the island from the leader.

Unfortunately, I still haven't been able to systematically reproduce it, but it seems to be connected to players joining/leaving the server - so is most likely caused by the async loading of player-data (and by association, the island-files).

I thought introducing the Guava caches would ensure thread-safety reg. these issues, but apparently not.

**Comment by hunter688** [comment] 2015-11-09 09:05
Files isnt deleted, but modified and contain only one line:

<pre>
version:1
</pre>

**Comment by csorrows** [comment] 2015-11-09 09:38
@hunter688 yes, that is exactly what @rlf just described.

**Comment by hunter688** [comment] 2015-11-09 09:42
I know, I described this in the first post. :-)
<pre>
Only thing which remains in the file of an island is "version:1" rest of the data is removed by the plugin.
This deletion proceeds from file to file, the plugin does not delete all at once.
</pre>

**Comment by rlf** [comment] 2015-11-09 11:59
Could I get you to try out v2.5.4 - It might resolve the issue, and if it doesn't the `/usb debug setlevel FINER` with a subsequent pastebin of the log from `/uSkyBlock/logs` should make us more enlightened.

**Comment by hunter688** [comment] 2015-11-09 12:12
It is safe upgrade from my version to this one?

**Comment by rlf** [comment] 2015-11-09 12:16
Well, I'd say yes - but no upgrade is ever safe... :D
There are (quite some) changes between those two releases.
https://github.com/rlf/uSkyBlock/compare/v2.4.5...v2.5.4

I'd assume you'd want most of them - perhaps not the "island regions become 1 block smaller".
But that is entirely up to you.

**Comment by hunter688** [comment] 2015-11-09 12:22
Im now disabled plugins holographic scoreboard. Looks like yml files in the islands directory untouched now. I will wait some time and report.

After this test I will try to deploy new version.

**Comment by hunter688** [comment] 2015-11-09 15:16
Looks like found source of problem. Thanks for suggestion about Holographic Scoreboard.

Whne disabled plugin, looks like island yml files are modified only when player do /is info or flush cache.

my scoreboard config:
<pre>
boards:
  topten:
    command: is top
    interval: 10m
    sender: console
    delay: 10s
    location:
      world: world
      x: 33.542805143211474
      y: 63.62
      z: -21.552578013993774
</pre>

**Comment by rlf** [comment] 2015-11-11 09:06
I'm still experiencing this issue on my server.
So, the code needs some more work - esp. if both Holographic-Scoreboard and `autoRefreshScore` is in use.

**Comment by dutchy1001** [comment] 2016-12-16 21:27
think were past this issue, closing for now

**Closed by dutchy1001** 2016-12-16 21:27 UTC
Labels: A bug, C performance/concurrency, C UUID
