### ISSUE TITLE
Not gaining Island levels

### ISSUE THREAD

**Issue by supaspork** [rlf/uSkyBlock#517] opened 2015-10-23 00:14 UTC
Over 100 people have been on my 1.7.10 uskyblock server and only 6 people have managed to get any sort of levels. Any help?
Edit: also not getting any block information when typing /is info

Getting this error when issuing command
```
[23:51:35 INFO]: supaspork1 issued server command: /is level
[23:51:35 WARN]: Exception in thread "Craft Scheduler Thread - 7"
[23:51:35 WARN]: org.apache.commons.lang.UnhandledException: Plugin uSkyBlock v2.4 generated an exception while executing task 330
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 16288
        at us.talabrek.ultimateskyblock.island.LevelLogic.addBlockCount(LevelLogic.java:238)
        at us.talabrek.ultimateskyblock.island.LevelLogic.access$100(LevelLogic.java:36)
        at us.talabrek.ultimateskyblock.island.LevelLogic$1.run(LevelLogic.java:180)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by dutchy1001** [comment] 2015-10-23 06:45
can you give us the info when you do the command "/usb version"

**Comment by rlf** [comment] 2015-10-23 07:32
It seems you have an invalid `levelConfig.yml` file, have you changed it? Otherwise it have been corrupted. Please pastebin it, and share it.

**Comment by rlf** [comment] 2015-10-23 07:35
EDIT: Nevermind, it's not the levelConfig, it's your world. uSkyBlock v2.4 doesn't support "extended blocks", but you seem to be running a modded version of Minecraft, that uses block-ids above 255.

That is not supported by v2.4, only later versions support this (but they don't support Bukkit 1.7.10).

**Comment by agonii52** [comment] 2015-10-23 13:50
Is it possible to have the latest release modified to run on a modded 1.7.10 server?
I would like to run skyblock with a few different modpacks aswell.

**Comment by dutchy1001** [comment] 2015-10-23 14:52
we have been working on a release for 1.7.9/10 but t needs some more work to get it ready for release.

**Comment by rlf** [comment] 2015-10-23 17:13
Checkout this link:

**Comment by agonii52** [comment] 2015-10-23 19:00
Thanks, version 2.4.9 is calculating levels properly!! 

I do still receive an error when using /is top, although this is not a major issue.
Info below: (note: I replaced the old jar file with 2.4.9 and deleted the yml files under plugins/uskyblock I can test with a clean install if needed, bout would rather keep the current world/islands.)
![Uploading usbvers.PNG…]()

[18:40:02] [Server thread/INFO]: Agoni issued server command: /is top
[18:40:03] [Craft Scheduler Thread - 7/WARN]: Exception in thread "Craft Scheduler Thread - 7" 
[18:40:03] [Craft Scheduler Thread - 7/WARN]: org.apache.commons.lang.UnhandledException: Plugin uSkyBlock v2.4.9 generated an exception while executing task 77
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: us.talabrek.ultimateskyblock.guava.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key c1fc3ace-e6b2-37ed-a575-03e0d777d7f1.
	at us.talabrek.ultimateskyblock.guava.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2350)
	at us.talabrek.ultimateskyblock.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2320)
	at us.talabrek.ultimateskyblock.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at us.talabrek.ultimateskyblock.guava.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at us.talabrek.ultimateskyblock.guava.cache.LocalCache.get(LocalCache.java:3937)
	at us.talabrek.ultimateskyblock.guava.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at us.talabrek.ultimateskyblock.guava.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at us.talabrek.ultimateskyblock.player.PlayerLogic.getPlayerInfo(PlayerLogic.java:114)
	at us.talabrek.ultimateskyblock.uSkyBlock.getPlayerInfo(uSkyBlock.java:766)
	at us.talabrek.ultimateskyblock.island.IslandLogic.displayTopTen(IslandLogic.java:218)
	at us.talabrek.ultimateskyblock.island.IslandLogic$5.run(IslandLogic.java:249)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

Also, with inventory tweaks allowing ctrl+click and alt+click, i am able to remove the blocks from the /is menu, they do repopulate, but people are able to aquire the blocks used in the menu. I'm not sure if this can be fixed inside the plugin or if the best solution is to leave alt and ctrl disabled in the invtweaks config.

Again thanks for the help!!!

**Comment by dutchy1001** [comment] 2015-10-24 15:27
It would have been so much easier that they would mention they use KCauldron instead of Bukkit/Spigot in the first message. This would have made it so much easier.
I've tried to find a server file for KCauldron so I can setup a server to test but so far I haven't been successful.

**Comment by agonii52** [comment] 2015-10-24 17:43
Sorry Dutchy! 
I know the /usb version is one of the items you request on the wiki, it just slipped my mind when posting the first post.
I downloaded the version i use from http://tcpr.ca/kcauldron 
As stated above I use version 152.
http://tcpr.ca/files/kcauldron/KCauldron-1.7.10-1492.152.zip
If i can do anything to help, let me know.

**Comment by dutchy1001** [comment] 2015-10-24 23:50
the link is not of an official source and even Spigot can be downloaded there which is as far I know an offence. I be careful to use links like that and cant recommend it from a legal point of view.

**Closed** 2015-10-31 23:18 UTC
Labels: misconfiguration/old version
