### ISSUE TITLE
Island Deleting with no WG region error

### ISSUE THREAD

**Issue by mcraftpete** [rlf/uSkyBlock#337] opened 2015-04-06 20:09 UTC
Hi,
A player tried to delete his island , but it hadn't created a WG region to the island on joining the server so when he did islands restart it caused this error...
```
[13:57:15] [Server thread/INFO]: NJO51412 issued server command: /is restart
[13:57:15] [Server thread/WARN]: Trying to delete an island - with no WG region! (skyworld:-5830.00,150.00,-4510.00)
[13:57:15] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin uSkyBlock v2.3-HF1c
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_05]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_05]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
Caused by: java.lang.NullPointerException
	at us.talabrek.ultimateskyblock.handler.WorldEditHandler.getRegion(WorldEditHandler.java:129) ~[?:?]
	at us.talabrek.ultimateskyblock.handler.WorldEditHandler.unloadRegion(WorldEditHandler.java:145) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.postRestart(uSkyBlock.java:543) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.access$500(uSkyBlock.java:93) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock$6.run(uSkyBlock.java:567) ~[?:?]
	at us.talabrek.ultimateskyblock.island.IslandLogic.clearIsland(IslandLogic.java:93) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.restartPlayerIsland(uSkyBlock.java:564) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RestartCommand.doExecute(RestartCommand.java:29) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequireIslandCommand.doExecute(RequireIslandCommand.java:42) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequirePlayerCommand.execute(RequirePlayerCommand.java:33) ~[?:?]
	at us.talabrek.ultimateskyblock.command.common.CompositeUSBCommand.execute(CompositeUSBCommand.java:116) ~[?:?]
	at us.talabrek.ultimateskyblock.command.common.AbstractCommandExecutor.onCommand(AbstractCommandExecutor.java:21) ~[?:?]
	at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCommand.java:64) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	... 14 more
```

**Comment by rlf** [comment] 2015-04-09 11:19
Had the player changed his name before joining the server?

**Comment by mcraftpete** [comment] 2015-04-09 11:33
No hes had the same name , he hasnt been on server since we updated to newer version , but this seems to be mixed , we still have some players coming on and a simply relog updates their wg regions and island info but not always.

**Comment by rlf** [comment] 2015-04-12 10:25
The "updating of the WG region" is done when:
a) A user logins *in the skyworld* 
b) A user accesses his island (i.e. issues the `/is` command).

If the WG region "fix" fails (and it seems that is the cause on occasion for you), there should be a stack-trace in the server-log.

We need that stack-trace to get to the root of this issue.
That is, not the stack-trace above, but the one that should be shown on login/access.

**Comment by rlf** [comment] 2015-04-13 06:37
This issue should contribute to the feature in issue #193 (i.e. some report of the number of islands with and without WG regions).

**Comment by dutchy1001** [comment] 2015-12-14 11:37
No further input.
Closing this.

**Closed by dutchy1001** 2015-12-14 11:37 UTC
