### ISSUE TITLE
Nether Problems

### ISSUE THREAD

**Issue by ZyloV** [rlf/uSkyBlock#389] opened 2015-06-04 03:42 UTC
I have downloaded this plugin and really like it, but I have encountered an issue. I go to the bukkit page and look how to make a nether world, I follow every step and then restart my server (to let the scale take action) but when I spawn back in and go through my portal, it just acts like it is going somewhere and then spawns me on the outside of the portal in the same world. I would love your guys' help, thank you. :)

**Comment by dutchy1001** [comment] 2015-06-04 06:38
This is a multiverse or Spigot/craftbukkit 1.8.6  bug and not uSkyblock. I already have contacted Multiverse but no update from them till now.

**Comment by ZyloV** [comment] 2015-06-04 13:16
Sounsds good, if I could get a notification when it works again that would
be great.

**Comment by dutchy1001** [comment] 2015-06-04 15:43
I was unable to recreate a 1.8.5/4 jar so it's back to 1.8.3.
I'm not sure if this is now related to MV or the 1.8.6 build (both Spigot and Craftbukkit).
With the 1.8.3 server jar the portals are working correct again.

**Comment by ZyloV** [comment] 2015-06-04 16:08
Sounds good, Thank you.

**Comment by woolwind** [comment] 2015-06-04 17:22
I've got functional portals with spigot 1.8.6 using these versions of MV:

09:17:03] [Server thread/INFO]: [Multiverse-Core] Loading Multiverse-Core v2.5-b678
[09:17:04] [Server thread/INFO]: [Multiverse-Portals] Loading Multiverse-Portals v2.4-b548
[09:17:04] [Server thread/INFO]: [Multiverse-NetherPortals] Loading Multiverse-NetherPortals v2.5-bUNKNOWN

the MV-NP version is the one rlf kindly built and posted:

https://github.com/rlf/Multiverse-NetherPortals/releases/tag/2.5-1118bc7

**Comment by dutchy1001** [comment] 2015-06-04 18:42
My orginal setup has these versions:
Multiverse-Core v2.5-b691 (1 build newer)
Multiverse-Portals v2.5-b710 (a lot newer)
Multiverse-NetherPortals v2.5-bUNKNOWN (same)

I reverted all plugins back to the same as you but I keep having the same issue which makes me think that it's caused by spigot/craftbukkit

**Comment by rlf** [comment] 2015-06-04 21:37
I think so to.
It seems, that MV will require locations to contain the World as well, and that Spigot 1.8.6 has changed the Portal event to not have world in all the Locations provided.
Most likely a bug in Spigot, and hopefully one that will be fixed soon.

**Comment by rlf** [comment] 2015-06-06 07:49
Marking it invalid - since it's out of our hands (not a bug on our end).

**Comment by dutchy1001** [comment] 2015-06-07 10:38
After testing the new 1.8.7 spigot it seems the portal bug has been solved.

**Comment by ZyloV** [comment] 2015-06-08 06:02
Oh yay!!! Now all I do is just make the portal orrr?

**Comment by dutchy1001** [comment] 2015-06-08 06:54
Make sure you have the Nether setup right. https://github.com/rlf/uSkyBlock/wiki/Nether-and-uSkyBlock

**Comment by ZyloV** [comment] 2015-06-08 06:57
Thank you very much.

**Comment by ZyloV** [comment] 2015-06-08 18:32
It still spawns me back on the on my island :/

**Comment by dutchy1001** [comment] 2015-06-08 18:41
are you sure you have the last pre-release? You might need to delete the old jar first then re-add the new jar.

**Comment by ZyloV** [comment] 2015-06-08 18:42
Where can I download that?

**Comment by dutchy1001** [comment] 2015-06-08 18:46
sorry I got mixed up with with an other post.
Can you do "usb version" command in console and post those details here? You be able to copy paste then or "/usb version" ingame but you need to retype them

**Comment by ZyloV** [comment] 2015-06-08 18:51
http://pastebin.com/RZaHjTDt

**Comment by dutchy1001** [comment] 2015-06-08 18:56
Your server is still on 1.8.6. You need to recompile the spigot.jar to make it 1.8.7

Also you can update your Worldguard to a dev build 1600 (higher I havent tested yet)
http://builds.enginehub.org/job/worldguard?branch=master

**Comment by ZyloV** [comment] 2015-06-08 18:57
How would I get 1.8.7 if I am using a server host.

**Comment by dutchy1001** [comment] 2015-06-08 19:03
You should be able to choose the jar from the drop down menu in your hosts controle panel. if the file is not yet available contact your host so they can add it for you. (I only doubt that they react as fast our support does)

**Comment by dutchy1001** [comment] 2015-06-08 19:06
alternative you can go back to 1.8.3 till they add the 1.8.7 file

**Comment by ZyloV** [comment] 2015-06-08 19:10
The only option for spigot is to choose the 1.8.7 jar.

**Comment by dutchy1001** [comment] 2015-06-08 19:13
if that is there then yes

**Comment by ZyloV** [comment] 2015-06-08 19:29
I chose the 1.8.7 jar but it still doesn't work.

**Comment by dutchy1001** [comment] 2015-06-08 19:38
were are you changing this?
If you can choose the 1.8.7 spigot.jar from your host, then restart the server it should work.
After a restart do the command "usb version"  then post that here plz

**Comment by ZyloV** [comment] 2015-06-08 19:42
08.06 15:39:42 [Server] INFO ------------------------------
08.06 15:39:42 [Server] INFO Version: 6.0.0-beta-05.1569-
08.06 15:39:42 [Server] INFO Name: WorldGuard
08.06 15:39:42 [Server] INFO ------------------------------
08.06 15:39:42 [Server] INFO Version: 6.1;no_git_id
08.06 15:39:42 [Server] INFO Name: WorldEdit
08.06 15:39:42 [Server] INFO ------------------------------
08.06 15:39:42 [Server] INFO Version: 1.5.3-b37
08.06 15:39:42 [Server] INFO Name: Vault
08.06 15:39:42 [Server] INFO ------------------------------
08.06 15:39:42 [Server] INFO Server: CraftBukkit git-Spigot-6a6b839-b0e81a4
(MC: 1.8.6)
08.06 15:39:42 [Server] INFO ------------------------------

**Comment by ZyloV** [comment] 2015-06-08 19:42
But I have 1.8.7 chosen http://gyazo.com/d1d0f5ddc145fad7efd657b4e6e21def

**Comment by dutchy1001** [comment] 2015-06-08 19:45
looks like your host has made a mistake and have the wrong file attached to it, You should contact them about it.

You can check on our public test server (uskyblock.redirectme.net) that is works.

**Comment by ZyloV** [comment] 2015-06-08 19:54
Thank you.

**Comment by ZyloV** [comment] 2015-06-09 04:20
Alright, I got the 1.8.7 to work but now when I use the portal, it spawns
me above the nether where the bedrock layer is.

**Comment by dutchy1001** [comment] 2015-06-09 06:44
Do you use Multiverse-NetherPortals?
Our dev made a fix for this.
Download this version from [here](https://github.com/rlf/Multiverse-NetherPortals/releases/tag/2.5-1118bc7)

make sure your Nether is setup right with the pagew I mention before

**Comment by ZyloV** [comment] 2015-06-09 06:45
I will try it out as soon as I can, thank you.

**Comment by ZyloV** [comment] 2015-06-09 19:30
Fixed the problem, thank you very much for that :D. This can now be closed.

**Comment by dutchy1001** [comment] 2015-06-09 19:31
YW enjoy the uSkyblock

**Closed** 2015-06-09 19:40 UTC
Labels: invalid / wontfix
