### ISSUE TITLE
Error with /is level

### ISSUE THREAD

**Issue by Aberzhulan** [rlf/uSkyBlock#509] opened 2015-10-12 11:17 UTC
We are using uSkyblock version v2.4.5-8f474f-dev

First issue: When I try to use /is level, I get this error: http://pastebin.com/A8FTUGzd
player.yml: http://pastebin.com/0Bkg6N0k
island.yml: http://pastebin.com/4fWU2LVR

**Comment by rlf** [comment] 2015-10-12 11:26
First of, it seems you are not running an official version of uSkyBlock.

Can you please provide the full output from `/usb version`.
If you change the code, we don't have any chance of helping you - especially if you do not tell us how you changed it.

**Comment by Aberzhulan** [comment] 2015-10-12 11:34
I'm unsure as to how I'm running an unofficial version, since I downloaded it from the SpigotMC page. I don't change code in plugins, since I don't even understand how java works.

Here's a screenshot of the /usb version output:http://imgur.com/m0iwvb3

**Comment by rlf** [comment] 2015-10-12 12:44
In that case, I apologize - I was just not able to locate any source-code that matched that particular version.
Nor explain why the error occurs where it claim to occur.

I will investigate further, and get back to you.

**Comment by rlf** [comment] 2015-10-12 12:48
I found it
https://github.com/rlf/uSkyBlock/blob/8f47f49c7ce58e9817fc965dab67e60b090fbf0f/src/main/java/us/talabrek/ultimateskyblock/island/LevelLogic.java#L177

This is caused by the same bug that is reported in #503 
Marking it as a duplicate - since the other was first - and hoping the yml files you provided will bring us closer to fixing it (Duplicate of #503)

**Closed by rlf** 2015-10-12 12:48 UTC
