### ISSUE TITLE
Hopper MineCart Error

### ISSUE THREAD

**Issue by xkxksk1234** [rlf/uSkyBlock#854] opened 2016-08-14 13:53 UTC
_Please paste the output from `/usb version` below_

```
[22:36:45 INFO]: Name: uSkyBlock
[22:36:45 INFO]: Version: 2.7.2
[22:36:45 INFO]: Description: Ultimate SkyBlock v2.7.2-45f756-430
[22:36:45 INFO]: Language: korean (korean)
[22:36:45 INFO]:   State: d=200, r=75, i=745, p=923, n=false, awe=false
[22:36:45 INFO]: Server: CraftBukkit git-Spigot-1480adb-f92e01b (MC: 1.9.2)
[22:36:45 INFO]:   State: online=false, bungee=true
[22:36:45 INFO]: ------------------------------
[22:36:45 INFO]: Vault 1.5.6-b49 (ENABLED)
[22:36:45 INFO]: WorldEdit 6.1.3;7a097ca (ENABLED)
[22:36:45 INFO]: WorldGuard 6.1.2;e38d98d (ENABLED)
[22:36:45 INFO]: Multiverse-Core 2.5-b716 (ENABLED)
[22:36:45 INFO]: ------------------------------
```

_What steps will reproduce the problem?_
1. [youtube](https://youtu.be/jtRxlR67wwo)

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
- server-log: [pastebin](http://pastebin.com/que4t6Tc)

**Comment by rlf** [comment] 2016-08-16 20:44
In spite of the chinese characters, a really good bug-report! Nice pastebin server-log, and nice visualization of the bug in question.

This is caused by a weirdness (apparently) in Spigot 1.9.2, where a method seems to be declared abstract - we expect it to either not be there, or actually be there - not that it's there, but uncallable (abstract).

Will be fixed in next release.

**Comment by xkxksk1234** [comment] 2016-08-18 04:19
I'm not Chinese

**Comment by rlf** [comment] 2016-08-18 07:33
Oh, sry, inspite of the weird-looking characters then :) I'm just an ignorant western-european, latin and greek letters is all I know...

**Comment by xkxksk1234** [comment] 2016-08-18 15:42
:)

**Comment by xkxksk1234** [comment] 2016-09-30 11:32
Recently, i found that the same error occurs in other ways.
That same bug occurs: Chest MineCart, Furnace MineCart

**Comment by rlf** [comment] 2016-09-30 12:44
Can you retest with the latest pre-release?

**Comment by xkxksk1234** [comment] 2016-10-01 09:31
Where i can download pre-release?

**Comment by xkxksk1234** [comment] 2016-10-01 09:42
Oh, I found and I apply 2.7.3 aipha 7
but, same error occurs...
and i found another error
https://www.youtube.com/watch?v=zwiRGd6O4Hg&feature=youtu.be

**Comment by dutchy1001** [comment] 2016-12-16 21:36
cant reproduce this with alpha12.
This should be fixed.

**Closed by dutchy1001** 2016-12-16 21:36 UTC
Labels: A bug, C 1.9, T ready for test
