### ISSUE TITLE
Users Kicked After Going Home - Region Deleted After Inviting

### ISSUE THREAD

**Issue by Disorbs** [rlf/uSkyBlock#165] opened 2015-01-20 23:23 UTC
hello idk if i did it right but i did /timings off and tested it a bit and got kicked and came
back on and did /timings paste so here it is i hope you can help with this, thanks

http://timings.aikar.co/?url=9790216

Also players loose their WG protection after inviting someone i dont know whats going on.

**Comment by rlf** [comment] 2015-01-21 07:47
Could you please share what version you are seeing this in, since it sounds like some of the issues solved in RC1.62.

**Comment by rlf** [comment] 2015-01-21 07:49
Duplicate of #160

**Comment by Disorbs** [comment] 2015-01-21 10:24
hello yes im using version RC1.56 also just came up with another bug/error where it seems
the user cant do /is level and in my console i get this huge spam error code here - http://pastebin.com/64B9FXaf

**Comment by dutchy1001** [comment] 2015-01-21 10:42
When doing /is level in v2.0.1 RC1.62 doesnt give me any error in console

**Comment by Disorbs** [comment] 2015-01-21 10:44
hello yes for me it doesnt either when op or deop it works but for this user it doesnt i also noticed
in the uskyblock folder /island folder his island -110,110.yml file isnt there idk if it has to do with that
but it could of been when he invited another member and messed up his island and his world guard
deleted but i had to manually add it again.

**Comment by dutchy1001** [comment] 2015-01-21 10:57
When you manual added this again you could have made a mistake with some of the value's or because it's not generated by the plugin it wont accept it manually. 

You can copy (when copying stand on the bedrock to keep the right location) his island using WorldEdit (make it into a schematic) then using the command "/usb island delete [playername]" should reset his files. Let the player create a new island (/is create or through the GUI) and then paste back (standing on the bedrock) his island back. 
Ofcourse if his island is not worth copying just let him create a new island (which is the easiest option :) )

**Comment by Disorbs** [comment] 2015-01-21 11:02
well ill have to wait till he gets on then to try it but what if it happens again when he invites someone and the user accepts it might erase his world guard again? also any news on why /is home kicks users out randomly? they asked for my timings of when it happens which is here http://timings.aikar.co/?url=9790216

**Comment by dutchy1001** [comment] 2015-01-21 11:31
We have been working on this issue and should be fixed in v2.0.1 RC1.62.
You can already copy(schematic) his island and then use the delete command, he will see as soon he logon that his island is gone and complain (lol) probably then. You can then explain to make a new island so you can copy his old one back (as said if the island is worth copying).
You will keep this problem with this player aslong his "corrupted" files are present.

**Closed** 2015-01-21 19:53 UTC
Labels: duplicate
