### ISSUE TITLE
Can't use the challenges.

### ISSUE THREAD

**Issue by xXBlazeCraftXx** [rlf/uSkyBlock#204] opened 2015-01-29 13:30 UTC
Whenever I use /c it says "Error while trying to execute this command". I have the recent version.

**Comment by dutchy1001** [comment] 2015-01-29 14:05
plz refere to the bukkit website "how to post an issue" http://dev.bukkit.org/bukkit-plugins/uskyblock/

duplicate off #201

**Closed** 2015-02-04 00:04 UTC
Labels: duplicate, input needed
