### ISSUE TITLE
Error when player use /is

### ISSUE THREAD

**Issue by MrFiliper** [rlf/uSkyBlock#606] opened 2015-12-30 15:41 UTC
If player use command /is, display this error:

EDIT: http://pastebin.com/ptKjjp3X

Where is problem?

**Comment by dutchy1001** [comment] 2015-12-30 15:57
update to 2.5.5 from github releases and see if problem still exist.

Next time a "/usb version" output would be nice as we cant keep looking back to old issue's for that info.

**Comment by rlf** [comment] 2015-12-30 18:26
First off, your version isn't a release version (most likely something you compiled your self?).
Meaning, we have no way to support you - since we have no way of knowing what you changed.

Secondly - ALWAYS!!! include output from `/usb version`. It's not a joke, we NEED it!!

Thirdly - Please use pastebin - it's so much nicer to look at.

Forthly - Since the bug occurs while trying to make the menu - odds are, you have a custom translation - and that this is the cause of the problem - and this info is ALSO good to know (we would know it, if you included `/usb version`).

**Comment by MrFiliper** [comment] 2015-12-30 21:09
OK, ok.

Here is /usb version:

> [22:08:36 INFO]: Název: uSkyBlock
> [22:08:36 INFO]: Verze: 2.5.0-SNAPSHOT
> [22:08:36 INFO]: Popis: Ultimate SkyBlock v${gitTag}-DEV-dev
> [22:08:36 INFO]: Jazyk: cs (cs)
> [22:08:36 INFO]: ------------------------------
> [22:08:36 INFO]: Server: CraftBukkit git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
> [22:08:36 INFO]: ------------------------------
> [22:08:36 INFO]: Název: Vault (ENABLED)
> [22:08:36 INFO]: Verze: 1.5.6-b49
> [22:08:36 INFO]: ------------------------------
> [22:08:36 INFO]: Název: WorldEdit (ENABLED)
> [22:08:36 INFO]: Verze: 6.1;no_git_id
> [22:08:36 INFO]: ------------------------------
> [22:08:36 INFO]: Název: WorldGuard (ENABLED)
> [22:08:36 INFO]: Verze: 6.1
> [22:08:36 INFO]: ------------------------------
> [22:08:36 INFO]: Název: AsyncWorldEdit (ENABLED)
> [22:08:36 INFO]: Verze: 2.2.2

**Comment by rlf** [comment] 2015-12-30 22:43
Closing this issue, as it's obviously caused by a non-released version combined with a non-released translation.

**Closed by rlf** 2015-12-30 22:43 UTC
Labels: C i18n, S misconfiguration
