### ISSUE TITLE
Bug: Cant get player island lvl

### ISSUE THREAD

**Issue by voodootje0** [rlf/uSkyBlock#503] opened 2015-10-07 21:14 UTC
When I open the island menu and wants to check my island lvl I get this error:

[23:06:04] [Server thread/INFO]: voodootje0 issued server command: /is
[23:06:07] [Craft Scheduler Thread - 33/WARN]: Exception in thread "Craft Scheduler Thread - 33" 
[23:06:07] [Craft Scheduler Thread - 33/WARN]: org.apache.commons.lang.UnhandledException: Plugin uSkyBlock v2.4.7 generated an exception while executing task 1683
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at us.talabrek.ultimateskyblock.island.LevelLogic$1.run(LevelLogic.java:174)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

Versions:
![image](https://cloud.githubusercontent.com/assets/6852308/10351258/ca979d18-6d48-11e5-9e31-dad9db67251c.png)

The strange thing is I only get this error when I am using a schematic. Maybe the plugin cannot check what items are on my island?

**Comment by rlf** [comment] 2015-10-07 21:57
It seems you have been unlucky with the placement of that particular island.

Could you please share your config.yml and the island.yml in question.

**Comment by voodootje0** [comment] 2015-10-08 18:09
# The language used in the plugin (en is default).
language: en
options:
  general:

    # [integer] The max number of players allowed in a single party. (including the leader)
    maxPartySize: 4

    # [integer] The time in seconds before a player can use the /island info command again. (note: cooldowns are reset when the plugin is reloaded)
    cooldownInfo: 20

    # [integer] The time in seconds before a player can use the /island restart command again.
    cooldownRestart: 30

    # [integer] The time in seconds before a player can use the /island biome command again.
    biomeChange: 180

    # [integer] The number of milliseconds between the same notification is sent to the player.
    # This is used when events are triggered heavily - i.e. item-pickup-prevention, damage-prevention etc.
    maxSpam: 2000

    # [string] The name of the skyblock world, will be automatically generated if it doesn't exist.
    worldName: skyworld

    # [integer] Area around 0,0 where islands will not be created to protect spawn.
    spawnSize: 150
  island:

    # [integer] The y-coordinate (height) where islands are spawned.
    height: 150

    # [integer] The number of blocks between islands.
    distance: 200

    # [integer] The size of the protective region for each island. Can't be higher than 'distance'
    protectionRange: 190

    # [filename] The schematic to use for island generation.
    # Put your schematic in the 'uSkyBlock/schematics' folder, you don't need to add the '.schematic' part below.
    schematicName: island

    # [true/false] If true, remove all hostile mobs when a player teleports back to their island.
    removeCreaturesByTeleport: false

    # [item list] The list of items to place in the chest when a player starts a new island. ITEM_ID:HOW_MANY.
    # default is 2 ice, 1 watermelon, 1 cactus, 1 lava bucket, 1 red & brown mushroom, 1 pumpkin seed, 1 sugar cane, 1 sign.
    chestItems: 79:2 360:1 81:1 327:1 40:1 39:1 361:1 338:1 323:1

    # [true/false] If true, add extra items to a chest when a player starts a new island. (for donors and special players)
    addExtraItems: true

    # [integer] The delay in seconds before teleporting to an island. Affects /is home, /is warp, /is spawn
    islandTeleportDelay: 2

    # Allow PvP on the island
    allowPvP: deny

    #[true/false] Allow players to completely lock their islands so non-party members can't enter. (locking still requires permission usb.lock)
    allowIslandLock: true

    # [true/false] Use old SkySMP style island generation. Set this to true if you want to use the old
    # island style, or set to false if you want to use the new style island generation. Only affects new islands.
    useOldIslands: false

    # [true/false] If true, use island levels/ranks (/island info) - may have a slight impact on performance
    # Set to false if you have performance issues
    useIslandLevel: true

    # [true/false] Whether or not /is top should be available.
    useTopTen: true

    # [integer] The time in minutes for how often the top-ten list will be re-generated when doing /is top
    topTenTimeout: 20

    # [integer] The time in minutes for refreshing/recalculating the score for players on their island
    # set to 0 to disabled
    autoRefreshScore: 5

    # [true/false] Whether or not to include island-members on the top-ten scoreboard
    topTenShowMembers: true

    # [true/false] Whether or not to try and fix flat-land issues when players join the server
    # Note: will make the PlayerJoin event take longer.
    fixFlatland: false

    # The format used in /islandtalk chat messages
    chat-format: '&9SKY &r{DISPLAYNAME} &f>&d {MESSAGE}'

    # How many entries to remember in the island-log
    log-size: 10

    # Limits the spawning
    spawn-limits:

      # [true/false] if true, the limits below will limit spawning
      enabled: true

      # how many animals can be spawned within an island
      animals: 48

      # how many monsters can be spawned on an island
      monsters: 50

      # how many villagers can be spawned on an island
      villagers: 16

    # [permission] The name of the permissions to check if extra items are added to the chest, you can change these or add more
    # Only checked if 'addExtraItems' is set to true.
    # [permission:item list] The list of extra items to add to the chest, will only be added if the player has the permission. ITEM_ID:HOW_MANY
    # When granting the permission, prefix it with "usb." so the full permission to add would be usb.smallbonus
    extraPermissions:
      smallbonus: 4:16 320:5
      mediumbonus: 50:16 327:1
      largebonus: 3:5 12:5
      giantbonus: 2:1 110:1
      extremebonus: 352:8 263:4
      donorbonus: 261:1 262:32 272:1
  extras:

    # [true/false] If true, return players that don't have an island (this includes players removed from a party while offline), to the server spawn when they login.
    # NOTE: Requires EssentialsSpawn or another plugin with the "/spawn" command
    sendToSpawn: true

    # [true/false] If true, a player can right-click on a block of obsidian on their island while holding an empty bucket to remove the obsidian and fill the bucket with lava. This is useful for people that accidently
    # turn their lava into obsidian with a bad cobblestone generator design. Will only work on the player's island and if there are no other obsidian blocks nearby (so can't be used on portals).
    obsidianToLava: true

  # Contains flags for enabling PROTECTION of various mechanics.
  protection:

    # Whether or not, items dropped on the ground should be limited to party-members.
    item-drops: true

    # If true, only creepers targeting party-members will explode
    creepers: true
    visitors:

      # Protect visitors from trampling your crop
      trampling: true

      # Protect against visitors attacked animals
      kill-animals: true

      # Protect against visitors attacking monsters
      kill-monsters: true

      # Protect from shearing
      shearing: true

      # Protect from villager-trading
      villager-trading: true

      # Whether or not visitors are protected from fall damage
      fall: true

      # Whether or not visitors are protected from fire damage (incl. lava)
      fire-damage: true

      # Whether or not visitors should be allowed to drop items
      item-drops: true

      # Warns online members when a player visits the island.
      warn-on-warp: true

      # Whether or not to actively block banned players from entering an island (by walking/flying).
      block-banned-entry: true
  party:

    # The number of ticks before an invite timeouts (20 ticks per sec.)
    invite-timeout: 600

    # The format used in /partytalk chat messages
    chat-format: '&9PARTY &r{DISPLAYNAME} &f>&b {MESSAGE}'
    leave:

      # [true/false] Whether to require confirmation (i.e. repeating the command twice).
      confirmation: true

  # This section provide some performance tweaking configs
  advanced:

    # If true, display-name is looked up (might be performance intensive).
    useDisplayNames: false

    # [number] The threshold for purging islands.
    # any island with a level above this, is spared.
    purgeLevel: 10

    # [seconds] The number of seconds for confirming a command by
    # re-executing it (/is leave, /is restart).
    confirmTimeout: 10

  # Section about restarting your island (or accepting an invite).
  restart:

    # Clears the player's inventory on island create/restart
    clearInventory: false

    # Clears the player's armor on island create/restart
    clearArmor: false

    # Clears the player's enderchest on island create/restart
    clearEnderChest: false

    # [ticks] The number of ticks to wait, before porting the player back
    # on /is restart or /is create (default: 40)
    teleportDelay: 20

    # [true/false] Whether or not the player should be auto teleported to the island when it's ready
    teleportWhenReady: true

    # [true/false] Whether to require confirmation (i.e. repeating the command twice).
    confirmation: true

# This section allows donors to get specific perks
#donor-perks:
#  usb:
#    donor:
#      example:
#        # permission: usb.donor.example will give the below extra items
#        maxPartySize: 5
#        schematics: [LargeIsland]
#        animals: 60
#        monsters: 100
#        villagers: 24
#        rewardBonus: 0.5
#        hungerReduction: 0.5
asyncworldedit:

  # Supports disabling the detection of AWE
  enabled: true

  # Show progress to the user every 5 seconds
  progressEveryMs: 5000

  # Or 20pct (what-ever comes first)
  progressEveryPct: 20
  watchDog:

    # The maximum time to wait for AWE paste to complete (2m, 3m20s, etc.)
    timeout: 5m

    # The number of ms between each heartbeat
    heartBeatMs: 2000
worldguard:
  entry-message: true
  exit-message: true

# DO NOT TOUCH THE FIELDS BELOW
version: 31
force-replace:
  options:
    party:
      invite-timeout: 100
    island:
      islandTeleportDelay: 5

**Comment by dutchy1001** [comment] 2015-10-08 18:51
`Could you please share your config.yml and the island.yml in question.`
The "in question" means the 2 .yml files, the config.yml and the island.yml (EG 220,440.yml) what has been used when this error occurred.
You did the config.yml now the other "island.yml"

**Comment by voodootje0** [comment] 2015-10-09 23:05
general:
  level: 0
  warpLocationX: 0
  warpLocationY: 0
  warpLocationZ: 0
  warpActive: false
  biome: OCEAN
  regionVersion: 11 en
version: 1
log:
- 1444251644078;The island has been created.
- 1444054667246;The island has been created.
party:
  leader: voodootje0
  members:
    voodootje0:
      canChangeBiome: true
      canToggleLock: true
      canChangeWarp: true
      canToggleWarp: true
      canInviteOthers: true
      canKickOthers: true
      canBanOthers: true
      maxPartySizePermission: 8
      maxAnimals: 48
      maxMonsters: 50
  currentSize: 1

**Comment by rlf** [comment] 2015-10-10 07:38
How did you get that island?
Because it's obviously invalid, compared to your config.yml file.
Your spawnSize is set to 150, meaning no islands should be within 150 blocks of spawn.

Your island is at 0,0.

The interesting part is, how that happened.

**Comment by voodootje0** [comment] 2015-10-11 22:10
Yeah it is very intresting how that is possible, I don't have any idea why. And you can't fix it or test a schematic.

**Comment by csorrows** [comment] 2015-10-12 00:29
@rlf Would it work if he calculated the location it should have been placed at, fixed the region file, island and player file, then updated the last island location? @voodootje0 is this a new server? are there any other islands?

**Comment by rlf** [comment] 2015-10-12 08:13
Yes, you can manually move things around, but I wouldn't recommend it.

Odds are, that a `/usb island delete <name>` followed by a `/is create` should give a valid location.

Still puzzled as to how the error occurred in the first place - but we do have some issues lurking reg. initialization, esp. during "player-join" scenarios (i.e. if you fire an /is create too soon after joining, weird stuff seems to happen).

**Comment by csorrows** [comment] 2015-10-12 09:12
Maybe you could code something that would disallow all commands until the plugin is fully loaded? I have heard other plugins that have done this.

If this was caused by what you mentioned, it should solve that issue.

**Comment by rlf** [comment] 2015-10-12 09:32
Well, we do, we do not register commands etc. until the plugin is fully loaded.

But... we have an achillesheel in the UUID name-changing code, that has been known to be buggy.
It's still on our TODO list to resolve that issue - but tbh. I usually lose the will to code when I start on that task :) Since it sort of requires a refactoring/conversion of most of our internal model.

**Comment by csorrows** [comment] 2015-10-12 10:16
Sounds like a pretty lengthy, boring, crappy task. I would not have much drive reworking all that mess either.

**Comment by rlf** [comment] 2015-10-12 13:09
Question to @voodootje0  and @Aberzhulan: Did you by any chance change the `protectionRange` and/or `distance` in the main config file?
Because, it seems, the WorldEdit region of the island, does not match the radius calculated based on `protectionRange` (this might be a rounding issue too, just curious).

**Comment by dutchy1001** [comment] 2015-12-14 11:42
No further input. Levels showing properly in our test servers.
Closing this.

**Closed by dutchy1001** 2015-12-14 11:42 UTC
Labels: bug, ready for test
