### ISSUE TITLE
Challenge completion prefix color not working

### ISSUE THREAD

**Issue by c0wg0d** [rlf/uSkyBlock#392] opened 2015-06-09 05:39 UTC
I tried setting to '&b' and to '§b' and neither worked.  Screenshots below.

![2015-06-08_22 25 22](https://cloud.githubusercontent.com/assets/10082424/8051254/27ac0468-0e2f-11e5-93f4-15bbc1acd65b.png)

![2015-06-08_22 35 13](https://cloud.githubusercontent.com/assets/10082424/8051259/2bedd826-0e2f-11e5-8c5e-e87806a8e602.png)

**Comment by dutchy1001** [comment] 2015-06-09 06:47
Can you post, through pastebin, the challenges.yml?

**Comment by c0wg0d** [comment] 2015-06-09 06:51
http://pastebin.com/3Fusdmy3

**Comment by dutchy1001** [comment] 2015-06-09 07:02
Is it only with the Coalminer challenge or with any challenge?

If with all challenges try to change the **broadcastText** to  **"\xa76"** (almost on top of the config).
All other color settings there might have to be in the same format then (this will be in the next update)
challengeColor: "\xa7e"
finishedColor: "\xa72"
repeatableColor: "\xa7a"

**Comment by c0wg0d** [comment] 2015-06-09 07:14
Same issue unfortunately.

![2015-06-09_00 13 20](https://cloud.githubusercontent.com/assets/10082424/8052450/88ffd5e8-0e3c-11e5-90b9-a6df0cd9c2a1.png)

**Comment by dutchy1001** [comment] 2015-06-09 08:32
What versions are you using, Do the **/usb version** and let us know plz

**Comment by c0wg0d** [comment] 2015-06-09 14:01
Sorry I forgot to put that in my initial report.

>usb version
[10:01:26 INFO]: Name: uSkyBlock
[10:01:26 INFO]: Version: 2.3-HF3
[10:01:26 INFO]: Description: Ultimate SkyBlock v2.3-HF3-9fc81a-dev
[10:01:26 INFO]: ------------------------------
[10:01:26 INFO]: Server: CraftBukkit git-Spigot-44c59bf-1880a9c (MC: 1.8.7)
[10:01:26 INFO]: ------------------------------
[10:01:26 INFO]: Name: Vault
[10:01:26 INFO]: Version: 1.5.3-b37
[10:01:26 INFO]: ------------------------------
[10:01:26 INFO]: Name: WorldEdit
[10:01:26 INFO]: Version: 6.1;no_git_id
[10:01:26 INFO]: ------------------------------
[10:01:26 INFO]: Name: WorldGuard
[10:01:26 INFO]: Version: 6.1
[10:01:26 INFO]: ------------------------------

**Comment by dutchy1001** [comment] 2015-06-09 15:36
I started a fresh usb server with the following:

[16:17:42] [Server thread/INFO]:  Name: uSkyBlock
[16:17:42] [Server thread/INFO]:  Version: 2.3-HF3
[16:17:42] [Server thread/INFO]:  Description: Ultimate SkyBlock v2.3-HF3-9fc81a-dev
[16:17:42] [Server thread/INFO]:  Server: CraftBukkit git-Spigot-b3c0272-7723b90 (MC: 1.8.7)
[16:17:42] [Server thread/INFO]:  Name: Vault
[16:17:42] [Server thread/INFO]:  Version: 1.5.3-b37
[16:17:42] [Server thread/INFO]:  Name: WorldEdit
[16:17:42] [Server thread/INFO]:  Version: 6.1;no_git_id
[16:17:42] [Server thread/INFO]:  Name: WorldGuard
[16:17:42] [Server thread/INFO]:  Version: 6.1.1-SNAPSHOT.1609-2d28e8d

The spigot file has a slight different compile date and WorldGuard is 1 newer then yours. This will not be the cause of your text not taking the color code.

What happens when your going back to default color? (&6)
What happens when you do a repeat completion of a challenge?

I have tried several colors that all worked without any hassle. (changing the challenges.yml and using the /usb reload)

Do you have any chat related plugins recently updated?

**Comment by c0wg0d** [comment] 2015-06-09 15:43
I was wondering if my chat plugin was causing the issue, but as you can see in my screenshots, the other colors work just fine--it's only the broadcast message to all players that has the issue.  And I have used the broadcastMessage() function in other plugins where my chat plugin is used, and there's no issue there either.

I looked at the source for uSkyblock and they are using "\u00a7" as a prefix, so I will try that.  I can't test until tonight (about 12 hours from now).

If the devs have time to look at my chat plugin and see if there are issues with it, that would be awesome.  It's here: https://github.com/c0wg0d/LibsChat

**Comment by dutchy1001** [comment] 2015-06-09 15:46
you could try the latest pre-release from [here](https://github.com/rlf/uSkyBlock/releases/tag/v2.3-HF6c)

**Comment by rlf** [comment] 2015-06-09 19:08
Well, it's not \xa7, it's either '§' or '\u00a7' or U+00A7 or .. you get the point http://www.fileformat.info/info/unicode/char/a7/index.htm

My bet is, that the problem is the encoding of your challenges.yml file.
We require it to be UTF-8 encoded, that is how we read it.

Try installing and opening it in Notepad++ or another sensible text-editor, and make sure the file-encoding is UTF-8, and the char is '§'.

**Comment by dutchy1001** [comment] 2015-06-09 20:17
And if that doesnt work then I suggest to disable the chat plugin to see if that makes a differance.

**Comment by c0wg0d** [comment] 2015-06-10 03:52
Okay, this is taking me down a very dark and scary path...  I've never encountered the need to mess with file encoding on any other plugin before.  I'm not saying your way is wrong, but why can't we just use an & like all other plugins?  And the colors clearly work in all the other cases of broadcast messages, just not challenge completion.

I use vim, and I did :set fileencoding=utf-8 and saved the file, but then when I reopened the file, my broadcastMessage config changed to 'Â§b', which I'm guessing is some kind of display issue because my ssh client is doing something weird?  I don't know, but I can't be the only one with this issue... can I?

**Comment by rlf** [comment] 2015-06-10 10:02
UTF-8 is not a "dark and scary path", it's the bright and enlightened path og wonderful things!!! ;-)

In order to use & instead of §, we need to do some conversion in the plugin.
Doable, but not something we have put any effort into yet.

**Comment by c0wg0d** [comment] 2015-06-10 17:44
I agree with you, but by default, mysql uses latin1, Putty uses latin1, Ubuntu uses C, and vim uses us-ascii.  It's a nightmare!

In any case, I was able to convert the file to utf-8, and then the color worked in game.  So thank you for that.  You can close this bug, but I would still like the ability to use '&' in the configs.

**Comment by dutchy1001** [comment] 2015-06-10 18:06
Glad you got it sorted.
I still dont think it was a bug on our side but glad we could point you into the right direction of sorting it.

**Closed by dutchy1001** 2015-06-10 18:06 UTC
