### ISSUE TITLE
Ability to delete your island or ability to invite players to your island who already has their own island

### ISSUE THREAD

**Issue by Lahemees47** [rlf/uSkyBlock#138] opened 2015-01-09 21:30 UTC
As the title says, it would be great to have an ability to delete your island so players could invite other players who already have an island.

**Comment by rlf** [comment] 2015-01-10 12:20
This should already be possible.

I.e. not deleting an island, but accepting an island invitation once you are the only member of your own island.

**Comment by dutchy1001** [comment] 2015-01-10 13:01
This question has me a bit confused. 
When you are invited to an island your own island is always deleted (if you have one ofcourse). As far as  I know it will not be possible to have your own island (owner) and be a member on an other island.

**Comment by Lahemees47** [comment] 2015-01-12 20:12
My players can't invite other players who already have an island. If they try to invite, plugin says "That player is already with a group on an island.", even if they're not in any group.

**Comment by dutchy1001** [comment] 2015-01-12 20:22
What version of uSkyblock/WorldEdit/WorldGuard/Vault  are you using?

When it says "That player is already with a group on an island." have you checked the config file of that island if the player is alone on that island? Can you upload this config to pastebin and link it here? (you can find this in the \uSkyBlock\islands folder).

**Comment by Lahemees47** [comment] 2015-01-12 20:35
Versions:
uSkyBlock: v2.0.1-SNAPSHOT-a2a843
WorldEdit: v6.0.2-SNAPSHOT;3347-fe6717a0
WorldGuard: v6.0.0-SNAPSHOT.1510-
Vault: v1.5.0-b28

Just a random island config file: http://pastebin.com/mkVR0DaD
It looked in other configs too, seems like every player has automatically it's own group.

**Comment by dutchy1001** [comment] 2015-01-12 20:51
Your uSkyblock version is way old compair to the releases that have been released (there have been 22 updates since).
Also to post the config of the person that had problems with the island would have been better as the one you posted has nothing wrong as far I can see.

Update first to the latest version https://github.com/rlf/uSkyBlock/releases/latest and see if the problem is still there.

**Comment by Lahemees47** [comment] 2015-01-12 22:09
Oh right, I haven't updated it for a while. I'll update it tomorrow and let you know.
As far as I know, nobody could invite anyone on their island, so I think it doesn't matter whose config that was.

**Comment by Lahemees47** [comment] 2015-01-13 18:06
Yeap, invites are working after updating, but now players don't get items as rewards for completing challenges, only XP.

Error: http://paste.ubuntu.com/9733097/

**Comment by rlf** [comment] 2015-01-18 09:41
It errs on a line, where it tries to tell the player how much "econ"-wise he get as reward.
Are you using economy on your server? And is Vault correctly configured?

I will try to make the code more robust - perhaps just ensure, that if it fails, it doesn't fail until the player has gotten the rewards :D

**Comment by rlf** [comment] 2015-01-18 22:17
Closing this issue - since the original issue has been resolved.
Please create a new one - if the econ thingy persists.

**Closed by rlf** 2015-01-18 22:17 UTC
