### ISSUE TITLE
Challenge command and allias give error on mc 1.13.1

### ISSUE THREAD

**Issue by SgtLegoTown** [rlf/uSkyBlock#1095] opened 2018-09-01 20:15 UTC
https://pastebin.com/M01jKvWP

_What steps will reproduce the problem?_
1. trying to execute /challenges or /c

usb v included in the paste

**Comment by rlf** [comment] 2018-09-03 15:10
Duplicate of #1094

**Closed by rlf** 2018-09-03 15:10 UTC
Labels: A bug, S duplicate
