### ISSUE TITLE
Bug: Challenge name will be lowercase

### ISSUE THREAD

**Issue by voodootje0** [rlf/uSkyBlock#504] opened 2015-10-07 21:31 UTC
When I change in challenges.yml the name of the challenge it will be lowercase in the ingame challenge menu.

![image](https://cloud.githubusercontent.com/assets/6852308/10351681/37c19bc6-6d4b-11e5-83c5-1a04b7ad00d7.png)
![image](https://cloud.githubusercontent.com/assets/6852308/10351688/3f138722-6d4b-11e5-972d-69d383d0c275.png)

Maybe you can also add a setting to change the displayname now its white and italic.

**Comment by rlf** [comment] 2015-10-07 21:55
That is not a bug, it's a feature.
Originally the plugin was command-line based (and still supports that mode), where challenge-names being case-sensitive only cause problems.

I'm not sure that is something we should change.

**Comment by csorrows** [comment] 2015-10-08 07:32
Maybe have every call that is displayed use the config case and have all commands force lower case. That way you can have it display the way you want it to yet the commands are not case sensitive. Sorry if this doesn't make sense, it's been a long day.

**Comment by rlf** [comment] 2015-10-08 11:01
Next (natural) step would be to both allow spaces and other punctuation, and even translate it.

I will take a look at what it requires to support more versatile challenge-names (and rank-names for that matter).

**Comment by voodootje0** [comment] 2015-10-11 22:11
Thanks for your answer

**Comment by rlf** [comment] 2015-10-31 23:23
Fixed in #514

**Closed by rlf** 2015-10-31 23:23 UTC
Labels: feature request
