### ISSUE TITLE
Name Changes

### ISSUE THREAD

**Issue by DogsPaw** [rlf/uSkyBlock#344] opened 2015-04-11 04:56 UTC
This was brought up in #310, but that went unanswered. The issue resolved itself to being isolated to a couple players. The name changes however are not working properly. It worked for initial name changes, but players who change their name again, won't have their islands converted fully. If you issue /usb goto {name} it'll work, and if you register them to the Island, it will say they already have an island, but if you move, it will leave the region, and enter their fixed name.

uSky: 2.3-HF1a
Vault 1.5.3
WE: 3342
WG: 1586

**Comment by rlf** [comment] 2015-04-12 10:23
Sorry for not answering in the original thread @DogsPaw  - we have been trying to figure out what the cause of those "random" issues were, but haven't found a solution yet.

If what you describe above, is a reproducible way to get the problem - we have something solid to continue the investigation on.

**Comment by dutchy1001** [comment] 2015-04-13 11:20
I think it also is connected with issue #285

**Comment by dutchy1001** [comment] 2015-04-14 22:27
after extensive testing with the name changing (see #285 ) I think our dev found the issue.

**Comment by rlf** [comment] 2015-04-15 22:24
Duplicate of #285 and #310

**Closed by rlf** 2015-04-15 22:24 UTC
Labels: bug, duplicate, ready for test
