### ISSUE TITLE
uSkyBlock v2.5.3-bukkit-1.7.9 language bug

### ISSUE THREAD

**Issue by wei199891wei** [rlf/uSkyBlock#672] opened 2016-02-19 12:11 UTC
Name: uSkyBlock
Version: 2.5.3-bukkit-1.7.9
Description: Ultimate SkyBlock v2.5.3-bukkit-1.7.9-da7f04-383
Language: en (en)
Server: CraftBukkit git-Spigot-1649 (MC: 1.7.10)
Name: Vault (ENABLED)
Version: 1.4.1-b436
Name: WorldEdit (ENABLED)
Version: 6.1;no_git_id
Name: WorldGuard (ENABLED)
Version: 6.1

If change the language to 'zh_CN',the GUI will have a error.
Pls help me.I love this plugin very much.But my friends' and my English is not good.

This is the log file.
[20:05:52 ERROR]: Could not pass event InventoryClickEvent to uSkyBlock v2.5.3-bukkit-1.7.9
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-1649]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1649]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [spigot.jar:git-Spigot-1649]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-1649]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1477) [spigot.jar:git-Spigot-1649]
        at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:15) [spigot.jar:git-Spigot-1649]
        at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.handle(PacketPlayInWindowClick.java:65) [spigot.jar:git-Spigot-1649]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot.jar:git-Spigot-1649]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1649]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1649]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1649]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1649]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1649]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1649]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 45
        at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftInventoryCustom$MinecraftInventory.getItem(CraftInventoryCustom.java:70) ~[spigot.jar:git-Spigot-1649]
        at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftInventory.getItem(CraftInventory.java:49) ~[spigot.jar:git-Spigot-1649]
        at us.talabrek.ultimateskyblock.menu.IntegerEditMenu.onClick(IntegerEditMenu.java:40) ~[?:?]
        at us.talabrek.ultimateskyblock.menu.ConfigMenu.onClick(ConfigMenu.java:43) ~[?:?]
        at us.talabrek.ultimateskyblock.event.MenuEvents.guiClick(MenuEvents.java:25) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-Spigot-1649]
        ... 13 more

**Comment by dutchy1001** [comment] 2016-02-20 00:48
The version you use (uSkyBlock v2.5.3-bukkit-1.7.9) does still have a language bug. This is fixed in the later versions but that means you need to update to 1.8.x.
It's either update or use the default "en" language (also the zh_CN is less then 42% completed and this might cause issue's too).

**Comment by wei199891wei** [comment] 2016-02-20 03:05
I want to use your plugin in 1.7.10.Can you let uSkyBlock v2.5.7 or later version support 1.7.10 or fix uSkyBlock v2.5.3-bukkit-1.7.9's language bug?I love your plugin very much.My friends' eng is not good.I want to use zh_CN.Pls help me?

**Comment by dutchy1001** [comment] 2016-02-20 12:22
What's holding you back to update to 1.8 or soon 1.9?

**Comment by wei199891wei** [comment] 2016-02-20 12:27
Because not everyone buy the minecraft(I bought).Someone play it not use the official launcher.

**Comment by dutchy1001** [comment] 2016-02-20 14:33
The question is then, should we do bug fixes for players that didn't bought the game?
I will not condone anyone for doing so (because that's not up to me), but with some research there is more possible then 1.7.x (but don't ask me).
Maybe teach your players that so you can then update with the new awesome features uSkyblock has to offer then.

**Comment by dutchy1001** [comment] 2016-03-06 14:37
Due to new release of MC 1.9 with the support removed for 1.7 and lower this issue will more then likely to be obsolete.

**Closed by dutchy1001** 2016-03-06 14:37 UTC
Labels: A bug, C 1.7.9, C i18n

**Comment by DimaTiunov** [comment] 2016-03-19 11:16
The author, this version is relevant for playing on kcauldron that works to version 1.7.10

**Comment by dutchy1001** [comment] 2016-03-19 11:48
After many times to try and setup a server for KCauldron and NOT succeeding I have given up on KCauldron. It's to old as 1.7 is not supported any more by MC or Spigot. Time for KCauldron to get up to date to 1.9

**Comment by DimaTiunov** [comment] 2016-03-29 14:13
Update this core server to a higher version is impossible, since the developers bolshenstvo left the team to participate in the development of Sponge. But you, I still ask to help with the correction of this bug because I really need to find a solution to this problem.

**Comment by rlf** [comment] 2016-03-30 07:43
The "language bug" is caused by missing translations in the language file you have (zh_CN), which means the UI stops working, since the title of the menu isn't matching.

The bug that was fixed in later versions, avoided using "empty strings" when the translations were missing - which meant the UI would revert to english - and the UI click-events would still work.

If you want this to work, without upgrading your server, translate the zh_CN.po file, and all should be fine.

**Comment by DimaTiunov** [comment] 2016-03-31 07:31
I use ru translation. With regard to the translation I translate it to a new file from a template?

**Comment by rlf** [comment] 2016-03-31 22:10
You need to make sure the "Config:" entry in your .po file has been correctly translated (i.e. is not empty "").
