### ISSUE TITLE
Kicked player overriding island owner

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#507] opened 2015-10-10 02:20 UTC
Version Info: http://pastebin.com/raw.php?i=SGkzPSG3

When one of my players, labrat35, kicks his island member, RelentlessPvPer, after some time the island member takes over his island as owner and it resets. When viewing the WorldGuard region info, labrat35 is still listed as the owner of the region. This is the second time this happened for labrat35. His island.yml file shows two island creation dates, 9/29/15 and 10/9/15; both days that this happened. I've had similar reports from other players in the past.

I can't find any errors but I don't know exactly where in the log to check for them since labrat35 experiences the issue when he logs on instead of when it happens. I'll keep looking and update this ticket if I find anything.

labrat35.yml: http://pastebin.com/raw.php?i=jv0AUGsg
RelentlessPvPer.yml: http://pastebin.com/raw.php?i=y8xqGyJs
-5500,6500.yml: http://pastebin.com/raw.php?i=W3rcaAJm
WG Region Info: http://pastebin.com/raw.php?i=rpqJz81S

**Comment by rlf** [comment] 2015-10-10 07:03
Thanks for the report.

What is the sequence of commands leading to it?
It's relevant ig RelentlessPvPer get's labrats island on `/is create` or doing `/is restart`.

**Comment by rlf** [comment] 2015-10-10 07:42
The fact that it says 2 x "The island has been created." leads me to believe, that it somehow is listed in the orphans file.

We did relax the "island-detection" code when finding new spots, primarily because of the changed functionality of the purge command.

The main problem here is, that we cannot reproduce the things you seem to be experiencing.

We will try to reproduce it in our test-environment, and get back to you.

**Comment by rlf** [comment] 2015-11-03 23:05
Been seeing something similar on my server lately.
We had a concurrency issue when loading player-data, that has been resolved in v2.5.3 - might be the cause of it. But as long as we cannot reproduce it consistently, it's really hard to fix.

**Comment by dutchy1001** [comment] 2016-01-10 20:30
If this still occurs we can reopen or make a new issue, for now it seems to be fixed with v2.5.3

**Closed by dutchy1001** 2016-01-10 20:30 UTC
Labels: A bug
