### ISSUE TITLE
Error InventoryClickEvent uSkyblock 2.5.3

### ISSUE THREAD

**Issue by manercraft** [rlf/uSkyBlock#548] opened 2015-11-07 01:55 UTC
Hello,
I have a error when a player interact with his inventory/chest
http://pastebin.com/917sv0wL

Last version of spigot (yesterday)

**Comment by rlf** [comment] 2015-11-07 05:52
Provide output from `/usb version`

Latest version means noooothing to us.

**Comment by csorrows** [comment] 2015-11-07 07:45
noooooooooothing? Haha.

**Comment by manercraft** [comment] 2015-11-07 21:26
It's a release, why don't use ?

![usb version](https://cloud.githubusercontent.com/assets/1338257/11017414/9201cba4-859e-11e5-9155-7ff2340f8062.png)

**Comment by csorrows** [comment] 2015-11-08 07:09
The /usb version feature was added to aid in trouble shooting. That is why it is REQUIRED when submitting issues. Thank you for the output.

**Comment by rlf** [comment] 2015-11-08 10:22
The output from `/usb version` tells us all we need, but `the latest version` only raises a lot of questions. 

Now that we know what you have, we have a chance of finding out why you are experiencing issues.

When you write: "when a player interact with his inventory/chest" does that mean any interaction?
Or is it when he interacts with the `/is` menu? 
Does it happen in all worlds, or just in the skyworld?

It's almost 100% caused by the french translation you use, so perhaps try using `/usb lang en` and see if the problem disappears (that info is also valuable to us).
Also, if you have any more detailed log (the pastebin you provided, seems to be the console-output, some times the actual log-files contains more details).

More specifically, I'm trying to figure out, exactly where the `ArrayIndexOutOfBoundsException` originates.

**Comment by manercraft** [comment] 2015-11-08 12:04
"When you write: "when a player interact with his inventory/chest" does that mean any interaction?"
Just when a player tries to move a item in this inventory

All worlds

I'll try /usb lang fr  when I can

**Comment by rlf** [comment] 2015-11-08 12:20
Acknowledged.
It's caused by the latest localisation framework we introduced.
A workaround is to place the following:
```
msgid "Config:"
msgstr "Config:"
```
in `fr.po` within the `plugins/uSkyBlock/i18n` folder, and restarting the plugin.

**Comment by dutchy1001** [comment] 2015-12-14 11:24
No further input, I guess this is solved then.
Closing this for now.

**Closed by dutchy1001** 2015-12-14 11:24 UTC
Labels: bug
