### ISSUE TITLE
CME on login

### ISSUE THREAD

**Issue by drtshock** [rlf/uSkyBlock#292] opened 2015-03-01 00:16 UTC
Getting a CME when certain players login.
https://gist.github.com/drtshock/fda1dd1fcaeb0db82a15

>version uskyblock
[17:15:53 INFO]: uSkyBlock version 2.2-HF9b
[17:15:53 INFO]: Ultimate SkyBlock v2.2-HF9b-8e30a8-dev
[17:15:53 INFO]: Author: Talabrek, R4zorax and others

**Comment by rlf** [comment] 2015-03-01 09:01
It's not caused by "certain players logging in", but rather the concurrent modifcation and access of the playerDB.
It seems legit though, and are most likely related to #285

**Comment by rlf** [comment] 2015-03-01 09:58
v2.2-HF13d

**Comment by rocky143** [comment] 2015-03-02 09:08
@rlf Would you be releasing v2.2-HF13d jar file anytime soon.
All the HF13* versions have no jar files for download https://github.com/rlf/uSkyBlock/releases

**Comment by EvilOlaf** [comment] 2015-03-02 09:49
Whats the issue with building them by yourself from source? ;)

**Comment by rocky143** [comment] 2015-03-02 10:03
I wouldn't be requesting for the jar file if I new how to do it myself.

**Comment by rlf** [comment] 2015-03-02 10:06
Aah, my bad, the build-server seems to be failing. Will fix ASAP.

**Comment by dutchy1001** [comment] 2015-04-08 07:49
is this still an issue as I dont know how to test this.

**Comment by rlf** [comment] 2015-04-08 13:23
Close this for now

**Closed by rlf** 2015-04-08 13:23 UTC
Labels: bug, ready for test
