### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [rlf/uSkyBlock#217] opened 2015-01-31 20:57 UTC
Timings are interesting:
![image](https://cloud.githubusercontent.com/assets/3297866/5989806/153d3d10-a994-11e4-85ee-a195279e6915.png)

**Comment by rlf** [comment] 2015-01-31 22:26
Yes, for now, you should disable the options.island.autoRefreshScore by giving it a value of 0.

It's due to the island-level calculations being done too often now. and it takes more than a tick to complete for large islands.

**Comment by rlf** [comment] 2015-01-31 22:26
Duplicate of #215

**Comment by TheOnlyRealTGS** [comment] 2015-01-31 22:29
Okay.

**Closed** 2015-02-02 12:31 UTC
Labels: duplicate
