### ISSUE TITLE
SkyBlock GUI buttons not working

### ISSUE THREAD

**Issue by AppleTechMedia** [rlf/uSkyBlock#163] opened 2015-01-19 22:21 UTC
Whenever I go into the GUI and try to change the biome or invite a player to my island, It tells me I don't have permissions to do these. I posted the error codes down below for more info if you need it. I am using uSkyBlock v2.0.1-RC1.54, WorldGuard v6.0.0-beta-4, and WorldEdit v6.0.0 SNAPSHOT.

Error Code: http://pastebin.com/ba05x7ju

**Comment by rlf** [comment] 2015-01-19 22:24
Moved the trace to pastebin.

**Comment by rlf** [comment] 2015-01-19 22:30
And, removed all the traces from a broken PlotMe installation: http://pastebin.com/JiP44KSJ

It's caused by a "broken" island-config. Not sure how these occur, but you are not the first experiencing this issue.
Most likely, you have misused the `/usb` or `/dev` command - but I can't be sure.

**Comment by rlf** [comment] 2015-01-20 00:14
Fixed in RC1.60 - or, not fixed, but at least it won't throw the NPE anymore - odds are, the island config is still fubared.

**Comment by AppleTechMedia** [comment] 2015-01-20 16:49
So, whenever RC1.60 is released, I won't have that problem anymore, most likely?

**Comment by dutchy1001** [comment] 2015-01-21 20:26
To use the biome's you need to have the permission usb.biome.[biomename] or usb.biome.* (PermissionEX doesn't like the use of * ).
Invites have had a cleanup in the last few releases.

If the problem still excist with the latest version (https://github.com/rlf/uSkyBlock/releases/latest)  plz reopen this issue.

**Closed by dutchy1001** 2015-01-21 20:26 UTC
Labels: ready for test
