### ISSUE TITLE
Island party bug

### ISSUE THREAD

**Issue by MrFiliper** [rlf/uSkyBlock#807] opened 2016-07-01 22:49 UTC
_Please paste the output from `/usb version` below_
```
�Name: �uSkyBlock�
�Version: �2.6.12�
�Description: �Ultimate SkyBlock v2.6.12-9e2d30-413�
�Language: �cs (cs)�
�------------------------------�
�Server: �CraftBukkit git-Spigot-c3e4052-1953f52 (MC: 1.10)�
�------------------------------�
��Vault �1.5.6-b49 �(�ENABLED�)�
��WorldEdit �6.1.3;7a097ca �(�ENABLED�)�
��WorldGuard �6.1.2;e38d98d �(�ENABLED�)�
��AsyncWorldEdit �2.2.2 �(�ENABLED�)�
��Multiverse-Core �2.5-b717 �(�ENABLED�)�
��Multiverse-NetherPortals �2.5-b675 �(�ENABLED�)�
�------------------------------�
```

_What steps will reproduce the problem?_
1. Use command /is party
2. Click to player head
3. Give player permissions for setbiome, lock island... not working.

This isn't working only for minimum players. Here config for island: http://pastebin.com/ggu0fugH

Problem is for player Lawkam, leader can set other player permissions. but for player Lawkam can't.

**Comment by dutchy1001** [comment] 2016-07-01 22:54
do those other players have permission in there current rank?
If the party member doesn't have the permission that can be given through the party menu then it will not work.

**Comment by MrFiliper** [comment] 2016-07-01 22:57
Yes thay have.

**Comment by rlf** [comment] 2016-07-02 07:30
Duplicate. Caused by the mixed case of the player name.  Should be fixed when the UUID conversion is done (next release).
Ofc. We need to test this after the UUID import  dutchy1001.

**Comment by dutchy1001** [comment] 2016-07-02 08:25
aye

**Comment by dutchy1001** [comment] 2016-07-04 22:14
in the latest dev build this issue is fixed.

**Comment by dutchy1001** [comment] 2016-07-06 15:02
As no further comments are made this is classed as being fixed.

**Closed by dutchy1001** 2016-07-06 15:02 UTC
Labels: S duplicate, T tested awaiting reporter
