### ISSUE TITLE
ServerCommandEvent

### ISSUE THREAD

**Issue by Victhetiger** [rlf/uSkyBlock#753] opened 2016-05-25 20:34 UTC
Hi USkyblock Team,

I'm currently having some issues when I run a command.

I'm using: Spigot 1.9.4
and USkyblock 2.6.4

Here's the error: http://prntscr.com/b8f5wx

Sincerely,
Victhetiger

**Comment by dutchy1001** [comment] 2016-05-25 21:28
Can you post the full output of ```/usb version```, this way we can see if the default setup is correct.

As it shows placeholders issue's in the log you might need to add [MVdWPlaceholderAPI](https://www.spigotmc.org/resources/mvdwplaceholderapi.11182/)
Let me know if that fixed your issue.

**Comment by Victhetiger** [comment] 2016-05-25 21:31
Here you go: http://prntscr.com/b8fy91

**Comment by SgtLegoTown** [comment] 2016-05-26 00:24
can you look in the config for the following settings at the bottom of the config 

placeholder:

  # Hooks into MVdWPlaceholderAPI
  mvdwplaceholderapi: false

  # uSkyBlock native placeholders for chat messages and format
  chatplaceholder: false

  # uSkyBlock native placeholders for server-commands
  servercommandplaceholder: false

and what chat plugin do you use ?

**Comment by Victhetiger** [comment] 2016-05-26 02:10
All 3 of these are set to true, I'm currently using EssentialsChat.

**Comment by SgtLegoTown** [comment] 2016-05-26 04:29
set them to false pls and try again ..

**Comment by rlf** [comment] 2016-05-26 05:39
This bug has been fixed in later versions.
You can disable the "internal placeholders", i.e.:
```
  # uSkyBlock native placeholders for chat messages and format
  chatplaceholder: false

  # uSkyBlock native placeholders for server-commands
  servercommandplaceholder: false
```
As SgtLego stated - and the bug shouldn't manifest it self anymore.

**Comment by Victhetiger** [comment] 2016-05-29 17:56
Thank you very much, it is now fixed.

**Comment by SgtLegoTown** [comment] 2016-05-29 20:29
as the issue is fixed in later versions and this is a work around for other version I close the topic now

**Closed by SgtLegoTown** 2016-05-29 20:29 UTC
Labels: S old version
